Repository goreleaser/goreleaser, pull requests merged in 2019-08, with the labels that each got.

#1111 test: add error handling
  internal/pipe/build/build_test.go
  internal/pipe/sign/sign_test.go
Labels: invalid

#1116 docs: supported gitlab versions
  .github/ISSUE_TEMPLATE/Bug_report.md
  go.mod
  go.sum
  www/content/quick-start.md
  www/content/release.md
Labels: docs

#1114 feat: gitea release support
  go.mod
  go.sum
  internal/client/client.go
  internal/client/client_test.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  pkg/config/config.go
  pkg/context/context.go
  www/content/environment.md
  www/content/homebrew.md
  www/content/release.md
  www/content/scoop.md
Labels: enhancement
