Repository goreleaser/goreleaser, pull requests merged in 2020-03, with the labels that each got.

#1380 feat: improve output a bit
  internal/middleware/logging.go
  internal/pipe/artifactory/artifactory.go
  internal/pipe/before/before.go
  internal/pipe/blob/blob.go
  internal/pipe/docker/docker.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/release/release.go
  internal/pipe/scoop/scoop.go
  internal/pipe/semver/semver.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/upload/upload.go
Labels: enhancement

#1412 chore(deps): bump code.gitea.io/sdk/gitea from 0.11.0 to 0.11.2
  go.mod
  go.sum
Labels: automerge, dependencies

#1407 refactor: simplify retries
  go.mod
  go.sum
  internal/client/client.go
  internal/pipe/release/release.go
Labels: automerge, enhancement
