Repository goreleaser/goreleaser, pull requests merged in 2020-05, with the labels that each got.

#1492 docs: GoReleaser Action v2
  www/content/actions.md
Labels: automerge, docs

#1493 feat: allow to template signs.args
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
  www/content/sign.md
Labels: automerge, enhancement

#1481 feat: Add support for custom publishers
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/exec/exec.go
  internal/exec/exec_mock.go
  internal/exec/exec_mock_test.go
  internal/exec/exec_test.go
  internal/logext/writer.go
  internal/pipe/custompublishers/custompublishers.go
  internal/pipe/publish/publish.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/config/config.go
  www/content/publishers.md
  www/content/templates.md
Labels: automerge, enhancement

#1494 docs: Use template for signs.args in GitHub Action doc
  www/content/actions.md
Labels: automerge, docs

#1495 feat: Use tools.go paradigm for external dependencies
  Makefile
  go.mod
  go.sum
  main.go
  tools.go
Labels: automerge, enhancement

#1496 feat: Add go.sum verification workflow
  .github/workflows/gosum.yml
Labels: automerge, enhancement

#1501 docs: improvements
  www/docs/ci/actions.md
  www/docs/ci/circle.md
  www/docs/ci/cloudbuild.md
  www/docs/ci/drone.md
  www/docs/ci/semaphore.md
  www/docs/contributing.md
  www/docs/customization/archive.md
  www/docs/customization/blob.md
  www/docs/customization/build.md
  www/docs/customization/checksum.md
  www/docs/customization/docker.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/nfpm.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/scoop.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/upload.md
  www/docs/deprecations.md
  www/docs/environment.md
  www/docs/install.md
  www/docs/intro.md
  www/docs/limitations/cgo.md
  www/docs/limitations/semver.md
  www/docs/links.md
  www/docs/overrides/home.html
  www/docs/quick-start.md
  www/docs/sponsors.md
  www/docs/tutorials.md
  www/mkdocs.yml
Labels: enhancement

#1502 chore(ci): remove travis
  .travis.yml
  snap.login.enc
Labels: automerge, enhancement

#1505 docs: Use GitHub Action badge
  README.md
Labels: automerge, enhancement

#1506 chore(ci): htmltest workflow
  .github/workflows/docs.yml
  www/htmltest.yml
Labels: automerge, enhancement

#1504 docs: some other improvements
  www/docs/customization/templates.md
  www/docs/overrides/main.html
Labels: automerge, enhancement

#1515 fix(ci): use GH_PAT to release
  .github/workflows/build.yml
Labels: automerge, bug

#1519 fix: improve docker logs and errors
  internal/pipe/docker/docker.go
Labels: automerge, bug

#1529 fix(ci): htmltest failing checks
  www/htmltest.yml
Labels: automerge, bug

#1528 fix(ci): unshallow history
  .github/workflows/build.yml
Labels: automerge, bug

#1539 fix: windows filenames
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: automerge, bug

#1542 fix: include go as a dependency of the brew tap
  .goreleaser.yml
Labels: automerge, bug

#1545 fix(ci): Fix invalid cross-device link
  .github/workflows/build.yml
Labels: automerge

#1546 chore(deps): bump code.gitea.io/sdk/gitea from v0.11.3 to v0.12.0
  go.mod
  go.sum
  internal/client/gitea.go
Labels: automerge, dependencies

#1551 chore: auto-label size, assign to project
  .github/workflows/assigner.yml
  .github/workflows/labeler.yml
Labels: automerge, enhancement

#1540 fix: cgo docker image
  Dockerfile
  Dockerfile.cgo
Labels: automerge, bug, size/XS

#1543 fix: include golang as a dependency of deb/rpms
  .goreleaser.yml
Labels: automerge, enhancement, size/XS

#1552 feat: allow signing only the source
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
  www/docs/customization/sign.md
Labels: automerge, enhancement, size/M

#1557 feat: Expose semver for snapshots
  internal/tmpl/tmpl.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: automerge, enhancement, size/M

#1554 feat: add support brew dependency types
  .goreleaser.yml
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/binary_overridden.rb.golden
  internal/pipe/brew/testdata/custom_block.rb.golden
  internal/pipe/brew/testdata/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/custom_require.rb.golden
  internal/pipe/brew/testdata/default.rb.golden
  internal/pipe/brew/testdata/default_gitlab.rb.golden
  internal/pipe/brew/testdata/github_enterprise_url.rb.golden
  internal/pipe/brew/testdata/gitlab_enterprise_url.rb.golden
  internal/pipe/brew/testdata/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/multiple_armv7.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: automerge, enhancement, size/M

#1555 docs: bump ghaction-import-gpg
  www/docs/ci/actions.md
Labels: automerge, size/XS

#1559 fix: brew dependency: string or struct
  pkg/config/config.go
  pkg/config/config_homebrew_dependency_test.go
Labels: automerge, enhancement, size/M

#1561 fix(ci): Remove workaround for invalid cross-device link
  .github/workflows/build.yml
Labels: automerge, size/XS

#1535 feat: Added extra files to blob
  .golangci.yml
  internal/extrafiles/extra_files.go
  internal/extrafiles/extra_files_test.go
  internal/extrafiles/testdata/file1.golden
  internal/extrafiles/testdata/file2.golden
  internal/extrafiles/testdata/file3.gold
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/testdata/file.golden
  internal/pipe/blob/upload.go
  internal/pipe/release/release.go
  pkg/config/config.go
  www/docs/customization/blob.md
Labels: size/L

#1563 chore(deps): bump github.com/golangci/golangci-lint from 1.23.7 to 1.27.0
  .golangci.yml
  go.mod
  go.sum
  internal/artifact/artifact.go
  internal/builders/golang/build.go
  internal/client/client.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/deprecate/deprecate.go
  internal/exec/exec.go
  internal/git/git.go
  internal/http/http.go
  internal/ids/ids.go
  internal/linux/arch.go
  internal/logext/writer.go
  internal/pipe/archive/archive.go
  internal/pipe/artifactory/artifactory.go
  internal/pipe/before/before.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/upload.go
  internal/pipe/brew/brew.go
  internal/pipe/build/build.go
  internal/pipe/changelog/changelog.go
  internal/pipe/checksums/checksums.go
  internal/pipe/custompublishers/custompublishers.go
  internal/pipe/defaults/defaults.go
  internal/pipe/dist/dist.go
  internal/pipe/docker/docker.go
  internal/pipe/effectiveconfig/config.go
  internal/pipe/env/env.go
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/pipe.go
  internal/pipe/project/project.go
  internal/pipe/publish/publish.go
  internal/pipe/release/release.go
  internal/pipe/scoop/scoop.go
  internal/pipe/semver/semver.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapshot/snapshot.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/upload/upload.go
  internal/semerrgroup/sem.go
  internal/testlib/git.go
  internal/testlib/skip.go
  internal/tmpl/tmpl.go
  pkg/archive/gzip/gzip.go
  pkg/archive/targz/targz.go
  pkg/archive/tarxz/tarxz.go
  pkg/archive/zip/zip.go
  pkg/build/build.go
  pkg/config/config.go
  pkg/context/context.go
Labels: automerge, size/XL

#1565 chore(deps): bump github.com/goreleaser/nfpm from 1.2.1 to 1.3.0
  go.mod
  go.sum
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: automerge, enhancement, size/XS

#1568 fix: Brew versioned formulae now supported
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: automerge, size/XS

#1569 docs: Format markdown tables
  www/docs/ci/actions.md
  www/docs/customization/build.md
  www/docs/customization/templates.md
Labels: automerge, docs, size/L

#1573 docs: Fix link to "sign"
  www/docs/ci/actions.md
Labels: size/XS

#1578 chore(ci): change auto go mod tidy commit msg
  .github/workflows/gosum.yml
Labels: automerge, enhancement, size/XS

#1575 feat: Add support for templated release notes, header and footer
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/changelog/testdata/changes-templated.md
  internal/pipe/changelog/testdata/release-footer-templated.md
  internal/pipe/changelog/testdata/release-header-templated.md
Labels: size/M
