Repository goreleaser/goreleaser, pull requests merged in 2020-08, with the labels that each got.

#1721 fix(ci): htmltest failing with 416 on some sites
  .github/workflows/docs.yml
  www/htmltest.yml
Labels: automerge, bug, size/XS

#1703 feat: log into Github package registry with token
  scripts/entrypoint.sh
Labels: size/XS

#1740 fix: ignore git warnings
  internal/git/git.go
  internal/git/git_test.go
  internal/testlib/git.go
Labels: automerge, bug, size/M

#1747 fix: windows shellwords
  go.mod
  go.sum
Labels: bug, size/XS

#1754 docs: make commands copy-paste friendly
  CONTRIBUTING.md
  www/docs/customization/release.md
  www/docs/customization/scoop.md
  www/docs/deprecations.md
  www/docs/install.md
  www/docs/quick-start.md
Labels: automerge, docs, size/L

#1752 feat: log build hooks
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
Labels: enhancement, size/M

#1756 fix: brew name template
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/foo_is_bar.rb.golden
Labels: bug, size/M

#1758 feat: update to Go 1.15 image
  Dockerfile
Labels: size/XS

#1757 fix(brew) create file if skip is set
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/pipe.go
  internal/pipe/pipe_test.go
Labels: bug, size/L

#1760 feat: allow to disable checksum pipe
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  pkg/config/config.go
  www/docs/customization/checksum.md
Labels: enhancement, size/S

#1771 typo: `this` to `these`
  www/docs/customization/templates.md
Labels: size/XS

#1776 fix:make minio based tests run locally again.
  internal/pipe/blob/blob_minio_test.go
Labels: size/XS

#1775 feat: Add `gobinary` option to build configs.
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: size/S
