Repository goreleaser/goreleaser, pull requests merged in 2020-04, with the labels that each got.

#1416 feat: use maximum compression for gzip and zip archives
  pkg/archive/gzip/gzip.go
  pkg/archive/targz/targz.go
  pkg/archive/zip/zip.go
Labels: automerge, enhancement

#1419 feat: build.skip option, support for library projects
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  pkg/config/config.go
  www/content/build.md
Labels: automerge, enhancement

#1420 fix: scoop binary names
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: automerge, bug

#1423 docs: Use "brews" plural form in documentation
  www/content/homebrew.md
Labels: automerge, docs

#1425 feat: split brew tap in 2 steps
  internal/artifact/artifact.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  internal/pipe/scoop/scoop.go
  internal/pipeline/pipeline.go
Labels: automerge, bug, enhancement

#1434 fix: brew no token
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: automerge, bug

#1430 feat(pipe/build): Report hook error in addition to stdout
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
Labels: automerge, enhancement

#1429 test: Allow tests to run in parallel without failing
  internal/pipe/build/build_test.go
Labels: automerge, enhancement

#1379 feat: upload source archive
  internal/artifact/artifact.go
  internal/http/http.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/openbucket.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/sign/sign.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/content/source.md
Labels: enhancement, pinned

#1437 feat: better shellwords on hooks
  go.mod
  go.sum
  internal/pipe/before/before.go
  internal/pipe/before/before_test.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
Labels: enhancement

#1435 feat: improve check command
  .goreleaser.yml
  .travis.yml
  internal/deprecate/deprecate.go
  internal/deprecate/deprecate_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/upload/upload.go
  main.go
  main_test.go
  pkg/context/context.go
  www/content/ci.md
Labels: automerge, enhancement

#1422 feat: xz compression
  go.mod
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/archive/tarxz/tarxz.go
  pkg/archive/tarxz/tarxz_test.go
Labels: automerge, enhancement

#1441 docs: add tar.xz to www content
  www/content/archive.md
Labels: automerge, docs

#1450 fix: correct the spelling of "snapshotting"
  internal/pipe/snapshot/snapshot.go
Labels: automerge, bug

#1449 fix: snap package apps with multiple binaries
  internal/pipe/snapcraft/snapcraft.go
Labels: automerge, bug

#1442 feat: remove deprecated nfpm options and puts
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/upload/upload.go
  pkg/config/config.go
  www/content/deprecations.md
Labels: enhancement

#1458 fix: scoop wrap_in_directory
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/test_buildmanifest_wrap.json.golden
Labels: automerge, bug

#1459 chore(deps): bump github.com/xanzy/go-gitlab from 0.29.0 to 0.31.0
  go.mod
  go.sum
  internal/client/gitlab.go
Labels: automerge, enhancement

#1472 feat: refactor main.go to spf13/cobra
  cmd/check.go
  cmd/check_test.go
  cmd/config.go
  cmd/config_test.go
  cmd/error.go
  cmd/init.go
  cmd/init_test.go
  cmd/release.go
  cmd/release_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/testdata/good.yml
  cmd/testdata/invalid.yml
  cmd/testdata/unmarshal_error.yml
  cmd/util_test.go
  go.mod
  go.sum
  main.go
  main_test.go
Labels: enhancement

#1476 fix: builds.binary template
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build_test.go
Labels: automerge, bug

#1474 feat: improve skip-publish behavior
  internal/artifact/artifact.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/upload.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/docker/docker.go
  internal/pipe/publish/publish.go
  internal/pipe/publish/publish_test.go
  internal/pipe/release/release.go
  internal/pipe/scoop/scoop.go
  internal/pipeline/pipeline.go
Labels: automerge, bug

#1467 feat(scoop): provide config option to change commit message
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  www/content/scoop.md
Labels: automerge, enhancement

#1480 fix: blob data race
  internal/pipe/blob/blob.go
  internal/pipe/blob/upload.go
Labels: automerge, bug
