Repository goreleaser/goreleaser, pull requests merged in 2020-11, with the labels that each got.

#1883 chore(deps): update nfpm
  go.mod
  go.sum
Labels: automerge, size/XS

#1877 fix: install completions with homebrew
  .gitignore
  .goreleaser.yml
  scripts/completions.sh
Labels: enhancement, size/S

#1886 feat: validate goos, goarch, goarm and gomips
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/build/build.go
  pkg/build/build_test.go
Labels: automerge, size/L

#1885 feat: use proxy from environment
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/http/http.go
Labels: automerge, size/XS

#1849 Add packager-specific nfpm config (#1829)
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nfpm/testdata/privkey.gpg
  internal/pipe/nfpm/testdata/rsa.priv
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: size/L

#1888 feat: support replaces on nfpm
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: automerge, size/S

#1889 feat: replace zglob with fileglob
  go.mod
  go.sum
  internal/extrafiles/extra_files.go
  internal/extrafiles/extra_files_test.go
  internal/extrafiles/testdata/sub/file5.golden
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/release/release_test.go
Labels: enhancement, size/L

#1892 feat: nfpm rpm.summary and nfpm.ghost_files
  internal/pipe/nfpm/nfpm.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/S

#1894 fix: improve completions
  cmd/build.go
  cmd/check.go
  cmd/completion.go
  cmd/init.go
  cmd/release.go
  cmd/root.go
Labels: automerge, enhancement, size/M

#1899 fix: dont fail if there is a .go directory
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: automerge, bug, size/M

#1907 add debconf-templates cookbook
  www/docs/cookbooks/debconf-templates.md
  www/docs/customization/nfpm.md
  www/mkdocs.yml
Labels: size/M

#1906 feat: add support for git branch in templates
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: automerge, enhancement, size/M

#1909 docs: fixing internal links that result in a broken navigation sidebar
  www/docs/customization/archive.md
  www/docs/customization/blob.md
  www/docs/customization/build.md
  www/docs/customization/checksum.md
  www/docs/customization/docker.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/milestone.md
  www/docs/customization/nfpm.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/snapcraft.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/upload.md
  www/docs/limitations/semver.md
Labels: size/M

#1547 feat: Gitea client add create file function
  internal/client/client_test.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/pipe/defaults/defaults.go
  internal/pipe/defaults/defaults_test.go
  pkg/config/config.go
  www/docs/environment.md
Labels: size/L

#1917 fix: prevent error if "dockerfile" isn't set
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: size/S

#1918 fix: don't append empty header/footer to changelog
  internal/pipe/changelog/changelog.go
Labels: automerge, size/S

#1919 fix: ensure Changelog ends on a newline
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: size/M

#1911 feat: make generated brew formulas `brew audit` compatible (#1908)
  .goreleaser.yml
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/custom_block.rb.golden
  internal/pipe/brew/testdata/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/custom_require.rb.golden
  internal/pipe/brew/testdata/default.rb.golden
  internal/pipe/brew/testdata/default_gitlab.rb.golden
  internal/pipe/brew/testdata/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/test.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: size/M

#1922 Support __completeNoDesc hidden command
  cmd/root.go
Labels: size/XS

#1923 feat: multi-arch docker images
  .github/workflows/build.yml
  .goreleaser.yml
  Dockerfile
  Dockerfile.cgo
  internal/pipe/docker/doc.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/docker/testdata/Dockerfile.arch
  internal/pipe/publish/publish.go
  pkg/config/config.go
  www/docs/customization/docker_manifest.md
  www/mkdocs.yml
Labels: size/XL

#1924 feat: install build-base on main img, drop -cgo img
  .goreleaser.yml
  Dockerfile
  Dockerfile.cgo
Labels: automerge, enhancement, size/M

#1925 feat: add docker manifests to release notes
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/release1.golden
Labels: automerge, enhancement, size/M
