Repository goreleaser/goreleaser, pull requests merged in 2020-07, with the labels that each got.

#1640 fix: update nfpm to v1.3.2
  go.mod
  go.sum
Labels: bug, size/XS

#1647 docs: Fix typo
  www/docs/customization/scoop.md
Labels: size/XS

#1649 refactor: align Homebrew repo handling with Scoop
  .goreleaser.yml
  internal/client/client.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/deprecate/deprecate.go
  internal/deprecate/testdata/output.txt.golden
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/custom_block.rb.golden
  internal/pipe/brew/testdata/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/custom_require.rb.golden
  internal/pipe/brew/testdata/default.rb.golden
  internal/pipe/brew/testdata/default_gitlab.rb.golden
  internal/pipe/brew/testdata/github_enterprise_url.rb.golden
  internal/pipe/brew/testdata/gitlab_enterprise_url.rb.golden
  internal/pipe/brew/testdata/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/multiple_armv7.rb.golden
  internal/pipe/defaults/defaults.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/deprecations.md
Labels: size/XL

#1641 feat: deterministic / reproducible build support
  .goreleaser.yml
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/git/git.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/testlib/git.go
  internal/tmpl/tmpl.go
  pkg/config/config.go
  pkg/context/context.go
  www/docs/customization/build.md
  www/docs/customization/templates.md
Labels: enhancement, size/L

#1650 feat: support custom tokens in Homebrew & Scoop
  internal/client/client.go
  internal/client/config.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/customization/scoop.md
Labels: enhancement, size/L

#1654 docs: add missing quotes around templating syntax
  www/docs/customization/homebrew.md
  www/docs/customization/scoop.md
Labels: docs, size/XS

#1658 chore(deps): bump code.gitea.io/sdk/gitea from v0.12.0 to v0.12.1
  go.mod
  go.sum
  internal/client/gitea_test.go
Labels: size/XS

#1657 feat: support closing milestones
  internal/client/client.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/git/config.go
  internal/git/config_test.go
  internal/git/git_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/milestone/doc.go
  internal/pipe/milestone/milestone.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/publish/publish.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/milestone.md
  www/mkdocs.yml
Labels: enhancement, size/XL

#1667 docs: Update quick-start.md
  www/docs/quick-start.md
Labels: automerge, size/XS

#1676 docs: configuring with Cirrus CI
  www/docs/ci/cirrus.md
  www/mkdocs.yml
Labels: size/S

#1677 docs: fix OCI annotation example
  www/docs/customization/docker.md
Labels: size/XS

#1679 fix: Completer script link errors for snapcraft
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
Labels: size/XS

#1680 refactor: avoid copying the completer multiple times
  internal/pipe/snapcraft/snapcraft.go
Labels: size/M

#1698 fix: better handle before hooks errors
  internal/pipe/before/before.go
  internal/pipe/before/before_test.go
  internal/pipe/before/testdata/foo.sh
Labels: enhancement, size/M

#1702 feat: make goos and goarch available in hooks
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/tmpl/tmpl.go
  pkg/build/build.go
Labels: automerge, enhancement, size/M

#1704 docs: update bintray instructions
  www/docs/customization/bintray.md
Labels: size/XS

#1706 fix: Fix indent of yaml generated by `init`
  internal/static/config.go
  internal/static/config_test.go
Labels: size/M

#1707 remove --pull option from docker run
  www/docs/ci/gitlab.md
Labels: size/XS

#1711 feat(pipeline): change the pipeline order to support additional template variables
  internal/pipeline/pipeline.go
Labels: size/XS
