Repository goreleaser/goreleaser, pull requests merged in 2020-12, with the labels that each got.

#1931 feat: add support for scripts in Scoop manifests
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/test_buildmanifest_pre_post_install.json.golden
  pkg/config/config.go
  www/docs/customization/scoop.md
Labels: size/M

#1805 feat: IDs filter for Checksums pipe
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  pkg/config/config.go
  www/docs/customization/checksum.md
Labels: automerge, enhancement, size/L

#1943 docs: add new tutorial
  www/docs/tutorials.md
Labels: size/XS

#1945 refactor(test): use testing.TB Cleanup and Tempdir
  cmd/build_test.go
  cmd/config_test.go
  cmd/init_test.go
  cmd/release_test.go
  cmd/root_test.go
  cmd/util_test.go
  internal/artifact/artifact_test.go
  internal/builders/golang/build_test.go
  internal/exec/exec_test.go
  internal/git/config_test.go
  internal/git/git_test.go
  internal/http/http_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/build/build_test.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/defaults/defaults_test.go
  internal/pipe/dist/dist_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/effectiveconfig/config_test.go
  internal/pipe/git/git_test.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/sourcearchive/source_test.go
  internal/pipe/upload/upload_test.go
  internal/testlib/git.go
  internal/testlib/git_test.go
  internal/testlib/mktemp.go
  internal/testlib/mktemp_test.go
  pkg/archive/archive_test.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip_test.go
Labels: automerge, enhancement, size/XL

#1946 chore(deps): bump nfpm
  go.mod
  go.sum
Labels: dependencies, size/XS

#1944 fix: nfpm signing error with `--skip-sign` when gpg key is not found
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: size/M

#1955 docs: unify naming of .goreleaser.yml file
  cmd/testdata/good.yml
  internal/static/config.go
  www/docs/customization/archive.md
  www/docs/customization/build.md
  www/docs/customization/docker_manifest.md
  www/docs/customization/env.md
  www/docs/customization/sign.md
  www/docs/deprecations.md
  www/docs/quick-start.md
Labels: size/S

#1958 feat: allow automatic snapshot on dirty state
  .github/workflows/build.yml
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  internal/git/git.go
  internal/git/git_test.go
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  www/docs/customization/snapshots.md
Labels: size/L

#1962 Revert "feat: allow automatic snapshot on dirty state"
  .github/workflows/build.yml
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  internal/git/git.go
  internal/git/git_test.go
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  www/docs/customization/snapshots.md
Labels: size/L

#1964 feat: ugprade nfpm
  go.mod
  go.sum
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
  www/docs/deprecations.md
Labels: automerge, enhancement, size/L

#1968 feat: upgrade nfpm
  go.mod
  go.sum
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
  www/docs/deprecations.md
Labels: automerge, enhancement, size/M

#1970 docs: add changie to changelog generators
  www/docs/customization/release.md
Labels: size/XS

#1973 docs: improve docker_manifest examples
  www/docs/customization/docker_manifest.md
Labels: automerge, docs, size/S

#1972 fix(docker): handle empty docker images
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: automerge, bug, size/M

#1974 chore(ci): improve dockerfile/manifest
  .goreleaser.yml
  Dockerfile
Labels: automerge, enhancement, size/XS

#1978 fix: manifest with no parallelism
  internal/pipe/docker/manifest.go
Labels: automerge, bug, size/XS

#1979 feat: simplify docker images
  .goreleaser.yml
Labels: automerge, enhancement, size/S
