Repository goreleaser/goreleaser, pull requests merged in 2020-06, with the labels that each got.

#1587 fix: docker images: bzr
  Dockerfile
  Dockerfile.cgo
Labels: automerge, bug, size/XS

#1553 feat: Support custom command and extra files in snaps
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/snapcraft/testdata/extra-file-2.txt
  internal/pipe/snapcraft/testdata/extra-file.txt
  pkg/config/config.go
  www/docs/customization/snapcraft.md
Labels: automerge, enhancement, size/L

#1594 docs: generate static/releases.json
  .gitignore
  Makefile
  scripts/get-releases.sh
Labels: automerge, docs, enhancement, size/S

#1595 docs: fix vercel deploy
  .gitignore
  Makefile
Labels: bug, docs, size/XS

#1596 docs: Documentation to include simple multiple binary example
  www/docs/customization/build.md
Labels: size/M

#1605 fix: removed unused code
  internal/static/config.go
  internal/static/doc.go
  internal/static/usage.go
Labels: automerge, enhancement, size/M

#1607 docs: remove incorrect quotes
  www/docs/customization/docker.md
Labels: size/XS

#1610 docs: unshallow action
  .github/workflows/build.yml
  www/docs/ci/actions.md
Labels: automerge, docs, enhancement, size/S

#1611 docs: action version semver range
  www/docs/ci/actions.md
Labels: automerge, docs, size/XS

#1617 fix: docker login using password stdin
  scripts/entrypoint.sh
Labels: automerge, enhancement, size/XS

#1621 feat: Install make into docker image
  Dockerfile
Labels: enhancement, size/XS

#1620 feat: add nfpm meta mackages
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/L

#1625 fix: use correct filename for GCS downloads
  internal/pipe/blob/upload.go
Labels: size/XS
