Repository goreleaser/goreleaser, pull requests merged in 2021-09, with the labels that each got.

#2435 fix: build dir that dont exist yet
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/builders/golang/testdata/.gitkeep
Labels: bug, size/M

#2436 feat: support links inside archives
  pkg/archive/targz/targz.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/testdata/link.txt
  pkg/archive/testdata/regular.txt
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
Labels: enhancement, size/M

#2449 style(ci): enhance Gitlab documentation
  www/docs/ci/gitlab.md
Labels: docs, size/XS

#2448 feat: templateable nfpm key files
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#2447 feat: allow to template brew message
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/scoop/scoop.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: enhancement, size/L

#2406 feat: add support for checksum generation for extra files
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/checksums/testdata/foo.txt
  internal/pipe/checksums/testdata/foo/bar.txt
  pkg/config/config.go
  www/docs/customization/checksum.md
Labels: size/L

#2437 docs: update check instructions
  www/docs/install.md
Labels: enhancement, size/S

#2455 fix: link in example config to https
  internal/static/config.go
Labels: size/XS

#2457 fix: clean user information from remote url if it contains username and token
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
Labels: size/M

#2464 docs: ghaction-import-gpg v4
  www/docs/ci/actions.md
Labels: size/XS

#2466 feat: Add support for templating NFPM bindir
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: size/M

#2465 feat: support templates for scm urls
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/pipe/defaults/defaults.go
  internal/pipe/defaults/defaults_test.go
  www/docs/scm/gitea.md
  www/docs/scm/github.md
  www/docs/scm/gitlab.md
Labels: size/XL

#2473 fix: panic on gitlab create release
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: size/M

#2461 feat(docker): add buildpacks support
  internal/pipe/docker/api_buildpack.go
  internal/pipe/docker/api_buildpack_test.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  www/docs/customization/docker.md
Labels: size/L

#2475 refactor: improve build
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
  internal/builders/buildtarget/testdata/.gitkeep
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/tmpl/tmpl.go
  pkg/build/build.go
  pkg/config/config.go
Labels: size/L

#2478 feat: announce: discord
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/discord/discord.go
  internal/pipe/discord/discord_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce.md
  www/htmltest.yml
Labels: size/L

#2482 feat: announce: teams
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/teams/teams.go
  internal/pipe/teams/teams_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce.md
  www/htmltest.yml
Labels: size/L

#2489 docs: fix environment variable to be COSIGN_PWD
  www/docs/customization/docker_sign.md
Labels: size/XS

#2490 update cosign installer action to 1.2.0
  .github/workflows/build.yml
Labels: size/XS

#2485 feat: add SMTP support to the announces
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/smtp/smtp.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce.md
Labels: size/L

#2486 feat: use correct remote name of the current branch
  internal/git/config.go
  internal/git/config_test.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/release/release_test.go
  internal/testlib/git.go
Labels: size/S

#2493 fix(buildpacks): add if check when copying Dockerfile
  .github/workflows/build.yml
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: size/L

#2501 feat(docker): install tini to handle Ctrl+C
  Dockerfile
Labels: size/XS

#2502 refactor: split go mod into 2 pipes
  internal/pipe/gomod/doc.go
  internal/pipe/gomod/gomod proxy.go
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/gomod/gomod_test.go
  internal/pipeline/pipeline.go
Labels: enhancement, size/XL

#2474 feat: support subgroups in GitLab
  internal/git/config.go
  internal/git/config_test.go
Labels: enhancement, size/S

#2503 feat: removes deprecated non-semver allowance
  cmd/release.go
  internal/pipe/semver/semver.go
  internal/pipe/semver/semver_test.go
  www/docs/customization/fury.md
  www/docs/deprecations.md
Labels: enhancement, size/M

#2515 fix: brew/scoop panic
  internal/client/client.go
  internal/client/client_test.go
  internal/pipe/brew/brew.go
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
Labels: bug, size/M

#2521 fix: do not skip any defaults
  internal/pipe/defaults/defaults.go
Labels: bug, size/S

#2525 fix: run goreleaser via exec to handle ctrl+c
  scripts/entrypoint.sh
Labels: size/XS

#2527 fix: bug in handling gitlab-ci style urls
  internal/git/config.go
  internal/git/config_test.go
Labels: size/S

#2507 docs: improve customization section
  www/docs/customization/announce.md
  www/docs/customization/announce/discord.md
  www/docs/customization/announce/index.md
  www/docs/customization/announce/reddit.md
  www/docs/customization/announce/slack.md
  www/docs/customization/announce/smtp.md
  www/docs/customization/announce/teams.md
  www/docs/customization/announce/twitter.md
  www/docs/customization/artifactory.md
  www/docs/customization/blob.md
  www/docs/customization/checksum.md
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
  www/docs/customization/docker_sign.md
  www/docs/customization/fury.md
  www/docs/customization/homebrew.md
  www/docs/customization/index.md
  www/docs/customization/milestone.md
  www/docs/customization/nfpm.md
  www/docs/customization/scoop.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/htmltest.yml
  www/mkdocs.yml
Labels: docs, size/XL

#2529 docs: fix trailing slashes
  vercel.json
  www/htmltest.yml
Labels: bug, docs, size/XS

#2533 fix: regression on nil pointer check
  internal/client/github.go
Labels: size/XS

#2538 docs: Fix invalid personal access token URL
  www/docs/scm/gitlab.md
Labels: size/XS

#2509 feat: publish: GoFish integration
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/golden/golden.go
  internal/pipe/gofish/doc.go
  internal/pipe/gofish/food_template.go
  internal/pipe/gofish/gofish.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/gofish/testdata/TestFullFood.lua.golden
  internal/pipe/gofish/testdata/TestFullFoodLinuxOnly.lua.golden
  internal/pipe/gofish/testdata/TestFullFoodWindowsOnly.lua.golden
  internal/pipe/gofish/testdata/TestFullPipe/default.lua.golden
  internal/pipe/gofish/testdata/TestFullPipe/default_gitlab.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeNameTemplate.lua.golden
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/gofish.md
  www/htmltest.yml
  www/mkdocs.yml
Labels: enhancement, size/XXL

#2536 feat: announce: mattermost
  internal/pipe/announce/announce.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/mattermost/mattermost_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/mattermost.md
Labels: size/L

#2530 refactor: improve brew templates
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
Labels: enhancement, size/L

#2543 fix: docs: Missing mattermost docs on website
  www/htmltest.yml
  www/mkdocs.yml
Labels: size/XS

#2545 docs: update CircleCI example
  www/docs/ci/circle.md
Labels: size/XS
