Repository goreleaser/goreleaser, pull requests merged in 2021-08, with the labels that each got.

#2377 fix: sort tags by version not day of the week
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
Labels: bug, size/XS

#2380 fix: make scoop write .json when --skip-publish
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: size/M

#2390 fix: main check when using gomod.proxy
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_test.go
  pkg/config/config.go
Labels: bug, size/M

#2400 feat: remove deprecated docker options
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: enhancement, size/M

#2399 feat: add id to dockers and docker_manifests
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  pkg/config/config.go
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
Labels: enhancement, size/L

#2407 feat: support windows/arm64
  internal/builders/golang/build.go
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
  www/docs/deprecations.md
Labels: size/L

#2409 fix: upload gcs blobs to bucket root
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/upload.go
Labels: size/M

#2411 fix: Run 'go version' command in build.Dir
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/pipe/build/build_test.go
Labels: size/M

#2416 fix: prevent panic on invalid git remote url
  internal/git/config.go
  internal/git/config_test.go
Labels: size/M

#2417 fix: Change the init- and default-template for `snapshot.name_template`
  .goreleaser.yml
  cmd/testdata/good.yml
  internal/pipe/snapshot/snapshot.go
  internal/pipe/snapshot/snapshot_test.go
  internal/static/config.go
  www/docs/customization/snapshots.md
  www/docs/customization/templates.md
Labels: size/S

#2423 feat: sign docker images with cosign
  .github/workflows/build.yml
  cosign.key
  cosign.pub
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_docker.go
  internal/pipe/sign/sign_docker_test.go
  internal/pipe/sign/testdata/cosign/.gitignore
  internal/pipe/sign/testdata/cosign/cosign.key
  internal/pipe/sign/testdata/cosign/cosign.pub
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
  www/mkdocs.yml
Labels: enhancement, size/XL

#2408 feat: use go 1.17
  .github/workflows/build.yml
  .github/workflows/lint.yml
  CONTRIBUTING.md
  Dockerfile
  cmd/util_test.go
  go.mod
  internal/pipe/gomod/gomod_test.go
  www/docs/ci/actions.md
  www/docs/ci/circle.md
  www/docs/ci/codefresh.md
Labels: size/M

#2431 feat: announce: reddit
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/reddit/reddit.go
  internal/pipe/reddit/reddit_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce.md
Labels: enhancement, size/L
