Repository goreleaser/goreleaser, pull requests merged in 2021-10, with the labels that each got.

#2547 feat: some little fixes on the webpage
  www/docs/overrides/home.html
  www/docs/quick-start.md
Labels: size/XS

#2540 refactor: remove unused not impl error
  internal/client/client.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/gofish/gofish.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: enhancement, size/L

#2544 feat: add template support for homebrew tap owner
  internal/pipe/brew/brew.go
Labels: size/XS

#2539 Draft: feat: allow default branch to be used in Gitlab CreateFile
  internal/client/client.go
  internal/client/config.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: size/L

#2549 refactor: unifying client mocks
  internal/client/client.go
  internal/client/mock.go
  internal/pipe/brew/brew_test.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop_test.go
  pkg/context/context.go
Labels: enhancement, size/L

#2548 feat: changelog from github
  .goreleaser.yml
  internal/client/client.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/client/mock.go
  internal/client/testdata/github/compare.json
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/milestone/milestone_test.go
  pkg/config/config.go
  pkg/context/context.go
  www/docs/customization/changelog.md
  www/docs/customization/release.md
  www/mkdocs.yml
Labels: enhancement, size/L

#2550 test: speed up minio tests
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/upload.go
Labels: enhancement, size/L

#2551 feat: publish arm v7 variant
  .goreleaser.yml
Labels: enhancement, size/XS

#2557 feat: Replace Make with Task
  .github/workflows/build.yml
  CONTRIBUTING.md
  Taskfile.yml
Labels: size/L

#2561 fix: taskfile: rewerite task order of ci and add default taks
  Taskfile.yml
Labels: size/S

#2559 chore(ci): cache go-build results on github actions
  .github/workflows/build.yml
Labels: enhancement, size/XS

#2613 docs: add USERS.md to track users of goreleaser
  USERS.md
Labels: size/XS

#2614 Add Numary is USERS.md
  USERS.md
Labels: size/XS
