Repository goreleaser/goreleaser, pull requests merged in 2021-07, with the labels that each got.

#2326 pipe/release: template header and footer
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
Labels: size/S

#2328 chore(deps): bump github.com/spf13/cobra from 1.1.3 to 1.2.0
  cmd/completion.go
  cmd/completion_test.go
  cmd/root.go
  go.mod
  go.sum
  scripts/cmd_docs.sh
  www/docs/cmd/goreleaser.md
  www/docs/cmd/goreleaser_completion.md
  www/docs/cmd/goreleaser_completion_bash.md
  www/docs/cmd/goreleaser_completion_fish.md
  www/docs/cmd/goreleaser_completion_powershell.md
  www/docs/cmd/goreleaser_completion_zsh.md
Labels: size/L

#2335 fix: new gitlab releases throwing 404 due to API change #2334
  internal/client/gitlab.go
Labels: size/XS

#2343 feat: smaller releases.json
  scripts/get-releases.sh
Labels: bug

#2347 feat: file mappings in archives
  go.mod
  go.sum
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/archive/testdata/a/a.txt
  internal/pipe/archive/testdata/a/b/a.txt
  internal/pipe/archive/testdata/a/b/c/d.txt
  internal/pipe/defaults/defaults_test.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/archive/gzip/gzip.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/targz/targz.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
  pkg/config/config.go
  pkg/config/config_archive_files_test.go
  www/docs/customization/archive.md
Labels: enhancement

#2359 feat: moving some cmd logs to debug
  internal/exec/exec.go
  internal/gio/doc.go
  internal/gio/safe.go
  internal/gio/safe_test.go
  internal/logext/testdata/TestWriter/debug/0.txt.golden
  internal/logext/testdata/TestWriter/debug/1.txt.golden
  internal/logext/writer.go
  internal/logext/writer_test.go
  internal/pipe/before/before.go
  internal/pipe/before/before_test.go
  internal/pipe/build/build.go
  internal/pipe/docker/api.go
  internal/pipe/sign/sign.go
Labels: bug, enhancement, size/L

#2361 feat(snapcraft): manage channel upload
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  pkg/config/config.go
  www/docs/customization/snapcraft.md
Labels: enhancement, size/L

#2358 feat: inc parts of semver, change snapshot default name
  .goreleaser.yml
  cmd/testdata/good.yml
  internal/pipe/git/git.go
  internal/pipe/snapshot/snapshot.go
  internal/static/config.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/snapshots.md
  www/docs/customization/templates.md
Labels: enhancement, size/M

#2362 fix: copying file on docker pkg instead of hard linking
  internal/gio/copy.go
  internal/gio/copy_test.go
  internal/gio/hash.go
  internal/gio/testdata/somefile.txt
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
Labels: size/L

#2333 feat: add docker-buildx to Docker image
  Dockerfile
Labels: size/XS

#2363 fix: return an err with stdout/err when a command failed
  internal/builders/golang/build.go
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/pipe/docker/api.go
  internal/pipe/docker/api_docker.go
  internal/pipe/sign/sign.go
  internal/pipe/snapcraft/snapcraft.go
Labels: enhancement, size/M

#2371 docs: update use buildx syntax
  www/docs/customization/docker_manifest.md
Labels: size/XS
