Repository goreleaser/goreleaser, pull requests merged in 2021-04, with the labels that each got.

#2154 fix: artifactory checksum header
  internal/pipe/artifactory/artifactory.go
  internal/pipe/artifactory/artifactory_test.go
Labels: bug, size/L

#2164 docs: tune performance and theming of documentation
  www/docs/overrides/home.html
  www/mkdocs.yml
Labels: size/S

#2172 fix: ignore non-arm64/386 builds when building Scoop manifest
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: automerge, bug, size/M

#2173 fix: handle build.main being a go file when using gomod.proxy
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_test.go
  www/docs/customization/build.md
  www/docs/customization/gomod.md
Labels: automerge, bug, size/M

#2174 fix: improve output a bit
  internal/middleware/error.go
  internal/middleware/error_test.go
  internal/middleware/logging.go
  internal/pipe/artifactory/artifactory.go
  internal/pipe/blob/blob.go
  internal/pipe/brew/brew.go
  internal/pipe/changelog/changelog.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/custompublishers/custompublishers.go
  internal/pipe/docker/docker.go
  internal/pipe/gomod/gomod.go
  internal/pipe/milestone/milestone.go
  internal/pipe/pipe.go
  internal/pipe/pipe_test.go
  internal/pipe/release/release.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/snapshot/snapshot.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/upload/upload.go
  www/docs/customization/gomod.md
Labels: enhancement, size/L

#2177 feat: create discussions from releases
  go.mod
  go.sum
  internal/client/github.go
  pkg/config/config.go
  www/docs/customization/release.md
Labels: automerge, dependencies, size/M

#2182 Do not send an empty discussion category name
  internal/client/github.go
Labels: size/XS

#2179 feat: build single target and/or build id
  cmd/build.go
  cmd/build_test.go
Labels: enhancement, size/L

#2180 docs: document required GitHub Actions token privileges
  www/docs/ci/actions.md
Labels: automerge, docs, size/S

#2184 docs: add cmd docs
  .gitignore
  cmd/build.go
  cmd/completion.go
  cmd/docs.go
  cmd/release.go
  cmd/root.go
  go.sum
  scripts/cmd_docs.sh
  www/docs/cmd/goreleaser.md
  www/docs/cmd/goreleaser_build.md
  www/docs/cmd/goreleaser_check.md
  www/docs/cmd/goreleaser_completion.md
  www/docs/cmd/goreleaser_init.md
  www/docs/cmd/goreleaser_release.md
  www/mkdocs.yml
Labels: automerge, docs, size/L

#2188 fix: fd leak on gomod pipe
  internal/pipe/gomod/gomod.go
Labels: automerge, bug, size/XS

#2187 fix: several fd leaks (on tests)
  internal/artifact/artifact_test.go
  internal/client/gitea_test.go
  internal/http/http_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/dist/dist_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/env/env_test.go
  internal/pipe/git/git_test.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/release/release_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/upload/upload_test.go
  pkg/archive/archive_test.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip_test.go
  pkg/config/config_test.go
Labels: automerge, bug, size/L

#2189 refactor: use os and io packages intead of ioutil when possible
  cmd/util_test.go
  internal/artifact/artifact_test.go
  internal/builders/golang/build_test.go
  internal/exec/exec_test.go
  internal/http/http_test.go
  internal/pipe/artifactory/artifactory.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/upload.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/build/build_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/dist/dist.go
  internal/pipe/docker/docker_test.go
  internal/pipe/effectiveconfig/config.go
  internal/pipe/effectiveconfig/config_test.go
  internal/pipe/git/git_test.go
  internal/pipe/release/body_test.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/sourcearchive/source_test.go
  internal/pipe/upload/upload_test.go
  pkg/archive/gzip/gzip_test.go
  pkg/config/config.go
Labels: automerge, enhancement, size/L

#2191 feat: add %pretrans %posttrans scriptlets
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: automerge, enhancement, size/M
