Repository goreleaser/goreleaser, pull requests merged in 2021-06, with the labels that each got.

#2272 feat(nfpm): template homepage and description
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/homebrew.md
  www/docs/customization/nfpm.md
Labels: size/M

#2277 fix(publishers): inherit some system variables
  internal/exec/exec.go
  internal/exec/exec_mock.go
  internal/exec/exec_test.go
  www/docs/customization/hooks.md
  www/docs/customization/publishers.md
Labels: enhancement, size/L

#2286 feat: --auto-snapshot on dirty git tree
  .github/workflows/build.yml
  cmd/release.go
  cmd/release_test.go
  internal/pipe/git/git.go
  www/docs/cmd/goreleaser_release.md
Labels: enhancement, size/M

#2280 feat: builds. no_unique_dist_dir
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: enhancement, size/M

#2287 feat: remove :latest imgs from release notes
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/TestDescribeBody.golden
  internal/pipe/release/testdata/TestDescribeBodyWithDockerManifest.golden
  internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
Labels: enhancement, size/S

#2303 chore(ci): use htmltest action
  .github/workflows/docs.yml
  www/htmltest.yml
Labels: size/S

#2301 fix: empty build.tags and build.ldflags
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: bug, size/L

#2302 feat: docker_manifests.skip_push
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  pkg/config/config.go
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
Labels: enhancement, size/L

#2308 feat(nfpm): add support for APK pre/post upgrade scripts
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: automerge, enhancement, size/L

#2314 refactor: preparing for other docker implementations
  .goreleaser.yml
  internal/pipe/docker/api.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  pkg/config/config.go
  www/docs/customization/docker.md
  www/docs/deprecations.md
Labels: size/L

#2297 feat: use project id
  internal/client/gitlab.go
  www/docs/customization/release.md
Labels: size/M

#2315 feat: remove some nfpm deprecated options
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: size/L

#2319 refactor(docker): preparing for multiple backends
  internal/pipe/docker/api.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/docker/testdata/Dockerfile.arch
  pkg/config/config.go
Labels: size/L
