Repository goreleaser/goreleaser, pull requests merged in 2021-12, with the labels that each got.

#2708 feat: remove docker images from changelog
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/TestDescribeBody.golden
  internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
Labels: enhancement, size/L

#2715 feat: store artifact list into dist/artifacts.json
  cmd/build.go
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/golden/golden.go
  internal/pipe/artifacts/artifacts.go
  internal/pipe/artifacts/artifacts_test.go
  internal/pipe/artifacts/testdata/TestArtifacts.json.golden
  internal/pipeline/pipeline.go
Labels: size/L

#2720 chore(ci): fix descriptions for testing DEB/APK packages
  Taskfile.yml
Labels: size/XS

#2724 update documentation for signing when using cosign
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
Labels: size/S

#2725 fix: double-dash cosign flags
  internal/pipe/sign/sign_docker.go
  internal/pipe/sign/sign_docker_test.go
Labels: bug, size/XS

#2728 fix: jsonschema build ignore casing
  pkg/config/config.go
Labels: bug

#2722 docs(quickstart): minimum github_token perms
  www/docs/quick-start.md
Labels: size/XS

#2729 chore(ci): auto-assign milestone
  .github/workflows/milestone.yml
Labels: size/M

#2719 chore: rename yml to yaml in init command
  cmd/init.go
Labels: size/XS

#2733 feat: improve multiple tokens error
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  www/docs/errors/multiple-tokens.md
  www/mkdocs.yml
Labels: enhancement, size/M

#2573 feat: auto-refresh checksums
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/artifact/testdata/TestMarshalJSON.json.golden
  internal/pipe/blob/upload.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
Labels: size/L

#2730 feat: get annotated tag message
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/testlib/git.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: enhancement, size/M

#2739 chore(deps): update milestone and dependabot config
  .github/dependabot.yml
  .github/workflows/milestone.yml
Labels: dependencies, size/XS

#2740 chore(ci): run codeql analysis
  .github/workflows/codeql.yml
Labels: enhancement, size/S

#2731 feat: allow to always log signing output
  internal/logext/writer.go
  internal/pipe/sign/sign.go
  pkg/config/config.go
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
Labels: enhancement, size/S

#2744 feat: annotated tag contents
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/testlib/git.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: enhancement, size/M

#2741 Fix JSON schema for ReleaseNotesMode
  pkg/config/config.go
  www/docs/static/schema.json
Labels: bug, size/XS

#2749 test: improve scoop tests
  internal/pipe/scoop/scoop_test.go
Labels: size/M

#2748 fix: artifacts.json when type is archive
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/artifact/testdata/TestMarshalJSON.json.golden
  internal/pipe/scoop/scoop_test.go
Labels: bug, size/S

#2747 feat: improve universal binaries on krew/brew/gofish
  .goreleaser.yaml
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden
  internal/pipe/gofish/gofish.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/gofish/testdata/TestRunPipeUniversalBinaryNotReplacing.lua.golden
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/krew/testdata/TestRunPipeUniversalBinaryNotReplacing.yaml
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
Labels: enhancement, size/L

#2758 fix: logext shouldnt mess with default logger
  internal/logext/writer.go
Labels: bug, size/XS

#2648 feat: add sbom generation
  .github/workflows/build.yml
  .gitignore
  .goreleaser.yaml
  cmd/release.go
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/checksums/checksums.go
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/context/context.go
  pkg/defaults/defaults.go
  www/docs/customization/sbom.md
  www/docs/customization/sign.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#2757 fix: sign with cert only
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_docker_test.go
Labels: bug, size/L

#2716 feat: keyless signing
  .github/workflows/build.yml
  .goreleaser.yaml
  cosign.key
  cosign.pub
  www/docs/install.md
  www/docs/static/goreleaser.pub
Labels: enhancement, size/L

#2767 chore(ci): use download syft action
  .github/workflows/build.yml
Labels: size/XS

#2773 docs(ci): fix circle config example
  www/docs/ci/circle.md
Labels: size/XS

#2752 docs(docker): add section for overriding hard-coded image name
  www/docs/cookbooks/override-image-name.md
Labels: size/M

#2781 fix: do not group changelog when using github-native
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  pkg/config/config.go
  www/docs/customization/changelog.md
Labels: bug, size/M

#2779 feat: do not release goreleaser for arm6
  .goreleaser.yaml
  Taskfile.yml
Labels: enhancement, size/S

#2784 docs: rename in the docs goreleaser.yml to goreleaser.yaml
  cmd/root.go
  cmd/testdata/good.yml
  www/docs/ci/cloudbuild.md
  www/docs/ci/gitlab.md
  www/docs/ci/semaphore.md
  www/docs/cmd/goreleaser.md
  www/docs/cookbooks/build-go-modules.md
  www/docs/cookbooks/debconf-templates.md
  www/docs/customization/announce/discord.md
  www/docs/customization/announce/index.md
  www/docs/customization/announce/linkedin.md
  www/docs/customization/announce/mattermost.md
  www/docs/customization/announce/reddit.md
  www/docs/customization/announce/slack.md
  www/docs/customization/announce/smtp.md
  www/docs/customization/announce/teams.md
  www/docs/customization/announce/telegram.md
  www/docs/customization/announce/twitter.md
  www/docs/customization/archive.md
  www/docs/customization/artifactory.md
  www/docs/customization/blob.md
  www/docs/customization/build.md
  www/docs/customization/checksum.md
  www/docs/customization/dist.md
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
  www/docs/customization/env.md
  www/docs/customization/fury.md
  www/docs/customization/gofish.md
  www/docs/customization/gomod.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/includes.md
  www/docs/customization/index.md
  www/docs/customization/krew.md
  www/docs/customization/milestone.md
  www/docs/customization/monorepo.md
  www/docs/customization/nfpm.md
  www/docs/customization/project.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/scoop.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/templates.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/upload.md
  www/docs/deprecations.md
  www/docs/errors/no-main.md
  www/docs/errors/resource-not-accessible-by-integration.md
  www/docs/how-it-works.md
  www/docs/intro.md
  www/docs/quick-start.md
  www/docs/scm/gitea.md
  www/docs/scm/github.md
  www/docs/scm/gitlab.md
Labels: size/L

#2789 docs: update Drone CI integration
  www/docs/ci/drone.md
Labels: size/M

#2796 fix: nfpm empty dirs
  go.mod
  go.sum
Labels: size/XS

#2791 fix: logext STDERR use warn instead of error
  internal/logext/testdata/TestWriter/debug/1.txt.golden
  internal/logext/writer.go
Labels: size/XS

#2798 fix: sbom binary filter
  internal/pipe/sbom/sbom.go
Labels: size/XS

#2801 fix: artifacts.json should be 0644 instead of 0600
  internal/pipe/artifacts/artifacts.go
  internal/pipe/artifacts/artifacts_test.go
Labels: size/S
