Repository goreleaser/goreleaser, pull requests merged in 2021-01, with the labels that each got.

#1990 fix: buildx tests
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: enhancement, size/S

#1995 feat(nfpm): wire up two additional nfpm properties
  .gitignore
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
Labels: automerge, size/S

#2001 fix: Adds comments to formula template to conform to 'brew audit --strict --online'
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/binary_overridden.rb.golden
  internal/pipe/brew/testdata/custom_block.rb.golden
  internal/pipe/brew/testdata/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/custom_require.rb.golden
  internal/pipe/brew/testdata/default.rb.golden
  internal/pipe/brew/testdata/default_gitlab.rb.golden
  internal/pipe/brew/testdata/foo_is_bar.rb.golden
  internal/pipe/brew/testdata/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/test.rb.golden
  internal/pipe/brew/testdata/test_linux_only.rb.golden
Labels: size/M

#2000 refactor: use t instead of tt
  internal/builders/golang/build_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/env/env_test.go
  internal/pipe/sign/sign_test.go
  internal/tmpl/tmpl_test.go
Labels: automerge, bug, size/L

#1999 feat: add arm64 to the default goarch list
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build_test.go
  www/docs/customization/build.md
Labels: automerge, enhancement, size/XS

#2002 feat(http): support custom headers in http upload
  internal/http/http.go
  internal/http/http_test.go
  pkg/config/config.go
  www/docs/customization/upload.md
Labels: automerge, enhancement, size/M

#2003 feat: allow to use nfpm packages in the docker pipe
  .goreleaser.yml
  Dockerfile
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/defaults/defaults_test.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/testdata/Dockerfile.nfpm
  pkg/config/config.go
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
  www/docs/deprecations.md
Labels: automerge, enhancement, size/L

#2005 feat(http): resolve custom header template expressions
  internal/http/http.go
  internal/http/http_test.go
  www/docs/customization/upload.md
Labels: automerge, enhancement, size/M

#2007 feat: install completions on linux packages
  .goreleaser.yml
Labels: automerge, enhancement, size/XS

#1936 feat: add Os and Arch template options to the Binary name field
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  www/docs/customization/build.md
Labels: automerge, enhancement, size/L

#2015 feat: use num cpu as default parallelism
  cmd/build.go
  cmd/release.go
Labels: automerge, enhancement, size/XS

#2016 feat: compile to riscv64
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
Labels: automerge, enhancement, size/XS

#2018 docs: fix typo in bintray.md
  www/docs/customization/bintray.md
Labels: automerge, size/XS

#2030 fix: brew default install when using templates in the binary name
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/defaults/defaults_test.go
Labels: automerge, bug, size/M
