Repository goreleaser/goreleaser, pull requests merged in 2021-11, with the labels that each got.

#2619 refactor: organize config a bit
  internal/builders/golang/build_test.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  pkg/config/config_build_hook_test.go
  www/docs/static/schema-pro.json
Labels: size/L

#2624 docs: Add Ministry of Justice UK to list of users
  USERS.md
Labels: size/XS

#2620 feat(source): add prefix_template option
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  pkg/config/config.go
  www/docs/customization/source.md
Labels: size/M

#2623 fix: remove .git suffix by default from announcers
  internal/pipe/discord/discord.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/reddit/reddit.go
  internal/pipe/slack/slack.go
  internal/pipe/smtp/smtp.go
  internal/pipe/teams/teams.go
  internal/pipe/telegram/telegram.go
  internal/pipe/twitter/twitter.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/announce/discord.md
  www/docs/customization/announce/index.md
  www/docs/customization/announce/mattermost.md
  www/docs/customization/announce/reddit.md
  www/docs/customization/announce/slack.md
  www/docs/customization/announce/smtp.md
  www/docs/customization/announce/teams.md
  www/docs/customization/announce/telegram.md
  www/docs/customization/announce/twitter.md
  www/docs/customization/templates.md
Labels: size/M

#2630 chore: add iron security ref
  USERS.md
Labels: size/XS

#2631 docs: Add Compose Generator to list of users
  www/docs/users.md
Labels: size/XS

#2634 doc: add GoReleaser Extensions for Azure DevOps to docs
  www/docs/ci/azurepipelines.md
Labels: size/M

#2636 feat(ci): add cosign public key to releases
  .goreleaser.yml
Labels: size/XS

#2627 refactor: improve release defaults
  internal/pipe/release/release.go
Labels: bug, enhancement, size/M

#2626 feat: add message template support for git providers
  internal/pipe/git/git.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/reddit/reddit.go
  internal/pipe/slack/slack.go
  internal/pipe/smtp/smtp.go
  internal/pipe/teams/teams.go
  internal/pipe/telegram/telegram.go
  internal/pipe/twitter/twitter.go
  internal/tmpl/tmpl.go
  pkg/context/context.go
Labels: size/M

#2637 refactor: release url
  internal/pipe/git/git.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/announce/index.md
  www/docs/customization/templates.md
Labels: size/M

#2492 feat: announce: LinkedIn
  internal/pipe/announce/announce.go
  internal/pipe/linkedin/client.go
  internal/pipe/linkedin/client_test.go
  internal/pipe/linkedin/linkedin.go
  internal/pipe/linkedin/linkedin_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/linkedin.md
  www/mkdocs.yml
Labels: enhancement, size/L

#2638 feat: support github release notes
  internal/client/client.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/mock.go
  internal/client/testdata/github/releasenotes.json
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  www/docs/customization/changelog.md
Labels: enhancement, size/L

#2661 fix: [Bug]: changelog is too long
  internal/client/client.go
  internal/client/client_test.go
  internal/client/github.go
Labels: size/M

#2662 feat: sign with env and output certificate
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/http/http.go
  internal/http/http_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/upload.go
  internal/pipe/env/env.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_docker_test.go
  internal/pipe/sign/sign_test.go
  pkg/config/config.go
  pkg/context/context.go
  pkg/context/context_test.go
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
Labels: enhancement, size/L

#2663 feat: nfpm conventional file name
  .goreleaser.yml
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
  www/docs/customization/templates.md
Labels: enhancement, size/L

#2640 feat: update nfpm
  Taskfile.yml
  go.mod
  go.sum
  internal/deprecate/deprecate.go
  internal/deprecate/deprecate_test.go
  internal/deprecate/testdata/TestWriter.txt.golden
  internal/linux/arch.go
  internal/linux/arch_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/snapcraft/snapcraft.go
  www/docs/customization/nfpm.md
Labels: size/L

#2667 feat: templates on sign env
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
Labels: enhancement, size/M

#2668 feat: update nfpm to 2.9.2
  .github/workflows/build.yml
  go.mod
  go.sum
  pkg/config/config.go
  www/docs/customization/nfpm.md
  www/docs/deprecations.md
Labels: size/L

#2673 fix: add env to the sign schema
  www/docs/static/schema.json
Labels: size/XS

#2542 feat: add cosign tool in the goreleaser image
  Dockerfile
Labels: enhancement, size/XS

#2676 refactor: use os and io packages instead of io/ioutil
  internal/artifact/artifact_test.go
  internal/client/gitea_test.go
  internal/gio/copy_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/docker/docker.go
  internal/pipe/env/env_test.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config_test.go
Labels: size/M

#2574 feat: allow to template main
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: enhancement, size/M

#2681 docs: fix version in docs
  scripts/vercel/build.sh
  www/docs/install.md
Labels: docs, size/S

#2682 docs: Add Fleet to USERS.md
  USERS.md
Labels: size/XS

#2680 fix: ensure certificate is always within dist
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
Labels: bug, size/M

#2677 feat: template on extra_files
  internal/extrafiles/extra_files.go
  internal/extrafiles/extra_files_test.go
  internal/extrafiles/testdata/sub3/file1.golden
  internal/pipe/blob/upload.go
  internal/pipe/checksums/checksums.go
  internal/pipe/release/release.go
  www/docs/customization/blob.md
  www/docs/customization/checksum.md
  www/docs/customization/release.md
Labels: size/M

#2689 chore: update strings when using a custom distribution directory
  internal/pipe/dist/dist.go
Labels: size/XS

#2692 fix: checksum extra_files when no builds
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
Labels: bug, size/S

#2693 fix: jsonschema field names
  .golangci.yml
  internal/pipe/krew/krew.go
  internal/pipe/snapcraft/snapcraft.go
  pkg/config/config.go
Labels: bug, size/S

#2694 chore: avoid task error on fmt
  Taskfile.yml
Labels: size/XS

#2684 feat: add hooks to universal binaries
  internal/middleware/skip/skip.go
  internal/pipe/announce/announce.go
  internal/pipe/build/build.go
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/shell/shell.go
  internal/shell/shell_test.go
  pkg/config/config.go
Labels: enhancement, size/L

#2678 feat: remap extra_files
  internal/extrafiles/extra_files.go
  internal/extrafiles/extra_files_test.go
  pkg/config/config.go
  www/docs/customization/blob.md
  www/docs/customization/checksum.md
  www/docs/customization/release.md
Labels: size/L

#2670 feat: CHANGELOG categories
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  pkg/config/config.go
  www/docs/customization/changelog.md
Labels: size/L

#2695 feat: make each changelog commit a list item
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: enhancement, size/M

#2683 feat: allow to use .PreviousTag on templates
  .goreleaser.yml
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: enhancement, size/L

#2696 docs: add docs to universal binaries hooks
  www/docs/customization/universalbinaries.md
Labels: docs, size/S

#2596 Adding top level environment variables within env section in docker section
  internal/pipe/docker/api.go
  internal/pipe/docker/api_buildpack.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: size/M

#2698 chore: Rename yml to yaml
  .golangci.yaml
  .goreleaser.yaml
Labels: size/XS

#2699 docs: add another step to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#2700 feat: add git summary support (aka git describe --dirty --tags --always)
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/tmpl/tmpl.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: size/S

#2702 feat: allow to customize release notes update behavior
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/client/release_notes.go
  internal/client/release_notes_test.go
  pkg/config/config.go
  www/docs/customization/release.md
  www/docs/static/schema.json
Labels: enhancement, size/L

#2706 refactor: remove unused git.RunEnv
  internal/git/git.go
  internal/pipe/git/git_test.go
  internal/testlib/git.go
Labels: enhancement, size/M

#2705 fix: git url with port
  internal/git/config.go
  internal/git/config_test.go
Labels: bug, size/S

#2709 feat: no main error page
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  www/docs/errors/no-main.md
  www/mkdocs.yml
Labels: size/M
