Repository goreleaser/goreleaser, pull requests merged in 2021-02, with the labels that each got.

#2042 docs: fix minor typo in intro.md
  www/docs/intro.md
Labels: size/XS

#2051 fix: update snapcraft command from 'push' to 'upload'
  internal/pipe/snapcraft/snapcraft.go
Labels: automerge, size/XS

#2054 minor grammar tweak
  www/docs/customization/templates.md
Labels: size/XS

#2056 docs: clarify cgo a bit
  www/docs/cookbooks/blog-posts.md
  www/docs/limitations/cgo.md
  www/mkdocs.yml
Labels: automerge, docs, size/S

#2057 fix: makes username and password optional for http uploads
  internal/http/http.go
  internal/http/http_test.go
  www/docs/customization/upload.md
Labels: automerge, bug, size/M

#1956 feat: support go 1.16 and apple silicon
  .github/workflows/build.yml
  CONTRIBUTING.md
  Dockerfile
  cmd/util_test.go
  go.mod
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/test.rb.golden
  www/docs/ci/actions.md
  www/docs/ci/circle.md
  www/docs/ci/codefresh.md
Labels: automerge, enhancement, size/M

#2062 fix: brew: check cpu
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/custom_block.rb.golden
  internal/pipe/brew/testdata/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/custom_require.rb.golden
  internal/pipe/brew/testdata/default.rb.golden
  internal/pipe/brew/testdata/default_gitlab.rb.golden
  internal/pipe/brew/testdata/foo_is_bar.rb.golden
  internal/pipe/brew/testdata/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/test.rb.golden
Labels: automerge, enhancement, size/S

#2069 fix: try not to break if run on go1.15
  internal/builders/golang/build.go
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
Labels: automerge, enhancement, size/M

#2078 docs: added ref to a blog post explaining how to publish deb/rpm packages to apt/yum repos
  www/docs/cookbooks/blog-posts.md
Labels: size/XS

#2082 chore(ci): stop using gocenter.io
  .goreleaser.yml
Labels: automerge, enhancement, size/XS
