Repository goreleaser/goreleaser, pull requests merged in 2021-03, with the labels that each got.

#2083 test: use main as git branch for tests
  internal/testlib/git.go
Labels: automerge, bug, size/XS

#2084 fix: log semver errors when snapshot
  internal/deprecate/deprecate.go
  internal/deprecate/deprecate_test.go
  internal/deprecate/testdata/output.txt.golden
  internal/deprecate/testdata/output_custom.txt.golden
  internal/pipe/semver/semver.go
  internal/pipe/semver/semver_test.go
  www/docs/deprecations.md
Labels: automerge, bug, enhancement, size/L

#2085 feat: update fileglob and nfpm
  go.mod
  go.sum
  internal/extrafiles/extra_files_test.go
  internal/pipe/release/release_test.go
Labels: automerge, enhancement, size/M

#2090 fix(ci): go mod tidy
  .github/workflows/build.yml
  .goreleaser.yml
  Makefile
  cmd/testdata/good.yml
  internal/static/config.go
  www/docs/customization/build.md
  www/docs/customization/env.md
  www/docs/customization/hooks.md
Labels: automerge, bug, size/S

#2092 feat: init: add dist to gitignore
  cmd/init.go
  cmd/init_test.go
Labels: automerge, enhancement, size/M

#2099 fix: nfpm config validation
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: automerge, bug, size/S

#2110 docs: Add info on skip_upload to scoop
  www/docs/customization/scoop.md
Labels: automerge, docs, size/XS

#2112 feat: support snapcraft layout
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  pkg/config/config.go
  www/docs/customization/snapcraft.md
Labels: size/M

#2116 Add trimprefix function to template package
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: size/S

#2117 fix(ci): snap tests
  .github/workflows/build.yml
Labels: automerge, bug, size/XS

#2123 docs: fix typo in templates.md
  www/docs/customization/templates.md
Labels: size/XS

#2122 docs: expand GitLab CI examples
  www/docs/ci/gitlab.md
Labels: size/M

#2119 fix: docker manifest on draft release
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: automerge, bug, size/S

#2126 fix: properly translate mips arch
  internal/linux/arch.go
  internal/linux/arch_test.go
Labels: automerge, bug, size/M

#2124 fix: default gomips
  internal/builders/golang/build.go
  internal/pipe/build/build_test.go
  www/docs/customization/build.md
Labels: automerge, bug, size/XS

#2128 feat: allow to use ModulePath on templates
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_test.go
  internal/pipeline/pipeline.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: automerge, enhancement, size/L

#2130 fix: wrong docker manifest on latest
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/docker/testdata/Dockerfile.dummy
Labels: bug, size/L

#2138 docs: added documentation for post_install step in homebrew section
  www/docs/customization/homebrew.md
Labels: size/S

#2135 feat: fail on shallow clone
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
Labels: size/M

#2144 fix: build windows/arm
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/builders/golang/targets_test.go
Labels: automerge, bug, size/XS

#2145 fix: update go-gitlab to fix upload file issue
  go.mod
  go.sum
Labels: bug, size/XS

#2129 feat: initial proxy build support
  .goreleaser.yml
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_test.go
  internal/pipeline/pipeline.go
  main.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/cookbooks/build-go-modules.md
  www/docs/customization/gomod.md
  www/mkdocs.yml
Labels: enhancement, size/XL
