Repository goreleaser/goreleaser, pull requests merged in 2022-11, with the labels that each got.

#3520 fix: do not run changelog on goreleaser build
  internal/pipeline/pipeline.go
Labels: bug, size/XS

#3523 feat: update to go 1.19.3
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/fig.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  www/docs/ci/actions.md
Labels: enhancement, dependencies, size/S

#3521 fix: allow to template scoop/brew/krew repo ref
  internal/client/config.go
  internal/client/config_test.go
  internal/pipe/brew/brew.go
  internal/pipe/krew/krew.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/scoop.md
Labels: bug, size/L

#3470 feat: implement nfpm archlinux packages
  .goreleaser.yaml
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#3529 docs: add Syft to contributing docs
  www/docs/contributing.md
Labels: size/XS

#3528 docs: update docs to mention gitlab protected vars
  www/docs/ci/gitlab.md
  www/docs/scm/gitlab.md
Labels: size/S

#3531 Update .goreleaser.yaml
  .goreleaser.yaml
Labels: size/XS

#3527 fix(changelog): group regexps
  .goreleaser.yaml
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  www/docs/customization/changelog.md
Labels: size/M

#3542 chore(docs): Fix wording
  www/docs/errors/dirty.md
Labels: size/XS

#3511 feat: build of shared/static libraries
  internal/artifact/artifact.go
  internal/builders/golang/build.go
  internal/pipe/archive/archive.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: enhancement, size/L

#3509 feat: chocolatey support
  internal/artifact/artifact.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/chocolatey/chocolatey_test.go
  internal/pipe/chocolatey/nuspec.go
  internal/pipe/chocolatey/nuspec_test.go
  internal/pipe/chocolatey/template.go
  internal/pipe/chocolatey/testdata/TestNuspecBytes.nuspec.golden
  internal/pipe/chocolatey/testdata/Test_buildNuspec.nuspec.golden
  internal/pipe/chocolatey/testdata/Test_buildTemplate.script.ps1.golden
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/chocolatey.md
  www/docs/static/schema.json
  www/mkdocs.yml
Labels: size/XXL

#3546 fix: improve artifactory error handling
  internal/pipe/artifactory/artifactory.go
  internal/pipe/artifactory/artifactory_test.go
Labels: bug, size/S

#3540 feat: add digest to artifacts info of published docker images
  internal/artifact/artifact.go
  internal/pipe/docker/api.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipeline/pipeline.go
Labels: size/M

#3549 Add Mercure to users
  USERS.md
Labels: size/XS

#3552 fix: set dockers.goarm to 6 by default
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  www/docs/customization/docker.md
Labels: bug, size/XS

#3548 feat: output checksums to artifacts info
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/docker/docker.go
Labels: size/M

#3554 fix: log when no artifacts are found for docker
  internal/pipe/docker/docker.go
Labels: enhancement, size/XS

#3553 docs: improve schema
  pkg/config/config.go
  www/docs/static/schema.json
Labels: bug, docs, size/S

#3556 feat: use digest to sign docker images/manifests
  internal/artifact/artifact.go
  internal/pipe/docker/docker.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_docker.go
  internal/pipe/sign/sign_docker_test.go
  www/docs/customization/docker_sign.md
Labels: enhancement, size/M

#3555 feat: use digest on manifests
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
Labels: enhancement, size/M

#3567 feat: add mastodon
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/mastodon/mastodon.go
  internal/pipe/mastodon/mastodon_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/mastodon.md
  www/mkdocs.yml
Labels: enhancement, size/L

#3568 fix: move mastodon server to yaml
  internal/pipe/mastodon/mastodon.go
  internal/pipe/mastodon/mastodon_test.go
  pkg/config/config.go
  www/docs/customization/announce/mastodon.md
Labels: enhancement, size/M

#3569 chore: announce goreleaser releases to mastodon
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: enhancement, size/XS

#3547 fix: improve github release code
  internal/client/github.go
Labels: bug, size/M

#3570 fix(ci): codeql use go 1.19
  .github/workflows/codeql.yml
Labels: bug, size/XS

#3576 chore: verify website for mastodon
  www/docs/overrides/home.html
Labels: size/XS

#3586 chore: fix typo in pro docs
  www/docs/pro.md
Labels: size/XS

#3590 feat: title template function
  go.mod
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#3581 feat: add windows to default builds
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build_test.go
  www/docs/customization/build.md
Labels: enhancement, size/S

#3591 fix: validate env templates
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/build.md
Labels: bug, size/S

#3593 feat(brew): allow to template brew.install
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
Labels: enhancement, size/L

#3589 feat: deprecate replacements
  .goreleaser.yaml
  cmd/init.go
  cmd/testdata/good.yml
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/exec/exec.go
  internal/http/http.go
  internal/pipe/archive/archive.go
  internal/pipe/aur/aur.go
  internal/pipe/brew/brew.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/krew/krew.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/sbom/sbom.go
  internal/pipe/scoop/scoop.go
  internal/pipe/snapcraft/snapcraft.go
  internal/static/config.go
  internal/static/config.yaml
  internal/static/config_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
  www/docs/customization/nfpm.md
  www/docs/customization/snapcraft.md
  www/docs/deprecations.md
Labels: enhancement, size/L

#3592 feat(build): allow to template env
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  www/docs/customization/build.md
Labels: enhancement, size/L

#3602 fix: missing digests on manifests
  internal/pipe/docker/api.go
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
Labels: bug, size/M

#3607 fix: warn if list has multiple files with same name
  internal/artifact/artifact.go
Labels: enhancement, size/S

#3608 fix: log request-id on upload error and release create/update
  internal/client/github.go
Labels: bug, size/S

#3603 fix: improve schema for signs
  pkg/config/config.go
  www/docs/static/schema.json
Labels: enhancement, size/XS

#3585 fix: retain symlinks added to zip archives
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
Labels: size/S
