Repository goreleaser/goreleaser, pull requests merged in 2022-06, with the labels that each got.

#3130 feat: update go-github from v44 to v45
  go.mod
  go.sum
  internal/client/github.go
Labels: size/XS

#3152 [docs] Miscellaneous usage improvements
  www/docs/ci/actions.md
  www/docs/cookbooks/release-a-library.md
  www/docs/customization/env.md
  www/docs/customization/monorepo.md
  www/docs/customization/nightlies.md
  www/docs/customization/verifiable_builds.md
  www/docs/quick-start.md
  www/docs/scm/github.md
  www/docs/scm/gitlab.md
  www/mkdocs.yml
Labels: size/S

#3138 feat: update x/sync
  go.mod
  go.sum
  internal/semerrgroup/sem.go
  internal/semerrgroup/sem_test.go
Labels: enhancement, size/L

#3131 chore(ci): tparse
  .github/workflows/build.yml
  .gitignore
Labels: size/S

#3158 fix: wrap_in_directory type
  pkg/config/config.go
  www/docs/static/schema.json
Labels: bug, size/XS

#3157 feat: removed deprecated windows arm handling on go 1.16
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
  www/docs/deprecations.md
Labels: enhancement, size/M

#3159 feat: update jsonschema library
  cmd/schema.go
  cmd/schema_test.go
  go.mod
  go.sum
  pkg/config/config.go
  www/docs/static/schema.json
Labels: size/M

#3163 feat: remove empty_folders for good
  internal/pipe/nfpm/nfpm.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: enhancement, size/S

#3167 docs: adds Koordinator to USERS.md
  USERS.md
Labels: size/XS

#3177 fix(ci): gitleaks license
  .github/gitleaks.toml
  .github/workflows/gitleaks.yml
Labels: bug, security, size/S

#3173 feat: log duration of slow pipes
  internal/middleware/logging/logging.go
Labels: enhancement, size/S

#3178 refactory: make easier to manage merges with pro
  cmd/build.go
  cmd/release.go
  cmd/root.go
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/artifact/testdata/TestMarshalJSON.json.golden
  internal/pipe/metadata/metadata.go
  internal/pipe/metadata/testdata/TestRun/artifacts.json.golden
  pkg/context/context.go
Labels: enhancement, size/L

#3176 feat: add --skip-docker
  cmd/release.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  pkg/context/context.go
Labels: enhancement, size/S

#3182 feat: added --skip-before flag
  cmd/build.go
  cmd/release.go
  internal/pipe/before/before.go
  internal/pipe/before/before_test.go
  internal/pipe/docker/docker_test.go
  pkg/context/context.go
Labels: enhancement, size/M

#3184 fix: improve docker publish skipping
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: enhancement, size/M

#3190 docs: no-main error if running outside project root
  www/docs/errors/no-main.md
Labels: size/XS

#3189 Typo in archive.md
  www/docs/customization/archive.md
Labels: docs, size/XS

#3191 refactor: improve handling of extra fields in artifacts
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/aur/aur.go
  internal/pipe/brew/brew.go
  internal/pipe/docker/docker.go
  internal/pipe/gofish/gofish.go
  internal/pipe/krew/krew.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/tmpl/tmpl.go
Labels: enhancement, size/L

#3185 fix: blob upload eating errors
  internal/pipe/blob/upload.go
Labels: bug, size/S

#3193 chore(ci): improve tparse output
  .github/workflows/build.yml
  scripts/test.sh
Labels: enhancement, size/S

#3199 fix: use default builder with buildx
  internal/pipe/docker/api_docker.go
  internal/pipe/docker/docker_test.go
  www/docs/customization/docker.md
Labels: bug, size/S

#3200 Fix mistaken mention of homebrew in AUR section
  www/docs/customization/aur.md
Labels: size/XS

#3198 fix: run defaults pipe before before pipe
  internal/pipeline/pipeline.go
Labels: bug, size/XS

#3204 docs: fix typos
  www/docs/customization/nfpm.md
  www/docs/customization/release.md
Labels: docs, size/XS

#3206 docs: update wrong permission key
  www/docs/ci/actions.md
Labels: size/XS

#3205 feat: allow to template release.repo
  internal/pipe/release/release.go
  internal/pipe/release/scm.go
  internal/pipe/release/scm_test.go
Labels: enhancement, size/L

#3203 feat: changelog group improvements
  .goreleaser.yaml
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: enhancement, size/M

#3201 feat: allow to override env for a target
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: enhancement, size/M

#3207 fix(ci): less logs in the test output
  internal/testlib/log.go
Labels: enhancement, size/S

#3212 feat: allow multiple ids to be passed to build
  cmd/build.go
  cmd/build_test.go
Labels: enhancement, size/M

#3213 feat: allow parallelism by build target
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
Labels: enhancement, size/S

#3218 docs: use `--output-signature` with cosign sign
  www/docs/customization/sign.md
Labels: docs, size/XS
