Repository goreleaser/goreleaser, pull requests merged in 2022-12, with the labels that each got.

#3611 feat: custom tag.sort
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  pkg/config/config.go
  www/docs/customization/build.md
  www/docs/customization/git.md
  www/mkdocs.yml
Labels: enhancement, size/M

#3623 feat: update lock task parameter due to braking change
  .github/workflows/lock.yml
Labels: size/XS

#3628 doc: fix `skip_push` parameter to `skip_build`
  www/docs/customization/docker.md
Labels: size/XS

#3640 docs: update github-action documentation
  www/docs/ci/actions.md
  www/docs/cookbooks/override-image-name.md
  www/docs/errors/resource-not-accessible-by-integration.md
Labels: docs, size/M

#3630 feat: allow to template archives.files.info
  internal/archivefiles/archivefiles.go
  internal/archivefiles/archivefiles_test.go
  pkg/archive/gzip/gzip.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/tar/tar.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
  pkg/config/config.go
  pkg/config/config_archive_files_test.go
  www/docs/customization/archive.md
Labels: enhancement, size/L

#3644 feat(deps): build with go 1.19.4
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/fig.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  www/docs/ci/actions.md
Labels: enhancement, dependencies, size/S

#3642 feat: improving minio and docker tests
  go.mod
  go.sum
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/docker/docker_test.go
  internal/testlib/docker.go
Labels: enhancement, size/L

#3651 docs: add Optimus Mine to GoReleaser users
  USERS.md
Labels: size/XS

#3652 docs: fix README badge
  README.md
Labels: size/XS

#3660 fix: multiple files with same name warning
  internal/artifact/artifact.go
Labels: bug, size/XS

#3656 feat: better archives relative paths
  .goreleaser.yaml
  internal/archivefiles/archivefiles.go
  internal/archivefiles/archivefiles_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/sourcearchive/source.go
  pkg/config/config.go
  www/docs/customization/archive.md
  www/docs/customization/source.md
  www/docs/deprecations.md
Labels: bug, enhancement, size/L

#3665 fix: log which token will be used
  internal/pipe/env/env.go
Labels: enhancement, size/XS

#3666 fix: only fail announcing phase in the end
  go.mod
  go.sum
  internal/middleware/errhandler/error.go
  internal/middleware/errhandler/error_test.go
  internal/pipe/announce/announce.go
  internal/pipe/announce/announce_test.go
  internal/pipe/discord/discord.go
  internal/pipe/discord/discord_test.go
  internal/pipe/linkedin/linkedin.go
  internal/pipe/linkedin/linkedin_test.go
  internal/pipe/mastodon/mastodon.go
  internal/pipe/mastodon/mastodon_test.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/reddit/reddit.go
  internal/pipe/reddit/reddit_test.go
  internal/pipe/slack/slack.go
  internal/pipe/slack/slack_test.go
  internal/pipe/smtp/smtp.go
  internal/pipe/teams/teams.go
  internal/pipe/teams/teams_test.go
  internal/pipe/telegram/telegram.go
  internal/pipe/telegram/telegram_test.go
  internal/pipe/twitter/twitter.go
  internal/pipe/twitter/twitter_test.go
  internal/pipe/webhook/webhook.go
  internal/pipe/webhook/webhook_test.go
Labels: bug, size/L

#3670 fix: Check that the variable resp is not nil
  internal/client/github.go
Labels: bug, size/XS

#3668 fix: native changeloger without previous tag
  cmd/release.go
  internal/client/mock.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  pkg/context/context.go
Labels: bug, size/L

#3673 fix: improve changelog a bit
  internal/pipe/changelog/changelog.go
Labels: enhancement

#3674 docs: improve build
  .gitattributes
  .github/workflows/generate.yml
  .github/workflows/release.yml
  .gitignore
  Taskfile.yml
  scripts/get-releases.sh
  scripts/pages/build.sh
  www/docs/static/latest
  www/docs/static/latest-pro
  www/docs/static/releases-pro.json
  www/docs/static/releases.json
  www/docs/static/run
Labels: enhancement, docs, size/XXL

#3672 docs: remove vercel
  Taskfile.yml
  scripts/vercel/build.sh
  scripts/vercel/install.sh
  vercel.json
Labels: enhancement, docs, size/S

#3677 fix: do not put binaries in /usr/local/bin
  Dockerfile
  www/docs/customization/nfpm.md
Labels: bug, docs
