Repository goreleaser/goreleaser, pull requests merged in 2022-08, with the labels that each got.

#3277 feat: support goarch=loong64
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
Labels: enhancement, size/XS

#3279 Note that AUR publish is skipped if aur git url is empty
  www/docs/customization/aur.md
Labels: size/XS

#3278 feat(ci): compile with go 1.19
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .golangci.yaml
  CONTRIBUTING.md
  cmd/util_test.go
  go.mod
  internal/artifact/artifact_test.go
  internal/builders/golang/build_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/snapshot/snapshot_test.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/upload/upload_test.go
  internal/testlib/tmpl.go
  www/docs/ci/actions.md
  www/docs/ci/azurepipelines.md
  www/docs/ci/circle.md
  www/docs/ci/codefresh.md
Labels: enhancement, size/L

#3282 feat: allow to skip scm release uploads
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  pkg/config/config.go
  www/docs/customization/release.md
  www/docs/static/schema.json
Labels: enhancement, size/S

#3274 fix: brew style
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
  internal/pipe/brew/testdata/TestRunPipeBinaryRelease.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
  internal/pipe/brew/testdata/TestRunPipeUniversalBinary.rb.golden
  internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden
Labels: bug, size/L

#3293 Add split function
  internal/tmpl/tmpl.go
  www/docs/customization/templates.md
Labels: size/XS

#3295 fix: do not push snaps concurrently
  internal/pipe/snapcraft/snapcraft.go
Labels: bug, size/S

#3296 feat: login into gitlab registry
  scripts/entrypoint.sh
Labels: enhancement, size/XS

#3302 Support mTLS with client certificate when configured.
  internal/http/http.go
  internal/http/http_test.go
  internal/http/testcert.pem
  internal/http/testkey.pem
  pkg/config/config.go
  www/README.md
  www/docs/customization/artifactory.md
  www/docs/customization/upload.md
  www/docs/static/schema.json
Labels: size/L

#3261 feat: strip_parent_binary_folder
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
Labels: enhancement, size/M

#2993 feat: gitlab option to use_job_token
  internal/client/gitlab.go
  pkg/config/config.go
  www/docs/scm/gitlab.md
Labels: enhancement, size/S

#3311 feat(deps): update nfpm to v2.18.0
  go.mod
  go.sum
Labels: size/XS

#3312 feat: remove gofish
  internal/artifact/artifact.go
  internal/golden/golden.go
  internal/pipe/aur/aur_test.go
  internal/pipe/gofish/doc.go
  internal/pipe/gofish/food_template.go
  internal/pipe/gofish/gofish.go
  internal/pipe/gofish/gofish_test.go
  internal/pipe/gofish/testdata/TestFullFood.lua.golden
  internal/pipe/gofish/testdata/TestFullFoodLinuxOnly.lua.golden
  internal/pipe/gofish/testdata/TestFullFoodWindowsOnly.lua.golden
  internal/pipe/gofish/testdata/TestFullPipe/default.lua.golden
  internal/pipe/gofish/testdata/TestFullPipe/default_gitlab.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeBinaryRelease.rb.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeNameTemplate.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeUniversalBinary.lua.golden
  internal/pipe/gofish/testdata/TestRunPipeUniversalBinaryNotReplacing.lua.golden
  internal/pipe/krew/krew_test.go
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/ci/azurepipelines.md
  www/docs/deprecations.md
  www/docs/static/schema.json
Labels: enhancement, size/XXL

#3310 fix: eventual race condition in artifacts
  internal/artifact/artifact.go
  internal/pipe/aur/aur_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/krew/krew_test.go
Labels: bug, size/M

#3309 feat: nfpm changelog support
  .goreleaser.yaml
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nfpm/testdata/changelog.yaml
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#3318 feat: replace existing draft releases on github
  internal/client/github.go
  pkg/config/config.go
  www/docs/customization/release.md
Labels: enhancement, size/M

#3319 feat: allow to specify version of brew deps
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: enhancement, size/M

#3326 feat(deps): update github to v46
  go.mod
  go.sum
  internal/client/github.go
Labels: enhancement, dependencies, size/XS

#3331 fix: grype ignore testdata
  .grype.yaml
Labels: size/XS

#3332 fix: run gitleaks and grype on prs
  .github/workflows/gitleaks.yml
  .github/workflows/grype.yml
  .gitleaks.toml
Labels: size/S

#3330 feat: delay github tag creation
  internal/client/github.go
Labels: enhancement, size/S

#3329 feat: add fig autocomplete support
  cmd/root.go
  go.mod
  go.sum
Labels: size/XS

#3333 feat: termux.deb
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#3102 feat: add extra files to source archives
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  pkg/config/config.go
  www/docs/customization/source.md
Labels: enhancement, size/L

#3343 fix: source archive add subfolders
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  pkg/config/config.go
  www/docs/customization/source.md
  www/docs/static/schema.json
Labels: bug, size/L

#3347 chore: remove duplicate word in comments
  internal/semerrgroup/sem.go
Labels: size/XS

#3349 fix: guard changelog commit abbrev behind config
  internal/client/github.go
  internal/client/github_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  pkg/config/config.go
  www/docs/customization/changelog.md
Labels: bug, size/L

#3352 fix: insert missing word
  www/docs/intro.md
Labels: size/XS
