Repository goreleaser/goreleaser, pull requests merged in 2022-04, with the labels that each got.

#3012 fix: sign before brew et al
  internal/pipeline/pipeline.go
Labels: bug, size/XS

#2999 feat: deprecate gofish
  .goreleaser.yaml
  internal/deprecate/deprecate.go
  internal/pipe/gofish/gofish.go
  pkg/config/config.go
  www/docs/customization/gofish.md
  www/docs/deprecations.md
  www/docs/install.md
  www/mkdocs.yml
Labels: enhancement, size/L

#3003 feat: tmpl snap fields
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
Labels: enhancement, size/M

#3028 fix: use universal binary id
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
Labels: bug, size/S

#3031 refactor: improve scoop tests
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: enhancement, size/L

#3032 refactor: use context on git exec calls
  cmd/release.go
  internal/git/config.go
  internal/git/config_test.go
  internal/git/git.go
  internal/git/git_test.go
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/defaults/defaults_test.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/pipe/milestone/milestone.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/sourcearchive/source.go
  internal/testlib/git.go
Labels: enhancement, size/XL

#3036 Set permissions for GitHub actions
  .github/workflows/docs.yml
  .github/workflows/generate.yml
Labels: bug, size/XS

#3038 Updated docker file - Pined by SHA
  Dockerfile
Labels: bug, size/XS

#3039 fix: nfpm lintian concurrency issue
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: bug, size/L

#3041 fix(ci): misspell action
  .github/workflows/misspell.yml
  .golangci.yaml
Labels: bug, dependencies, size/S

#3040 fix(ci): dont use krew fork
  .github/workflows/build.yml
Labels: dependencies, size/XS

#3046 Change test docker registry port numbers
  internal/pipe/docker/docker_test.go
Labels: size/S

#3054 Fixing typos
  SECURITY.md
  cmd/build.go
  www/docs/ci/codefresh.md
  www/docs/ci/gitlab.md
  www/docs/ci/semaphore.md
  www/docs/cmd/goreleaser_build.md
  www/docs/cookbooks/blog-posts.md
  www/docs/customization/docker_sign.md
  www/docs/customization/fury.md
  www/docs/customization/includes.md
  www/docs/customization/snapshots.md
Labels: size/M

#3052 fix: archive ids
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
Labels: bug, size/M

#3064 feat: add builds.no_main_check and builds.command
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: enhancement, size/L

#3063 fix: prevent folder collisions in builds and universal binaries
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  www/docs/customization/build.md
Labels: bug, size/S

#3062 feat: first class build targets
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  www/docs/customization/build.md
Labels: enhancement, size/L

#3068 Update scoop.md
  www/docs/customization/scoop.md
Labels: size/XS

#3075 feat: new install anf run script
  www/docs/ci/circle.md
  www/docs/ci/drone.md
  www/docs/ci/jenkins.md
  www/docs/ci/semaphore.md
  www/docs/ci/travis.md
  www/docs/install.md
  www/docs/static/run
Labels: bug, enhancement, docs, size/M

#3077 feat: adds openssh-client to docker images
  Dockerfile
Labels: enhancement, size/XS
