Repository goreleaser/goreleaser, pull requests merged in 2022-02, with the labels that each got.

#2859 feat: expose runtime goos and goarch on templates and metadata
  internal/pipe/metadata/metadata.go
  internal/pipe/metadata/metadata_test.go
  internal/pipe/metadata/testdata/TestRun/metadata.json.golden
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  pkg/context/context_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/M

#2865 chore: bump mango and adapt to changed API
  cmd/man.go
  go.mod
  go.sum
Labels: size/XS

#2860 feat: allow to override build flags by goos/goarch/etc
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/build.md
Labels: enhancement, size/L

#2841 fix: improve deprecate logs
  internal/deprecate/deprecate.go
  internal/deprecate/testdata/TestNotice.txt.golden
  internal/deprecate/testdata/TestNoticeCustom.txt.golden
Labels: size/S

#2872 feat: template nfpms.maintainer
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: enhancement, size/S

#2880 fix: aur error messages
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/testdata/TestFullAur.golden
  internal/pipe/aur/testdata/TestRunPipe.pkgbuild.golden
  internal/pipe/aur/testdata/TestRunPipe.srcinfo.golden
  internal/pipe/aur/tmpl.go
Labels: bug, size/M

#2882 feat: upgrade nfpm to v2.12.0
  go.mod
  go.sum
Labels: size/XS

#2883 feat: make pkg pass lintian validations
  .goreleaser.yaml
  .lintian-overrides
  scripts/manpages.sh
Labels: enhancement, size/M

#2701 feat: allow a --output flag on goreleaser build
  cmd/build.go
  cmd/build_test.go
Labels: enhancement, size/L

#2885 feat: warn if loaded changelog is whitespace-only
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/changelog/testdata/changes-empty.md
  internal/pipe/changelog/testdata/changes-templated-empty.md
Labels: enhancement, size/M

#2888 fix: make --release-notes flags more deterministic
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/changelog/testdata/changes-really-empty.md
Labels: bug, size/S

#2891 feat: allow to use .Path and .Name on universal binary post hooks
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  www/docs/customization/universalbinaries.md
Labels: enhancement, size/M

#2889 docs: use the orgs code of conduct
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  www/docs/links.md
Labels: size/M

#2893 docs: adds Conduit to USERS.md
  USERS.md
Labels: size/XS

#2892 feat: lintian overrides
  .goreleaser.yaml
  .lintian-overrides
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#2905 feat: add gpg to Docker image for signing of artifacts
  Dockerfile
Labels: size/XS

#2906 feat: update docker image's cosign
  Dockerfile
Labels: enhancement, size/XS

#2910 feat: change default nfpm bindir
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/S

#2916 fix: do not copy binary by default
  cmd/build.go
  cmd/build_test.go
Labels: bug, size/S

#2921 fix: Homebrew README example formula
  www/docs/customization/homebrew.md
Labels: size/S

#2929 docs: add community section in README
  README.md
Labels: enhancement, docs, size/S

#2931 Update drone.md
  www/docs/ci/drone.md
Labels: size/XS

#2932 docs: Add a new cookbook that covers using the jfrog-cli as an alternative to the artifactory publisher to publish to artifactory.
  www/docs/cookbooks/using-jfrog-cli-to-publish-to-artifactory.md
  www/mkdocs.yml
Labels: docs, size/S

#2924 feat: add filter and reverseFilter template functions
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/M

#2923 feat: annotated tag body
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#2930 fix: trim spaces from aur private key
  internal/pipe/aur/aur.go
Labels: bug, size/XS

#2935 fiX: improve aur key handling
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
Labels: bug, size/S

#2839 fix: dedupliate cataloging binary artifacts
  go.mod
  go.sum
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
Labels: size/XL

#2938 fix: build breaking on windows 386
  go.mod
  go.sum
  internal/artifact/artifact.go
Labels: bug, size/XS

#2939 improvement(pipe/brew): install amd64 binaries when no arm64 binaries present
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_tap_templates.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
Labels: size/L

#2940 feat(deps): upgrade nfpm to v2.14.0
  go.mod
  go.sum
Labels: dependencies, size/XS

#2941 feat: faster archiving with pgzip
  go.mod
  pkg/archive/gzip/gzip.go
Labels: enhancement, size/XS
