Repository goreleaser/goreleaser, pull requests merged in 2022-09, with the labels that each got.

#3362 chore(ci): govulncheck
  .github/workflows/build.yml
Labels: enhancement, size/S

#3365 fix: templates in release URLs
  internal/pipe/release/scm.go
  internal/pipe/release/scm_test.go
Labels: bug, size/M

#3364 fix: ruleguard and semgrep scans and fixes
  .github/workflows/build.yml
  cmd/config.go
  internal/builders/golang/build_test.go
  internal/exec/exec_mock.go
  internal/gio/safe_test.go
  internal/git/config.go
  internal/logext/writer_test.go
  internal/pipe/archive/archive.go
  internal/pipe/aur/aur.go
  internal/pipe/blob/upload.go
  internal/pipe/env/env.go
  internal/pipe/linkedin/client_test.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/release/release.go
  internal/pipe/webhook/webhook_test.go
  internal/testlib/git.go
  pkg/context/context.go
Labels: size/M

#3367 docs: version recent changes
  www/docs/customization/announce/webhook.md
  www/docs/customization/archive.md
  www/docs/customization/artifactory.md
  www/docs/customization/aur.md
  www/docs/customization/build.md
  www/docs/customization/changelog.md
  www/docs/customization/docker_sign.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/nfpm.md
  www/docs/customization/release.md
  www/docs/customization/sbom.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/docs/customization/source.md
  www/docs/customization/templates.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/upload.md
  www/docs/customization/verifiable_builds.md
  www/docs/scm/gitlab.md
Labels: bug, docs, size/L

#3374 fix: print release url after publishing it
  internal/pipe/release/release.go
Labels: enhancement, size/XS

#3375 fix: fish completions path on nfpm
  .goreleaser.yaml
Labels: bug, size/XS

#3376 fix: yaml-lang-server modelines in init config
  .goreleaser.yaml
  internal/static/config.go
  www/docs/customization/index.md
Labels: bug, docs, size/S

#3378 fix: add COSIGN_EXPERIMENTAL=1 for verify-blob
  www/docs/install.md
Labels: size/XS

#3379 fix: update cosign in docker img to 1.12.0
  Dockerfile
Labels: bug, size/XS

#3381 fix: build --single-target when using specific targets
  cmd/build.go
  cmd/build_test.go
Labels: bug, size/M

#3385 fix: binary archive when multiple builds
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  www/docs/errors/multiple-binaries-archive.md
  www/mkdocs.yml
Labels: bug, size/M

#3384 docs: improve wording/formatting in several places
  internal/pipe/git/errors.go
  www/docs/ci/actions.md
  www/docs/ci/azurepipelines.md
  www/docs/customization/artifactory.md
  www/docs/customization/aur.md
  www/docs/customization/blob.md
  www/docs/customization/build.md
  www/docs/customization/docker_manifest.md
  www/docs/customization/docker_sign.md
  www/docs/customization/env.md
  www/docs/customization/fury.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/includes.md
  www/docs/customization/index.md
  www/docs/customization/krew.md
  www/docs/customization/milestone.md
  www/docs/customization/monorepo.md
  www/docs/customization/nfpm.md
  www/docs/customization/nightlies.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/sbom.md
  www/docs/customization/scoop.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/templates.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/upload.md
  www/docs/customization/verifiable_builds.md
  www/docs/errors/dirty.md
Labels: docs, size/XL

#3386 chore: splitting workflows
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: size/L

#3389 chore: avoid running actions when not needed/possible
  .github/workflows/build.yml
  .github/workflows/gitleaks.yml
  .github/workflows/lock.yml
  .github/workflows/milestone.yml
  .github/workflows/release.yml
Labels: size/S

#3396 docs: update nfpm docs
  internal/pipe/nfpm/nfpm.go
  www/docs/customization/nfpm.md
Labels: bug, docs, size/M

#3400 refactory: making merges with pro easier
  cmd/release.go
  cmd/release_test.go
Labels: size/S

#3403 fix(deps): update cosign to v1.12.1
  Dockerfile
Labels: enhancement, dependencies, size/XS

#3409 fix: client key and cert should not be required
  pkg/config/config.go
  www/docs/static/schema.json
Labels: bug, size/XS

#3415 bugfix: handle mixing of job and normal tokens
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: bug, size/M

#3421 docs: add trendyol.com to users
  USERS.md
Labels: size/XS

#3419 docs: adds Meroxa to USERS.md
  USERS.md
Labels: size/XS

#3422 Adding KSOC to the list of users.
  USERS.md
Labels: size/XS

#3425 docs: add Goldenhand Software to users
  USERS.md
Labels: size/XS

#3424 Add Gitleaks.io to list of users
  USERS.md
Labels: size/XS

#3423 docs: Add Ayedo to Users.md
  USERS.md
Labels: size/XS
