Repository goreleaser/goreleaser, pull requests merged in 2022-05, with the labels that each got.

#3080 feat: improve docker errors
  internal/pipe/docker/docker.go
  www/docs/errors/docker-build.md
  www/mkdocs.yml
Labels: enhancement, docs, size/M

#3081 Fix typo in www/docs/errors/no-main.md
  www/docs/errors/no-main.md
Labels: size/XS

#3086 docs: fix several htmltest issues
  www/docs/cookbooks/using-jfrog-cli-to-publish-to-artifactory.md
  www/docs/customization/snapshots.md
  www/docs/errors/resource-not-accessible-by-integration.md
  www/docs/pro.md
  www/htmltest.yml
Labels: docs, size/S

#3087 fix: nfpm deprecation on nfpm check
  internal/deprecate/deprecate.go
  internal/deprecate/deprecate_test.go
  internal/deprecate/testdata/TestWriter.txt.golden
  internal/pipe/nfpm/nfpm.go
  www/docs/deprecations.md
Labels: bug, size/M

#3073 fix: update existing release drafts
  internal/client/github.go
Labels: size/M

#3090 docs(website): add SBOM section, update Docker as container
  www/docs/overrides/home.html
Labels: size/XS

#3088 feat: allow git remote urls from non-scm sources
  internal/git/config.go
  internal/git/config_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/milestone/milestone.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  pkg/config/config.go
Labels: enhancement, size/L

#3091 docs: add example for semantic-release
  www/docs/cookbooks/semantic-release.md
Labels: size/S

#3092 Add more sponsors to the readme
  README.md
Labels: size/S

#3093 feat: meta archives
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_meta_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
Labels: enhancement, size/L

#3100 refactor: improve archive pipe
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
Labels: enhancement, size/M

#3101 refactor: evaluate archive files in another package
  internal/archivefiles/archivefiles.go
  internal/archivefiles/archivefiles_test.go
  internal/archivefiles/testdata/a/a.txt
  internal/archivefiles/testdata/a/b/a.txt
  internal/archivefiles/testdata/a/b/c/d.txt
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
Labels: enhancement, size/L

#3107 fix: better handle docker skip errors
  internal/pipe/docker/docker.go
Labels: bug, size/XS

#3109 chore(deps): Included dependency review
  .github/workflows/depsreview.yaml
Labels: size/S

#3117 fix: brew formula class generation when using dots
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: bug, size/XS
