Repository goreleaser/goreleaser, pull requests merged in 2022-07, with the labels that each got.

#3221 fix: improve output on github actions
  cmd/root.go
  go.mod
  go.sum
  internal/logext/testdata/TestWriter/debug/0.txt.golden
  internal/logext/testdata/TestWriter/debug/1.txt.golden
  internal/logext/writer_test.go
Labels: bug, size/S

#3223 chore: make skip messages more idiomatic
  internal/middleware/errhandler/error.go
Labels: size/XS

#3222 test: reducing test ouput
  internal/pipe/git/git_test.go
  internal/pipe/universalbinary/universalbinary_test.go
  pkg/archive/tar/tar_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip_test.go
Labels: enhancement, size/XS

#3229 fix(build): set workdir as safe for git when running docker image
  scripts/entrypoint.sh
Labels: bug, size/XS

#3232 fix: build env overrides
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: bug, size/M

#3248 refactor(build): remove unused param
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
Labels: bug, size/M

#3247 feat(deps): update cosign to 1.10.0
  Dockerfile
Labels: enhancement, dependencies, size/XS

#3256 fix(archive): always strip parent if set
  internal/archivefiles/archivefiles.go
  internal/archivefiles/archivefiles_test.go
  www/docs/customization/archive.md
Labels: bug, size/S
