Repository goreleaser/goreleaser, pull requests merged in 2022-01, with the labels that each got.

#2802 fix: don't format github-native changelog
  internal/pipe/changelog/changelog.go
Labels: size/XS

#2806 Add prestd on users file
  USERS.md
Labels: size/XS

#2807 Update USERS.md
  USERS.md
Labels: size/XS

#2782 docs: goreleaser-xx
  www/docs/cookbooks/goreleaser-xx.md
  www/mkdocs.yml
Labels: size/S

#2795 feat: less logs for defaults
  internal/pipe/defaults/defaults.go
Labels: size/XS

#2799 feat(deps): update github.com/caarlos0/env/v6 from v6.8.0 to v6.9.1
  go.mod
  go.sum
Labels: size/XS

#2793 feat(deps): update go-github to v41
  go.mod
  go.sum
  internal/client/github.go
Labels: size/XS

#2797 feat: allow to template dockerfile
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  www/docs/customization/docker.md
Labels: size/M

#2770 Support extra_files in publishers
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/exec/testdata/a.txt
  pkg/config/config.go
  www/docs/customization/publishers.md
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: size/M

#2745 feat: add support for GitLab Generic Packages
  internal/client/gitlab.go
  pkg/config/config.go
  www/docs/scm/gitlab.md
Labels: enhancement, size/M

#2811 feat: allow multiple ids on universal binaries
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  pkg/config/config.go
  www/docs/customization/universalbinaries.md
Labels: enhancement, size/M

#2809 docs: correct installOnly in the documentation
  www/docs/ci/azurepipelines.md
Labels: docs, size/XS

#2803 fix: do not filter and sort github-native changelog
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: bug, size/L

#2750 feat: add generic webhook announcer
  internal/pipe/announce/announce.go
  internal/pipe/webhook/webhook.go
  internal/pipe/webhook/webhook_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/webhook.md
  www/mkdocs.yml
Labels: enhancement, size/L

#2810 refactor: improve gitlab cli a bit
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: enhancement, size/M

#2823 fix: go install and go-reddit
  go.mod
  go.sum
  internal/pipe/reddit/reddit.go
Labels: bug, size/XS

#2824 fix: linter issues after gotea update
  internal/client/gitea.go
Labels: bug, size/XS

#2826 feat: allow to template commit author
  internal/commitauthor/author.go
  internal/commitauthor/author_test.go
  internal/pipe/brew/brew.go
  internal/pipe/gofish/gofish.go
  internal/pipe/krew/krew.go
  internal/pipe/scoop/scoop.go
Labels: enhancement, size/L

#2834 fix: template main with gomod.proxy
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/gomod/gomod_proxy.go
  internal/pipe/prebuild/prebuild.go
  internal/pipe/prebuild/prebuild_test.go
  internal/pipeline/pipeline.go
Labels: bug, size/L

#2836 chore: remove stale trigger paths
  .github/workflows/docs.yml
Labels: size/XS

#2837 feat: manpages
  .gitignore
  .goreleaser.yaml
  cmd/man.go
  cmd/root.go
  go.mod
  go.sum
  scripts/manpages.sh
Labels: enhancement, size/M

#2838 feat: arch user repository integration
  .editorconfig
  .goreleaser.yaml
  go.mod
  go.sum
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/git/git.go
  internal/golden/golden.go
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/doc.go
  internal/pipe/aur/testdata/TestFullPipe/default-gitlab.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/default-gitlab.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/default.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/default.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/with-more-opts.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/with-more-opts.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPkgBuild.golden
  internal/pipe/aur/testdata/TestFullSrcInfo.golden
  internal/pipe/aur/testdata/TestRunPipe.pkgbuild.golden
  internal/pipe/aur/testdata/TestRunPipe.srcinfo.golden
  internal/pipe/aur/testdata/TestRunPipeBinaryRelease.pkgbuild.golden
  internal/pipe/aur/testdata/TestRunPipeBinaryRelease.srcinfo.golden
  internal/pipe/aur/tmpl.go
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/aur.md
  www/docs/customization/homebrew.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#2846 chore: update grammar in markdown
  www/docs/how-it-works.md
Labels: size/S

#2845 feat: write a dist/metadata.json
  internal/pipe/artifacts/artifacts.go
  internal/pipe/artifacts/artifacts_test.go
  internal/pipe/metadata/metadata.go
  internal/pipe/metadata/metadata_test.go
  internal/pipe/metadata/testdata/TestRun/artifacts.json.golden
  internal/pipe/metadata/testdata/TestRun/metadata.json.golden
  internal/pipeline/pipeline.go
Labels: enhancement, size/L

#2849 fix: pre-commit hook
  scripts/pre-commit.sh
Labels: size/XS

#2848 fix: lint issues
  pkg/config/config.go
  pkg/config/config_array_test.go
Labels: size/XS

#2850 fix(aur): version must be numbers only
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/testdata/TestFullPipe/default-gitlab.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/default-gitlab.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/default.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/default.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/with-more-opts.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/with-more-opts.srcinfo.golden
Labels: bug, size/M

#2851 docs(cookbooks): update links to the new goreleaser-cross home
  www/docs/cookbooks/cgo-and-crosscompiling.md
Labels: size/XS

#2855 feat: add goreleaser image to ArtifactHub
  .goreleaser.yaml
Labels: size/XS

#2858 feat: add additional properties for ArtifactHub
  .goreleaser.yaml
Labels: enhancement, size/S

#2864 Two line "extended" description
  www/docs/customization/nfpm.md
Labels: docs, size/XS
