Repository goreleaser/goreleaser, pull requests merged in 2023-01, with the labels that each got.

#3680 docs: rename `.goreleaser.yml` to `.goreleaser.yaml` in intro
  www/docs/intro.md
Labels: size/XS

#3686 feat: allow to template telegram.chat_id
  internal/pipe/telegram/telegram.go
  internal/pipe/telegram/telegram_test.go
  www/docs/customization/announce/telegram.md
Labels: size/M

#3688 Update USERS.md
  USERS.md
Labels: size/XS

#3667 feat: allow to template apk keyname
  internal/pipe/nfpm/nfpm.go
Labels: enhancement, size/XS

#3653 feat: add ko support
  cmd/release.go
  go.mod
  go.sum
  internal/pipe/docker/docker_test.go
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  internal/pipe/ko/testdata/app/go.mod
  internal/pipe/ko/testdata/app/main.go
  internal/pipe/publish/publish.go
  internal/testlib/docker.go
  pkg/config/config.go
  pkg/context/context.go
  pkg/defaults/defaults.go
  www/docs/customization/ko.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#3702 feat: deprecate --rm-dist in favor of new --clean flag
  Taskfile.yml
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  internal/pipe/dist/dist.go
  www/docs/ci/actions.md
  www/docs/ci/codefresh.md
  www/docs/ci/gitlab.md
  www/docs/cmd/goreleaser_build.md
  www/docs/cmd/goreleaser_release.md
  www/docs/cookbooks/override-image-name.md
  www/docs/cookbooks/semantic-release.md
  www/docs/customization/monorepo.md
  www/docs/customization/partial.md
  www/docs/deprecations.md
  www/docs/errors/no-main.md
  www/docs/install.md
  www/docs/quick-start.md
Labels: enhancement, size/M

#3698 refactor: improve go mod proxy usage
  internal/pipe/gomod/gomod_proxy.go
  internal/pipe/gomod/gomod_proxy_test.go
Labels: enhancement, size/M

#3712 feat: allow to template snaps.grade
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  www/docs/customization/snapcraft.md
Labels: enhancement, size/M

#3710 feat: allow to template release.disable and releaser.skip_upload
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  internal/pipe/publish/publish_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  www/docs/customization/release.md
Labels: size/L

#3719 fix: only debs should create iphoneos pkgs
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: bug

#3726 refactor: improve tmpls that eval to a bool
  internal/middleware/skip/skip.go
  internal/middleware/skip/skip_test.go
  internal/pipe/announce/announce.go
  internal/pipe/announce/announce_test.go
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
Labels: size/L

#3728 fix: improve handling of --rm-dist deprecation
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  cmd/root.go
  internal/deprecate/deprecate.go
  internal/pipe/dist/dist.go
  internal/pipe/dist/dist_test.go
  pkg/context/context.go
Labels: size/M

#3730 changelog: fix typo
  www/docs/customization/changelog.md
Labels: size/XS

#3733 Fix deprecation notice for `--rm-dist` -> `--clean`
  www/docs/deprecations.md
Labels: size/XS

#3734 build: increase release timeout
  Taskfile.yml
Labels: bug
