Repository goreleaser/goreleaser, pull requests merged in 2023-03, with the labels that each got.

#3813 fix: race condition on artifacts.List
  internal/artifact/artifact.go
  internal/exec/exec.go
  pkg/context/context.go
Labels: bug, size/S

#3811 Add my cross-compilation article
  www/docs/cookbooks/blog-posts.md
Labels: size/XS

#3814 feat(deps): update env to v7
  go.mod
  go.sum
  internal/pipe/discord/discord.go
  internal/pipe/linkedin/linkedin.go
  internal/pipe/mastodon/mastodon.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/opencollective/opencollective.go
  internal/pipe/reddit/reddit.go
  internal/pipe/slack/slack.go
  internal/pipe/smtp/smtp.go
  internal/pipe/teams/teams.go
  internal/pipe/telegram/telegram.go
  internal/pipe/twitter/twitter.go
  internal/pipe/webhook/webhook.go
Labels: enhancement, dependencies, size/M

#3815 fix: smtp mixup of env and yaml opts
  internal/pipe/smtp/smtp.go
  internal/pipe/smtp/smtp_test.go
  www/docs/customization/announce/smtp.md
Labels: bug, size/L

#3816 typo: document number error
  www/docs/errors/release-upload.md
Labels: size/XS

#3817 fix: remove unused field
  pkg/context/context.go
Labels: enhancement, size/XS

#3822 feat: ConventionalExtension on nFPM
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/M

#3821 feat: cosign update
  .goreleaser.yaml
  internal/pipe/sign/sign_docker.go
  internal/pipe/sign/sign_docker_test.go
  www/docs/customization/docker_sign.md
  www/docs/customization/sign.md
  www/docs/install.md
  www/docs/static/run
Labels: enhancement, size/M

#3823 fix: create temp docker outside dist
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: enhancement, size/S

#3831 test: improve file not found checkings
  internal/artifact/artifact_test.go
  internal/builders/golang/build_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/aur/aur_test.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/metadata/metadata_test.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/upload/upload_test.go
Labels: size/M

#3834 feat: add base template function
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/XS

#3854 fix(GO-2023-1621): update from go 1.20.1 to 1.20.2
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/fig.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  Dockerfile
  www/docs/ci/actions.md
Labels: security, size/S

#3861 fix(ko): disable SBOM when `sbom` is `none`
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
Labels: size/M

#3867 docs: add note about binary archives
  www/docs/customization/archive.md
Labels: docs, size/XS

#3874 build: fix golangci-lint failing
  .github/workflows/lint.yml
Labels: bug

#3841 feat: include prerelease suffix in git
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  pkg/config/config.go
  www/docs/customization/git.md
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: enhancement, size/M

#3853 feat: .Now template variable
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/XS

#3875 feat(deps): bump github.com/caarlos0/log from v0.2.1 to v0.2.2
  go.mod
  go.sum
Labels: dependencies, size/S

#3876 feat(deps): bump github.com/goreleaser/nfpm/v2 from v2.26.0 to v2.27.1
  go.mod
  go.sum
  www/docs/customization/nfpm.md
  www/docs/static/schema.json
Labels: dependencies, size/M

#3846 feat: scoop shortcuts
  internal/pipe/scoop/scoop.go
  pkg/config/config.go
  www/docs/customization/scoop.md
  www/docs/static/schema.json
Labels: enhancement, size/S

#3884 feat: blobs.disable
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_minio_test.go
  pkg/config/config.go
  www/docs/customization/blob.md
  www/docs/static/schema.json
Labels: enhancement, size/L

#3888 feat: IsDraft template variable
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#3889 fix: do not skip scoop on draft releases
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: bug, size/M

#3891 fix(gpg sign): issue #3890
  internal/pipe/git/git.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
Labels: enhancement, size/S

#3894 fix: clarify scoop no windows error
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  www/docs/errors/scoop-archive.md
Labels: bug, size/S

#3895 fix: improve brew no archive error
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: bug, size/M

#3897 internal/pipe/upload: fix redundant net/http import
  internal/pipe/upload/upload_test.go
Labels: size/M
