Repository goreleaser/goreleaser, pull requests merged in 2023-08, with the labels that each got.

#4227 fix(nix): multiple archives for the same platform
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_publish.nix.golden
Labels: bug, size/L

#4211 build: release nightly every Thursday
  .github/workflows/nightly.yml
  .goreleaser-nightly.yaml
  .goreleaser.yaml
Labels: enhancement, size/L

#4228 feat(snapcraft): allow to disable
  .goreleaser.yaml
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  pkg/config/config.go
  www/docs/customization/snapcraft.md
Labels: enhancement, size/S

#4218 make docker build stage files same as archive
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/testdata/Dockerfile.multiple
Labels: size/S

#4239 feat: publishers.disable
  .goreleaser.yaml
  internal/exec/exec.go
  internal/exec/exec_test.go
  pkg/config/config.go
  www/docs/customization/publishers.md
Labels: enhancement, size/M

#4210 fix: skip defaults for skipped pipes
  internal/pipe/defaults/defaults.go
  internal/pipe/defaults/defaults_test.go
  pkg/defaults/defaults.go
Labels: bug, size/XS

#4250 fix: snapshot should run before before hooks
  internal/pipe/snapshot/snapshot.go
  internal/pipeline/pipeline.go
Labels: bug, size/XS

#4244 feat: update to go 1.21
  .golangci.yaml
  CONTRIBUTING.md
  cmd/util_test.go
  go.mod
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/ko/testdata/app/go.mod
Labels: size/S

#4254 feat(dependencies): upgrade cosign
  Dockerfile
Labels: enhancement, dependencies, size/XS

#4251 feat(deps): update go-github to v54
  go.mod
  go.sum
  internal/client/github.go
  internal/client/github_test.go
Labels: dependencies, size/S

#4256 feat: improve template error handling
  internal/client/gitea_test.go
  internal/client/github_test.go
  internal/exec/exec_test.go
  internal/extrafiles/extra_files_test.go
  internal/pipe/archive/archive_meta_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/aur/aur_test.go
  internal/pipe/before/before_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/build/build_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/discord/discord_test.go
  internal/pipe/env/env_test.go
  internal/pipe/krew/krew_test.go
  internal/pipe/linkedin/linkedin_test.go
  internal/pipe/mastodon/mastodon_test.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/opencollective/opencollective_test.go
  internal/pipe/prebuild/prebuild_test.go
  internal/pipe/reddit/reddit_test.go
  internal/pipe/release/body_test.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/slack/slack_test.go
  internal/pipe/teams/teams_test.go
  internal/pipe/twitter/twitter_test.go
  internal/pipe/webhook/webhook.go
  internal/pipe/webhook/webhook_test.go
  internal/testlib/tmpl.go
  internal/tmpl/errors.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
Labels: enhancement, size/L

#4255 feat: git.ignore_tags
  .goreleaser.yaml
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  pkg/config/config.go
  www/docs/customization/git.md
Labels: enhancement, size/L

#4261 fix: failing when pull_request.base is empty
  internal/client/github.go
  internal/client/github_test.go
Labels: bug, size/M
