Repository goreleaser/goreleaser, pull requests merged in 2023-11, with the labels that each got.

#4403 build: only update docs, schema, after a release
  .github/workflows/generate-releases.yml
  .github/workflows/generate.yml
  .github/workflows/release.yml
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: enhancement, size/M

#4398 feat: check if go.mod has replace directives
  internal/pipe/gomod/gomod_proxy.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipeline/pipeline.go
Labels: enhancement, size/L

#4406 docs: fix typos
  internal/static/config.yaml
  www/docs/customization/templates.md
  www/docs/errors/docker-build.md
Labels: size/XS

#4420 feat(docs): Update command in SLSA verification blog post
  www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md
Labels: size/S

#4427 docs: update CONTRIBUTING.md add upx as optional prerequesite
  CONTRIBUTING.md
Labels: size/XS

#4428 fix: linkedin announce api changes
  internal/pipe/linkedin/client.go
  internal/pipe/linkedin/client_test.go
Labels: size/L

#4429 feat: validate ko's main path
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  www/docs/customization/ko.md
Labels: size/M

#4430 SBOM improvements
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  www/docs/customization/sbom.md
Labels: bug, enhancement, docs, size/M

#4441 fix: allow homebrew to use tar.xz format
  internal/pipe/brew/brew.go
Labels: size/XS

#4439 docs(azblob): correct auth to Azure storage service
  USERS.md
  www/docs/customization/blob.md
Labels: docs, size/S

#4442 feat: improve --single-target
  cmd/build.go
  cmd/build_test.go
  internal/pipe/build/build.go
  internal/pipe/build/filter.go
  internal/pipe/build/filter_test.go
  internal/pipe/partial/partial.go
  internal/pipe/partial/partial_test.go
  internal/pipeline/pipeline.go
  internal/testctx/testctx.go
  pkg/context/context.go
  www/docs/contributing.md
Labels: bug, size/L

#4449 docs: update deprecated `--skip-publish` release flag
  www/docs/quick-start.md
Labels: size/XS
