Repository goreleaser/goreleaser, pull requests merged in 2023-09, with the labels that each got.

#4265 feat(docker): retry push if 503
  internal/pipe/docker/docker.go
Labels: enhancement, size/M

#4269 feat: templates in upx.enabled
  internal/pipe/upx/upx.go
  internal/pipe/upx/upx_test.go
  pkg/config/config.go
  www/docs/customization/upx.md
Labels: enhancement, size/M

#4230 feat: support WASI
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
Labels: enhancement, size/XS

#4271 feat: allow goreleaser to run in gerrit, soft-serve and others
  internal/client/client.go
  internal/client/client_test.go
  internal/pipe/aur/aur.go
  internal/pipe/brew/brew.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/krew/krew.go
  internal/pipe/nix/nix.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/winget/winget.go
Labels: enhancement, size/L

#4275 fix(snapcrafts): skip publish is check by publish pipe
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
Labels: bug, size/S

#4273 fix(chocolatey): skip publish is check by publish pipe
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/chocolatey/chocolatey_test.go
Labels: bug, size/S

#4274 fix(custom_publishers): skip publish is check by publish pipe
  internal/pipe/custompublishers/custompublishers.go
  internal/pipe/custompublishers/custompublishers_test.go
Labels: bug, size/S

#4280 feat: skip gomod pipe when Go does not support modules
  internal/pipe/gomod/gomod.go
Labels: enhancement, size/XS

#4291 fix(sbom): Add LOCALAPPDATA to passthroughEnvVars
  internal/pipe/sbom/sbom.go
Labels: bug, size/XS

#4294 docs: fix link to homebrew formula on `install` page
  www/docs/install.md
Labels: size/XS

#4264 docs: blog
  scripts/pages/build.sh
  www/docker/Dockerfile
  www/docs/blog/.authors.yml
  www/docs/blog/index.md
  www/docs/blog/posts/2021-11-14-goreleaser-v1.md
  www/docs/blog/posts/2021-12-21-goreleaser-v1.2.md
  www/docs/blog/posts/2022-01-13-goreleaser-v1.3.md
  www/docs/blog/posts/2022-01-26-goreleaser-v1.4.md
  www/docs/blog/posts/2022-02-12-goreleaser-v1.5.md
  www/docs/blog/posts/2022-03-06-goreleaser-v1.6.md
  www/docs/blog/posts/2022-03-20-goreleaser-v1.7.md
  www/docs/blog/posts/2022-04-15-goreleaser-v1.8.md
  www/docs/blog/posts/2022-05-18-goreleaser-v1.9.md
  www/docs/blog/posts/2022-07-04-goreleaser-v1.10.md
  www/docs/blog/posts/2022-08-28-goreleaser-v1.11.md
  www/docs/blog/posts/2022-10-17-goreleaser-v1.12.md
  www/docs/blog/posts/2022-11-18-goreleaser-v1.13.md
  www/docs/blog/posts/2022-12-27-goreleaser-v1.14.md
  www/docs/blog/posts/2023-01-30-goreleaser-v1.15.md
  www/docs/blog/posts/2023-03-06-goreleaser-v1.16.md
  www/docs/blog/posts/2023-04-10-goreleaser-v1.17.md
  www/docs/blog/posts/2023-05-05-goreleaser-v1.18.md
  www/docs/blog/posts/2023-06-28-goreleaser-v1.19.md
  www/docs/blog/posts/2023-08-09-goreleaser-v1.20.md
  www/docs/blog/posts/2023-09-14-welcome.md
  www/docs/install.md
  www/docs/links.md
  www/htmltest.yml
  www/mkdocs.yml
Labels: docs, size/XXL

#4295 docs: fix some broken links
  www/docs/blog/posts/2022-10-17-goreleaser-v1.12.md
  www/docs/blog/posts/2022-11-18-goreleaser-v1.13.md
  www/docs/cookbooks/set-a-custom-git-tag.md
  www/docs/customization/changelog.md
  www/docs/pro.md
Labels: docs, size/S

#4297 docs: update goreleaser-action
  www/docs/ci/actions.md
Labels: docs, size/L

#4298 feat(winget): update manifest schema version & links
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.yaml.golden
Labels: enhancement, size/L

#4300 fix: chocolatey push failing
  .gitignore
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/chocolatey/chocolatey_test.go
  www/docs/customization/chocolatey.md
Labels: bug, docs, size/M

#4272 refactor: --skip=item
  cmd/build.go
  cmd/build_test.go
  cmd/helper_test.go
  cmd/release.go
  cmd/release_test.go
  internal/pipe/announce/announce.go
  internal/pipe/announce/announce_test.go
  internal/pipe/before/before.go
  internal/pipe/before/before_test.go
  internal/pipe/build/build.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/publish/publish.go
  internal/pipe/publish/publish_test.go
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_docker.go
  internal/pipe/sign/sign_docker_test.go
  internal/pipe/sign/sign_test.go
  internal/skips/skips.go
  internal/testctx/testctx.go
  pkg/context/context.go
  www/docs/deprecations.md
Labels: enhancement, size/XL

#4299 feat(winget): support dependencies
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  pkg/config/config.go
  www/docs/customization/winget.md
Labels: enhancement, size/L

#4301 fix(sbom): syft might fail on windows
  internal/pipe/sbom/sbom.go
  pkg/config/config.go
Labels: bug, size/XS

#4317 feat: add `map` and `indexOrDefault` template functions
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/L

#4310 docs: draft 1.21 announcement
  www/docs/blog/posts/2023-09-22-goreleaser-v1.21.md
Labels: docs, size/M

#4322 fix: git.ignore_tags not working
  internal/git/git.go
  internal/pipe/git/errors.go
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  www/docs/customization/git.md
Labels: bug, size/L

#4324 fix: git client should respect specified branch
  internal/client/git.go
  internal/client/git_test.go
  internal/pipe/brew/brew_test.go
  internal/pipe/krew/krew_test.go
  internal/pipe/scoop/scoop_test.go
  internal/testlib/git.go
Labels: bug, size/M

#4329 docs: release cadence post
  www/docs/blog/posts/2023-09-27-release-cadence.md
Labels: docs, size/L

#4328 docs: organizing docs a bit better
  www/docs/customization/jsonschema.md
  www/docs/customization/reportsizes.md
  www/docs/links.md
  www/mkdocs.yml
Labels: docs, size/L

#4334 refactor: improve releases/scm.go a bit
  internal/pipe/release/scm.go
Labels: enhancement, size/M
