Repository goreleaser/goreleaser, pull requests merged in 2023-04, with the labels that each got.

#3898 docs: standarizing docs defaults, since, etc
  www/docs/customization/announce/discord.md
  www/docs/customization/announce/index.md
  www/docs/customization/announce/linkedin.md
  www/docs/customization/announce/mastodon.md
  www/docs/customization/announce/mattermost.md
  www/docs/customization/announce/opencollective.md
  www/docs/customization/announce/reddit.md
  www/docs/customization/announce/slack.md
  www/docs/customization/announce/smtp.md
  www/docs/customization/announce/teams.md
  www/docs/customization/announce/telegram.md
  www/docs/customization/announce/twitter.md
  www/docs/customization/announce/webhook.md
  www/docs/customization/archive.md
  www/docs/customization/artifactory.md
  www/docs/customization/aur.md
  www/docs/customization/blob.md
  www/docs/customization/builds.md
  www/docs/customization/changelog.md
  www/docs/customization/checksum.md
  www/docs/customization/chocolatey.md
  www/docs/customization/dist.md
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
  www/docs/customization/docker_sign.md
  www/docs/customization/fury.md
  www/docs/customization/git.md
  www/docs/customization/homebrew.md
  www/docs/customization/hooks.md
  www/docs/customization/ko.md
  www/docs/customization/krew.md
  www/docs/customization/milestone.md
  www/docs/customization/nfpm.md
  www/docs/customization/nightlies.md
  www/docs/customization/partial.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/sbom.md
  www/docs/customization/scoop.md
  www/docs/customization/sign.md
  www/docs/customization/snapcraft.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/templatefiles.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/upload.md
  www/docs/customization/verifiable_builds.md
  www/docs/scm/gitlab.md
Labels: size/XXL

#3901 fix: set parallelism to match Linux container CPU
  cmd/build.go
  cmd/release.go
  go.mod
  go.sum
  main.go
Labels: size/S

#3910 feat: allow to forcefully use a token when multiple are set
  internal/pipe/env/env.go
  internal/pipe/env/env_test.go
  www/docs/errors/multiple-tokens.md
Labels: enhancement, size/L

#3913 docs: fix install's cosign steps
  www/docs/install.md
  www/docs/static/run
Labels: bug, docs, size/L

#3903 feat: allow to PR homebrew taps
  internal/client/client.go
  internal/client/config.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/client/mock.go
  internal/client/testdata/github/pull.json
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestRunPipePullRequest.rb.golden
  internal/pipe/changelog/changelog.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/static/schema.json
Labels: enhancement, size/XL

#3915 feat: allow to pr krew plugin manifests
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/krew/testdata/TestRunPipePullRequest.yaml
  www/docs/customization/krew.md
Labels: enhancement, size/L

#3916 feat: allow to pr scoop manifests
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
  www/docs/customization/scoop.md
Labels: size/L

#3904 fix: use git-archive under the hood
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_meta_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  internal/testlib/archive.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/archive/tar/tar.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz.go
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
  www/docs/customization/source.md
Labels: bug, enhancement, size/L

#3920 feat: add context info to docker build errors
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/testdata/Dockerfile.wrongbin
Labels: enhancement, size/M

#3921 Update USERS.md
  USERS.md
Labels: size/XS

#3924 fix(jsonschema): add binary to Archive format enum
  pkg/config/config.go
  www/docs/static/schema.json
Labels: size/XS

#3940 fix(nfpm): Add extension to produced artifacts
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: bug, size/XS

#3938 fix: source archive not being added when no extra-files
  internal/pipe/sourcearchive/source.go
  internal/pipe/sourcearchive/source_test.go
  pkg/archive/zip/zip.go
  pkg/archive/zip/zip_test.go
Labels: bug, size/L

#3942 fix: improve docker error handling
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
Labels: bug

#3939 fix: build should output more debug info
  internal/builders/golang/build.go
Labels: bug

#3925 test: ensure utf-8 sources/archives filenames work properly
  internal/pipe/sourcearchive/source_test.go
  internal/testlib/archive.go
  pkg/archive/archive_test.go
  pkg/archive/tar/tar.go
  pkg/archive/tar/tar_test.go
Labels: bug, size/M

#3946 fix: do not fatal on automaxprocs error
  main.go
Labels: bug, size/XS

#3936 feat: add force_token to config
  internal/pipe/env/env.go
  pkg/config/config.go
  www/docs/errors/multiple-tokens.md
  www/docs/static/schema.json
Labels: size/S

#3953 docs(artifactory): Add details on custom_artifact_name
  www/docs/customization/artifactory.md
Labels: size/XS

#3954 feat: log generated artifact sizes
  .goreleaser.yaml
  internal/artifact/artifact.go
  internal/pipe/reportsizes/reportsizes.go
  internal/pipe/reportsizes/reportsizes_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  www/docs/customization/reportsizes.md
  www/mkdocs.yml
Labels: enhancement, size/L

#3960 feat: allow to template nfpms.package_name
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: enhancement

#3962 feat: new --version output
  art.txt
  cmd/root.go
  cmd/root_test.go
  go.mod
  go.sum
  main.go
  main_test.go
  testdata/TestVersion/all_empty.json.golden
  testdata/TestVersion/complete.json.golden
  testdata/TestVersion/only_version.json.golden
  testdata/TestVersion/version,_date,_built_by.json.golden
  testdata/TestVersion/version_and_date.json.golden
Labels: enhancement, size/L
