Repository goreleaser/goreleaser, pull requests merged in 2023-12, with the labels that each got.

#4456 docs: Removed the duplicate GoReleaser Pro entry
  www/docs/customization/changelog.md
Labels: size/XS

#4454 feat: allow to template builds.gobinary
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  www/docs/customization/builds.md
Labels: enhancement, size/S

#4471 fix(github): do not fail branch creation if it already exists
  internal/client/github.go
  internal/client/github_test.go
Labels: size/M

#4473 fix: add -c flags when building go test
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: size/S

#4481 feat(homebrew): add os to dependency
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/static/schema.json
Labels: enhancement, size/S

#4484 feat: aur dir
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/testdata/TestFullPipe/custom-dir.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/custom-dir.srcinfo.golden
  pkg/config/config.go
  www/docs/customization/aur.md
Labels: enhancement, size/M

#4483 test: run testifylint -fix
  .golangci.yaml
  internal/artifact/artifact_test.go
  internal/builders/golang/build_test.go
  internal/client/gitea_test.go
  internal/client/github_test.go
  internal/commitauthor/author_test.go
  internal/gio/copy_test.go
  internal/middleware/errhandler/error_test.go
  internal/pipe/announce/announce_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/build/build_test.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/chocolatey/chocolatey_test.go
  internal/pipe/discord/discord_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/linkedin/linkedin_test.go
  internal/pipe/mastodon/mastodon_test.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/opencollective/opencollective_test.go
  internal/pipe/publish/publish_test.go
  internal/pipe/reddit/reddit_test.go
  internal/pipe/release/release_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/slack/slack_test.go
  internal/pipe/teams/teams_test.go
  internal/pipe/telegram/telegram_test.go
  internal/pipe/twitter/twitter_test.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/upx/upx_test.go
  internal/pipe/webhook/webhook_test.go
  internal/semerrgroup/sem_test.go
  internal/testlib/skip.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip_test.go
Labels: enhancement, size/L

#4486 docs: update snap link
  www/docs/customization/snapcraft.md
Labels: size/XS

#4490 chore: update the link to the go wiki page on first-class ports
  www/docs/customization/builds.md
Labels: size/XS

#4489 fix(winget): improve schema
  pkg/config/config.go
  www/docs/static/schema.json
Labels: bug, size/S

#4495 fix(nix): include unzip if any artifact is a zip
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/testdata/TestRunPipe/zip-and-tar_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip-and-tar_publish.nix.golden
Labels: bug, size/L

#4498 feat(winget): support installing .exe directly
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.installer.yaml.golden
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
Labels: enhancement, size/L

#4502 fix(aur): support wrap_in_directory
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/testdata/TestRunPipeWrappedInDirectory.pkgbuild.golden
  internal/pipe/aur/testdata/TestRunPipeWrappedInDirectory.srcinfo.golden
Labels: bug, size/M

#4497 feat(nix): validate licenses
  .github/workflows/generate.yml
  Taskfile.yml
  internal/pipe/nix/licenses.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  scripts/gen-nix-licenses.sh
Labels: enhancement, size/L

#4499 docs: Update repository.md typo in documentation check_boxex > check_boxes
  www/docs/includes/repository.md
Labels: size/XS

#4507 feat: nix devShell
  .envrc
  .github/workflows/docs.yml
  .gitignore
  Taskfile.yml
  flake.lock
  flake.nix
  www/docker/Dockerfile
Labels: size/L

#4508 feat: store which action is being taken in the context
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  pkg/context/context.go
Labels: enhancement, size/S
