Repository goreleaser/goreleaser, pull requests merged in 2023-06, with the labels that each got.

#4064 feat: Checksums as a template field
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/TestDescribeBodyWithHeaderAndFooter.golden
  www/docs/customization/templates.md
Labels: enhancement, size/L

#4069 style: spelling and grammar fixes
  internal/client/gitea_test.go
  internal/client/gitlab_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/metadata/metadata.go
  internal/pipe/pipe.go
  internal/pipe/slack/slack_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipeline/pipeline.go
  internal/semerrgroup/sem.go
  internal/testlib/tmpl.go
  www/docs/cookbooks/using-jfrog-cli-to-publish-to-artifactory.md
  www/docs/customization/artifactory.md
  www/docs/customization/builds.md
  www/docs/customization/chocolatey.md
  www/docs/customization/includes.md
  www/docs/customization/nfpm.md
  www/docs/customization/scoop.md
  www/docs/customization/templates.md
  www/docs/customization/universalbinaries.md
Labels: size/M

#4070 docs: add missing dash in ldflags default
  www/docs/customization/builds.md
Labels: size/XS

#4071 feat: completion improvements
  cmd/build.go
  cmd/check.go
  cmd/docs.go
  cmd/healthcheck.go
  cmd/init.go
  cmd/man.go
  cmd/release.go
  cmd/root.go
  cmd/schema.go
Labels: size/L

#4073 fix: deprecate brews.plist
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: enhancement

#4075 feat: remove deprecated replacements
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/http/http.go
  internal/http/http_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/config/config.go
  www/docs/customization/templates.md
  www/docs/deprecations.md
Labels: enhancement

#4076 feat: remove deprecated rlcp options
  internal/archivefiles/archivefiles.go
  internal/archivefiles/archivefiles_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/sourcearchive/source.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: enhancement, size/L

#4098 docs: include markdown plugin
  Taskfile.yml
  scripts/pages/build.sh
  www/docker/Dockerfile
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
  www/docs/includes/repository.md
  www/mkdocs.yml
Labels: enhancement, size/XL

#4099 feat: deprecate brews.tap, krews.index & scoops.bucket
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
  www/docs/deprecations.md
  www/docs/includes/repository.md
Labels: enhancement, size/L

#4097 feat: envOrDefault template function
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#4105 feat: support pull request templates
  internal/client/github.go
  internal/client/github_test.go
Labels: enhancement, size/M

#4106 docs: add more info about opening prs
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
  www/docs/includes/prs.md
Labels: docs, size/M

#4107 feat: make git client support creating multiple files in a single commit
  internal/client/client.go
  internal/client/git.go
  internal/client/git_test.go
Labels: enhancement, size/M

#4081 feat: winget support
  .goreleaser.yaml
  internal/artifact/artifact.go
  internal/golden/golden.go
  internal/pipe/publish/publish.go
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/winget.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#4112 docs: runner script fixes
  www/docs/static/run
Labels: size/S

#4113 fix: runner tarball download URL
  www/docs/static/run
Labels: size/XS

#4114 fix: runner tarball extract path
  www/docs/static/run
Labels: size/XS

#4118 test: ECONNREFUSED
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/upload/upload_test.go
Labels: size/S

#4117 fix: artifact.Path should filepath.ToSlash
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
Labels: enhancement, size/XS

#4116 fix: archives should always use forward slash
  internal/archivefiles/archivefiles.go
Labels: size/XS

#4119 test: improve executable not found checks
  internal/pipe/build/build_test.go
  internal/pipe/docker/docker.go
  internal/pipe/sign/sign_test.go
  internal/pipe/universalbinary/universalbinary_test.go
Labels: size/S

#4120 test: syscall.EACCES and os.ErrNoExist
  internal/pipe/checksums/checksums_test.go
  internal/pipe/gomod/gomod_proxy_test.go
Labels: enhancement, size/XS

#4122 feat: changelog.include
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  pkg/config/config.go
  www/docs/customization/changelog.md
Labels: enhancement, size/L

#4124 test: improve more tests
  internal/pipe/env/env_test.go
  internal/pipe/metadata/metadata_test.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/zip/zip_test.go
Labels: enhancement, size/M

#4126 feat(aur): single commit per package
  internal/pipe/aur/aur.go
Labels: enhancement, size/S

#4127 feat: continue on error
  cmd/release.go
  internal/middleware/errhandler/error.go
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/chocolatey/chocolatey_test.go
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/milestone/milestone.go
  internal/pipe/milestone/milestone_test.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/publish/publish.go
  internal/pipe/publish/publish_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  internal/pipeline/pipeline.go
  pkg/context/context.go
Labels: enhancement, size/L

#4133 fix: do runner cleanups also on `SIGINT` and `SIGTERM`
  www/docs/static/run
Labels: size/XS

#4136 fix: umask nfpm field
  internal/pipe/nfpm/nfpm.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: docs, size/S

#4137 fix: improve brew/krew/scoop/nix/winget paths inside dist
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/nix/nix.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/winget/template.go
Labels: enhancement, size/M

#4138 fix(snapcraft): title and icon are optional
  internal/pipe/snapcraft/snapcraft.go
Labels: bug, size/XS

#4139 fix(winget): incorrect filenames
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.locale.en-US.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
Labels: bug

#4140 test: use `t.Setenv` to set env vars
  cmd/build_test.go
  internal/builders/golang/build_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/build/build_test.go
  internal/pipe/git/git_test.go
  internal/pipe/slack/slack_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/testlib/path_test.go
  pkg/context/context_test.go
Labels: enhancement, size/M

#4144 feat(deps): bump github.com/goreleaser/nfpm/v2 from 2.30.1 to 2.31.0
  go.mod
  go.sum
Labels: dependencies, size/L

#4146 feat(deps): bump github.com/google/go-github/v53 50.1.0 to 53.2.0
  go.mod
  go.sum
  internal/client/github.go
  internal/client/github_test.go
Labels: dependencies, size/S

#4150 fix: Scoop releases being skipped via disabled SCM releases
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
Labels: size/M

#4151 build(nix): fix goreleaser config path
  .goreleaser.yaml
Labels: bug, size/XS

#4157 refactor(winget): minor improvements
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
Labels: enhancement, size/M

#4152 fix(github): check rate limit again after sleeping
  internal/client/github.go
  internal/client/github_test.go
Labels: bug, size/S

#4158 chore: add function to apply template multiple times
  internal/archivefiles/archivefiles.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nix/nix.go
  internal/pipe/scoop/scoop.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/winget/winget.go
  internal/tmpl/tmpl.go
Labels: size/L
