Repository goreleaser/goreleaser, pull requests merged in 2023-07, with the labels that each got.

#4164 fix(winget): add missing fields, more templates
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  pkg/config/config.go
  www/docs/customization/winget.md
Labels: enhancement, size/L

#4170 docs: fix yaml formatting on scoop deprecations
  www/docs/deprecations.md
Labels: size/XS

#4178 fix: Delete temporary dir used for docker build
  internal/pipe/docker/docker.go
Labels: size/XS

#4183 docs: fix links
  CONTRIBUTING.md
Labels: size/XS

#4182 feat: adds syft to docker image
  Dockerfile
Labels: size/XS

#4187 ci: append envs when calling docker instead of overriding
  internal/pipe/docker/api.go
Labels: size/XS

#4161 Support `make_latest` for GitHub release
  internal/client/github.go
  pkg/config/config.go
  www/docs/customization/release.md
Labels: size/S

#4175 fix(nfpm): lintian unix path
  internal/pipe/nfpm/nfpm.go
Labels: enhancement, size/XS

#4172 feat: support setting mod_timestamp in universalbinary
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  pkg/config/config.go
  www/docs/customization/builds.md
  www/docs/customization/universalbinaries.md
Labels: enhancement, size/L

#4191 refactor: gio.Chtimes
  internal/builders/golang/build.go
  internal/gio/chtimes.go
  internal/gio/chtimes_test.go
  internal/pipe/universalbinary/universalbinary.go
Labels: enhancement, size/L

#4188 feat: metadata mod_timestamp
  .goreleaser.yaml
  internal/pipe/metadata/metadata.go
  internal/pipe/metadata/metadata_test.go
  internal/pipe/reportsizes/reportsizes_test.go
  pkg/config/config.go
  www/docs/customization/metadata.md
  www/mkdocs.yml
Labels: enhancement, size/L

#4193 feat(scoop): support arm64
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/Test_buildManifest/common.json.golden
  internal/pipe/scoop/testdata/Test_buildManifest/gitlab_url_template.json.golden
  internal/pipe/scoop/testdata/Test_buildManifest/pre-post-install.json.golden
  internal/pipe/scoop/testdata/Test_buildManifest/url_template.json.golden
Labels: enhancement, size/M

#4195 fix(winget): replace forward slashes in Winget `RelativeFilePath`
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.installer.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
Labels: bug, size/M

#4199 fix(winget): improve commit msgs
  internal/client/client.go
  internal/client/mock.go
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
Labels: enhancement, size/M

#4201 chore: remove comment about WSL failure
  main.go
Labels: size/XS

#4205 docs: fix typo in builds.md
  www/docs/customization/builds.md
Labels: size/S

#4207 Fix deprecations notice about `scoops.bucket`
  www/docs/deprecations.md
Labels: size/XS

#4206 feat: improve output
  cmd/config.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/deprecate/deprecate.go
  internal/deprecate/testdata/TestNotice.txt.golden
  internal/deprecate/testdata/TestNoticeCustom.txt.golden
  internal/logext/styles.go
  internal/pipe/env/env.go
Labels: enhancement, size/M

#4217 feat(brew): extra_install
  .goreleaser.yaml
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestRunPipeBinaryRelease.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipePullRequest.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: enhancement, size/M
