Repository goreleaser/goreleaser, pull requests merged in 2023-10, with the labels that each got.

#4356 refactor(tmpl): avoid unnecessary byte/string conversion
  internal/tmpl/tmpl.go
Labels: size/XS

#4362 refactor: use ordered.First
  go.mod
  go.sum
  internal/client/git.go
  internal/client/github.go
  internal/pipe/git/git.go
Labels: enhancement, size/M

#4361 SLSA Provenance generation blog post
  www/docs/blog/.authors.yml
  www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md
  www/docs/static/slsa-provenance-generation.png
Labels: size/L

#4370 fix: build --single-target
  cmd/build.go
  cmd/build_test.go
Labels: bug, size/M

#4389 feat(nix): mark all Nix packages with the right source provenance
  internal/pipe/nix/testdata/TestRunPipe/deps_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/deps_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/extra-install_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/extra-install_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip_publish.nix.golden
  internal/pipe/nix/tmpl.nix
Labels: bug, size/M

#4385 fix: sort checksum lines by filename
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/checksums/testdata/order/a.txt
  internal/pipe/checksums/testdata/order/b.txt
  internal/pipe/checksums/testdata/order/c.txt
  internal/pipe/checksums/testdata/order/d.txt
Labels: size/M

#4391 feat: version in the yaml file
  .goreleaser.yaml
  internal/static/config.yaml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: enhancement, size/M

#4394 chore: add updatecli.io to USERS.md
  USERS.md
Labels: size/XS
