Repository goreleaser/goreleaser, pull requests merged in 2023-02, with the labels that each got.

#3743 fix: honouring ko bare option
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  pkg/config/config.go
Labels: size/M

#3747 fix: do not do fancy 3rd party process logging
  internal/exec/exec.go
  internal/logext/testdata/TestWriter/debug.txt.golden
  internal/logext/testdata/TestWriter/debug/0.txt.golden
  internal/logext/testdata/TestWriter/debug/1.txt.golden
  internal/logext/writer.go
  internal/logext/writer_test.go
  internal/pipe/before/before.go
  internal/pipe/docker/api.go
  internal/pipe/sbom/sbom.go
  internal/pipe/sign/sign.go
  internal/shell/shell.go
Labels: bug, enhancement, security

#3756 fix: force specific version of go-crypto
  go.mod
  go.sum
Labels: bug, dependencies

#3757 build: use go1.20
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/docs.yml
  .github/workflows/fig.yml
  .github/workflows/generate.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .golangci.yaml
  CONTRIBUTING.md
  Dockerfile
  cmd/util_test.go
  go.mod
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/ko/testdata/app/go.mod
  internal/pipe/sign/sign_test.go
  www/docs/ci/actions.md
  www/docs/ci/azurepipelines.md
  www/docs/ci/circle.md
  www/docs/ci/codefresh.md
  www/docs/contributing.md
Labels: enhancement, size/M

#3764 test: fix exec tests on go 1.20
  internal/exec/exec_test.go
Labels: size/XS

#3765 fix(gitlab): correctly prepend/append/keep releases notes
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: bug, size/M

#3758 feat: finally deprecate the single build option
  internal/pipe/build/build.go
  pkg/config/config.go
  www/docs/customization/builds.md
  www/docs/deprecations.md
  www/docs/static/schema.json
  www/mkdocs.yml
Labels: enhancement, size/M

#3735 build: do not release for windows arm7
  .goreleaser.yaml
Labels: bug, size/XS

#3753 feat: add OpenCollective
  internal/pipe/announce/announce.go
  internal/pipe/opencollective/opencollective.go
  internal/pipe/opencollective/opencollective_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/opencollective.md
  www/mkdocs.yml
Labels: enhancement, size/L

#3775 docs: update ref links
  www/docs/customization/snapcraft.md
Labels: size/XS

#3788 fix: better handle password protected keys
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  www/docs/customization/aur.md
Labels: bug, docs, size/M

#3793 fix: nfpm replacements deprecation
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: size/M

#3797 feat: scoop depends
  internal/pipe/scoop/scoop.go
  pkg/config/config.go
  www/docs/customization/scoop.md
  www/docs/static/schema.json
Labels: enhancement, size/XS

#3794 fix: convert to forward slashes inside gio.Copy
  internal/gio/copy.go
Labels: bug

#3804 fix: meta archives make the other archives be ignored
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
Labels: bug, size/M
