Repository goreleaser/goreleaser, pull requests merged in 2023-05, with the labels that each got.

#3965 feat: native upx support
  .github/workflows/build.yml
  .goreleaser.yaml
  internal/pipe/upx/upx.go
  internal/pipe/upx/upx_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/upx.md
  www/mkdocs.yml
Labels: enhancement, size/L

#3967 feat: IsGitDirty template variable
  internal/pipe/git/git.go
  internal/pipe/git/git_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#3968 fix: pass tree state as ldflag
  .goreleaser.yaml
  main.go
Labels: enhancement, size/S

#3966 feat: improve output
  go.mod
  go.sum
  internal/artifact/artifact.go
  internal/builders/golang/build_test.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/exec/exec.go
  internal/gio/copy.go
  internal/http/http.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/before/before.go
  internal/pipe/blob/upload.go
  internal/pipe/docker/api.go
  internal/pipe/reportsizes/reportsizes.go
  internal/pipe/sbom/sbom.go
  internal/pipe/scoop/scoop.go
  internal/pipe/sign/sign.go
  internal/pipe/upload/upload_test.go
  internal/shell/shell.go
Labels: enhancement, size/L

#3980 feat: allow to goreleaser check multiple files
  cmd/check.go
  cmd/check_test.go
Labels: enhancement, size/M

#3987 Fixes for prebuilt binaries docs
  www/docs/customization/builds.md
Labels: size/XS

#3992 fix: warn when no match on archive files
  internal/archivefiles/archivefiles.go
Labels: enhancement, size/M

#4008 feat: allow to template dockers.skip_push and docker_manifests.skip_push
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  www/docs/customization/docker.md
  www/docs/customization/docker_manifest.md
Labels: enhancement, size/M

#4007 fix: goreleaser build index out of range
  cmd/build.go
  cmd/build_test.go
Labels: bug, size/S

#4010 Pre-fill scopes for new Personal Access Token
  www/docs/quick-start.md
Labels: size/XS

#4013 fix(archive): warn only for non-default globs with no matches
  internal/archivefiles/archivefiles.go
  internal/pipe/archive/archive.go
  pkg/config/config.go
Labels: bug, size/S

#4012 feat: nix support
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  internal/artifact/artifact.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/template.go
  internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
  internal/pipe/nix/tmpl.nix
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/nix.md
  www/docs/install.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#4039 fix(nfpm): write too long when writing the lintian file
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: bug, size/M

#4043 feat(ko): allow to have an empty tag name
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  www/docs/customization/ko.md
Labels: enhancement, size/M

#4037 feat(github): avoid rate limits
  internal/client/github.go
  internal/client/github_test.go
Labels: enhancement, size/L

#4038 feat: allow to sign KO manifests
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  www/docs/customization/ko.md
Labels: enhancement, size/M

#4036 feat(telegram): ability to choose msg format, mdv2escape
  internal/pipe/telegram/telegram.go
  internal/pipe/telegram/telegram_test.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/config/config.go
  www/docs/customization/announce/telegram.md
  www/docs/customization/templates.md
Labels: bug, enhancement, size/L

#4017 feat: improve verbose output
  cmd/root.go
  internal/git/git.go
  www/docs/ci/codefresh.md
  www/docs/cookbooks/semantic-release.md
  www/docs/customization/release.md
  www/docs/deprecations.md
Labels: enhancement, size/M

#4051 feat(nix): support armv6l and armv7l
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
  internal/pipe/nix/tmpl.nix
Labels: enhancement, size/L

#4053 feat(github): allow to PR cross-repo
  internal/client/client.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/mock.go
  internal/pipe/brew/brew.go
  internal/pipe/krew/krew.go
  internal/pipe/nix/nix.go
  internal/pipe/scoop/scoop.go
  pkg/config/config.go
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
Labels: enhancement, size/L

#4054 feat(github): allow to open PRs as drafts
  internal/client/client.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/mock.go
  internal/pipe/brew/brew.go
  internal/pipe/krew/krew.go
  internal/pipe/nix/nix.go
  internal/pipe/scoop/scoop.go
  pkg/config/config.go
  www/docs/cookbooks/set-a-custom-git-tag.md
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
Labels: enhancement, size/M

#4055 chore: fix issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
Labels: size/XS

#4056 feat(upx): allow to filter by goos, goarch, goarm, goamd64
  internal/pipe/upx/upx.go
  internal/pipe/upx/upx_test.go
  pkg/config/config.go
  www/docs/customization/upx.md
Labels: enhancement, size/L

#4057 feat(scoop): allow to template description and homepage
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
  www/docs/customization/scoop.md
Labels: enhancement, size/L
