Repository goreleaser/goreleaser, pull requests merged in 2024-10, with the labels that each got.

#5167 test: add missing file.Close() calls
  internal/client/github_test.go
  internal/client/gitlab_test.go
  internal/testlib/archive.go
Labels: size/M

#5176 point to GHCR instead of GCR for cosign container
  Dockerfile
Labels: size/XS

#5173 fix(changelog): fix random order of first commit in first release
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: size/S

#5192 brew: Fix Forumla Class Name builder
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: size/M

#5185 fix(gitlab): improve artifact upload retry
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: bug

#5186 feat(build): add GO386, GOMIPS64, GORISCV64, and GOPPC64 support
  internal/artifact/artifact.go
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/archive/archive.go
  internal/pipe/build/build.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/snapcraft/snapcraft.go
  internal/tmpl/tmpl.go
  pkg/build/build.go
  pkg/config/config.go
  www/docs/customization/builds.md
  www/docs/customization/templates.md
Labels: enhancement, size/XL

#5200 fix: tmpl always copy before modifying
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
Labels: enhancement, size/M

#5208 refactor: improve buildtarget.List
  internal/builders/buildtarget/targets.go
Labels: size/S

#5196 ci: add riscv64 in release
  .goreleaser.yaml
Labels: size/XS

#5220 fix: typo in testctx.WithConfig parameter
  internal/testctx/testctx.go
Labels: size/XS

#5221 refactor: use std maps,slices instead of golang.org/exp
  go.mod
  internal/builders/golang/build.go
  internal/pipe/brew/brew.go
  internal/pipe/nix/nix.go
  internal/skips/skips.go
  internal/skips/skips_test.go
Labels: size/M

#5227 feat(ko): support annotations and user
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  pkg/config/config.go
  www/docs/customization/ko.md
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: size/L

#5233 refactor: rename archive.Copying to archive.Copy
  internal/pipe/sourcearchive/source.go
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/archive/tar/tar.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz.go
  pkg/archive/zip/zip.go
Labels: size/S

#5235 refactor: remove empty lines, fix //nolint
  .golangci.yaml
  internal/client/gitea.go
  internal/pipe/archive/archive_test.go
  internal/pipe/aur/aur.go
  internal/pipe/brew/brew.go
  internal/pipe/changelog/changelog.go
  internal/pipe/effectiveconfig/config.go
  internal/pipe/krew/krew.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/notary/macos.go
  internal/pipe/sbom/sbom.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/upx/upx_test.go
  internal/pipe/winget/template.go
  pkg/archive/zip/zip.go
Labels: size/M
