Repository goreleaser/goreleaser, pull requests merged in 2024-08, with the labels that each got.

#5035 fix(gitlab): release file URL broken
  internal/client/gitlab.go
Labels: size/XS

#5018 feat: binary signs
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_binary.go
  internal/pipe/sign/sign_binary_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  pkg/healthcheck/healthcheck.go
  www/docs/customization/binary_sign.md
  www/docs/customization/sign.md
  www/mkdocs.yml
Labels: enhancement, size/L

#5057 feat: when --clean, remove dist before checking git state
  internal/pipe/defaults/defaults.go
  internal/pipe/defaults/defaults_test.go
  internal/pipe/dist/dist.go
  internal/pipe/dist/dist_test.go
  internal/pipeline/pipeline.go
  pkg/defaults/defaults.go
Labels: enhancement, size/M

#5062 ci: split test and check jobs
  .github/workflows/build.yml
Labels: enhancement

#5063 feat(deps): update ko and gocloud.dev
  go.mod
  go.sum
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  www/docs/customization/ko.md
  www/docs/deprecations.md
Labels: enhancement, dependencies, size/L

#5065 sec(deps): update docker/docker and google/go-containerregistry
  go.mod
  go.sum
Labels: size/M

#5066 chore(deps): update env and lipgloss
  go.mod
  go.sum
Labels: size/XS

#5067 docs: use "~> v2" in GitHub actions docs
  www/docs/ci/actions.md
Labels: size/XS

#5079 test: make test pass on go 1.23
  internal/pipe/gomod/gomod_proxy_test.go
Labels: size/XS

#5087 chore: use snapshot.version_template in own config
  .goreleaser.yaml
Labels: size/XS

#5073 chore(deps): update bluesky/indigo
  go.mod
  go.sum
Labels: dependencies, size/S

#5088 build: constant archive files owner, group, and mtime
  .goreleaser.yaml
Labels: enhancement, size/S

#5082 build: go 1.23
  .golangci.yaml
  CONTRIBUTING.md
  cmd/util_test.go
  go.mod
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/ko/testdata/app/go.mod
  www/docs/contributing.md
  www/docs/install.md
Labels: enhancement, size/S

#5090 build: fix port error with dockertest on blob_minio_test.go
  internal/pipe/blob/blob_minio_test.go
Labels: bug, size/XS

#5089 feat(build): template skip
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/builds.md
Labels: enhancement, size/S

#5075 feat(nfpm): better support aix
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nfpm/testdata/testfile-ppc64.txt
Labels: enhancement, size/M

#5091 chore(deps): update gocloud to v0.39.0
  go.mod
  go.sum
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/upload.go
Labels: dependencies, size/L

#5099 chore(deps): upgrade cosign to 2.4.0
  Dockerfile
Labels: size/XS

#5106 fix: Handle error on failed release (github)
  internal/client/github.go
Labels: bug, size/S

#5107 test: do not fail if missing binaries
  internal/pipe/nix/nix_test.go
  internal/pipe/upx/upx_test.go
Labels: enhancement, size/XS

#5111 chore: fix linter errors
  internal/builders/golang/build_test.go
  internal/client/gitea_test.go
  internal/client/github_test.go
  internal/client/gitlab_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/mattermost/mattermost_test.go
  internal/pipe/webhook/webhook_test.go
Labels: size/L
