Repository goreleaser/goreleaser, pull requests merged in 2024-03, with the labels that each got.

#4694 feat: fig is being sunset, remove
  .github/workflows/fig.yml
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement, size/M

#4691 fix: do not log `release published` if it is a draft
  internal/pipe/release/release.go
Labels: size/XS

#4701 chore: remove repetitive words
  internal/middleware/middleware.go
  internal/pipe/winget/winget.go
Labels: size/XS

#4704 docs(blog): fix broken link
  www/docs/blog/posts/2022-03-28-supply-chain-sec.md
Labels: size/XS

#4695 fix: only build archlinux and aur for supported arches
  internal/pipe/aur/aur.go
  internal/pipe/aur/testdata/TestRunPipe.pkgbuild.golden
  internal/pipe/aur/testdata/TestRunPipe.srcinfo.golden
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
Labels: bug, size/M

#4706 feat: support netbsd/arm64
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
Labels: size/XS

#4707 feat: checksums.split
  internal/artifact/artifact.go
  internal/pipe/checksums/checksums.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/release/body.go
  internal/pipe/release/body_test.go
  internal/pipe/release/testdata/TestDescribeBodyMultipleChecksums.golden
  pkg/config/config.go
  www/docs/customization/checksum.md
  www/docs/customization/templates.md
Labels: size/L

#4705 feat: support projectID for gitlab CreateFile (brew, nix, etc)
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: size/M

#4711 feat: allow to delete existing artifacts in the release
  internal/client/github.go
  pkg/config/config.go
  www/docs/customization/release.md
Labels: enhancement, size/M

#4712 fix(aur): allow to have multiple AUR configs pointing to the same repo
  internal/client/git.go
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
Labels: bug, size/L

#4725 feat(git): retry git clone on retriable error
  internal/client/git.go
Labels: size/M

#4714 feat: add metadata to the release
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/http/http.go
  internal/http/http_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/upload.go
  internal/pipe/metadata/metadata.go
  internal/pipe/metadata/metadata_test.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  www/docs/customization/artifactory.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/upload.md
Labels: enhancement, size/L

#4729 fix: support dir in gomod
  internal/pipe/gomod/gomod.go
  internal/pipe/gomod/gomod_test.go
  pkg/config/config.go
  www/docs/customization/verifiable_builds.md
Labels: enhancement, size/M

#4734 fix(docs): update default for `build.id` attribute
  www/docs/customization/builds.md
Labels: size/XS

#4730 feat(archives): format override to 'none' to skip certain goos
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
Labels: enhancement, size/M

#4733 Fix typo username in dockerhubs example
  www/docs/customization/dockerhub.md
Labels: size/XS

#4736 Convert `run` install script to pure POSIX sh
  www/docs/static/run
Labels: size/XS
