Repository goreleaser/goreleaser, pull requests merged in 2024-12, with the labels that each got.

#5324 docs: improving home page a bit
  www/docs/cookbooks/goreleaser-xx.md
  www/docs/overrides/home.html
  www/mkdocs.yml
Labels: size/L

#5330 feat: add rustup and zig to packages optional dependencies
  .goreleaser.yaml
Labels: enhancement, size/XS

#5331 fix(typo): asmtags -> asmflags
  internal/builders/rust/build.go
  internal/builders/zig/build.go
Labels: size/XS

#5329 feat: handle healthcheck for builders
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/rust/build.go
  internal/builders/rust/build_test.go
  internal/builders/zig/build.go
  internal/builders/zig/build_test.go
  pkg/build/build.go
  pkg/build/build_test.go
  pkg/healthcheck/healthcheck.go
  pkg/healthcheck/healthcheck_test.go
Labels: enhancement, size/L

#5332 feat: --release and -Doptimize=ReleaseSafe for rust and zig
  internal/builders/rust/build.go
  internal/builders/rust/build_test.go
  internal/builders/zig/build.go
  internal/builders/zig/build_test.go
  internal/static/config.rust.yaml
  internal/static/config.zig.yaml
Labels: enhancement

#5328 feat: rename builds.*.gobinary to builds.*.tool
  internal/builders/buildtarget/targets_test.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/rust/build.go
  internal/builders/rust/build_test.go
  internal/builders/zig/build.go
  internal/builders/zig/build_test.go
  internal/pipe/build/build.go
  pkg/config/config.go
  www/docs/customization/builds.md
  www/docs/customization/rust-builds.md
  www/docs/customization/zig-builds.md
  www/docs/deprecations.md
Labels: enhancement, size/L

#5336 refactor: flag template processing
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/rust/build.go
  internal/builders/zig/build.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
Labels: enhancement

#5342 ci: notify goreleaser-rust-cross with the new release
  .github/workflows/release.yml
Labels: size/XS

#5226 feat(release): allow using existing draft release
  internal/client/github.go
  internal/client/github_test.go
  internal/client/testdata/github/releases.json
  pkg/config/config.go
  www/docs/customization/release.md
Labels: size/L

#5311 feat: AUR source integration
  internal/pipe/aursources/aursources.go
  internal/pipe/aursources/aursources_test.go
  internal/pipe/aursources/doc.go
  internal/pipe/aursources/testdata/TestFullAur.golden
  internal/pipe/aursources/testdata/TestFullPipe/custom-dir.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/custom-dir.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/default-gitlab.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/default-gitlab.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/default.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/default.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/double-quote-inside-description.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/double-quote-inside-description.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/mixed-quote-inside-description.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/mixed-quote-inside-description.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/simple-quote-inside-description.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/simple-quote-inside-description.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullPipe/with-more-opts.pkgbuild.golden
  internal/pipe/aursources/testdata/TestFullPipe/with-more-opts.srcinfo.golden
  internal/pipe/aursources/testdata/TestFullSrcInfo.golden
  internal/pipe/aursources/testdata/TestRunPipe.pkgbuild.golden
  internal/pipe/aursources/testdata/TestRunPipe.srcinfo.golden
  internal/pipe/aursources/testdata/TestRunPipeBinaryRelease.pkgbuild.golden
  internal/pipe/aursources/testdata/TestRunPipeBinaryRelease.srcinfo.golden
  internal/pipe/aursources/testdata/TestRunPipeWrappedInDirectory.pkgbuild.golden
  internal/pipe/aursources/testdata/TestRunPipeWrappedInDirectory.srcinfo.golden
  internal/pipe/aursources/tmpl.go
  internal/pipe/publish/publish.go
  internal/pipeline/pipeline.go
  internal/skips/skips.go
  internal/skips/skips_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/cmd/goreleaser_release.md
  www/docs/customization/aursources.md
  www/mkdocs.yml
Labels: enhancement, size/XXL

#5346 Doc fixes
  www/README.md
  www/docs/overrides/home.html
Labels: size/XS

#5319 fix(docker): retry on EOF
  internal/pipe/docker/docker.go
Labels: bug

#5353 feat(ko): support multiple repositories
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  pkg/config/config.go
  www/docs/customization/ko.md
  www/docs/deprecations.md
Labels: enhancement, size/L

#5360 chore: fix typos in comments, tests, and variables
  internal/builders/golang/build_test.go
  internal/pipe/brew/brew.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/changelog/testdata/changes-templated.md
  internal/pipe/changelog/testdata/changes.md
  internal/pipe/ko/ko.go
  internal/pipe/project/project.go
  internal/pipe/webhook/webhook.go
  internal/pipe/webhook/webhook_test.go
Labels: size/M

#5355 refactor: change from sort functions to slices functions
  internal/archivefiles/archivefiles.go
  internal/exec/exec_mock.go
  internal/pipe/aur/aur.go
  internal/pipe/aursources/aursources.go
  internal/pipe/brew/brew.go
  internal/pipe/checksums/checksums.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/manifest.go
  internal/pipe/krew/krew.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/sign/sign_test.go
  internal/skips/skips.go
Labels: size/L

#5359 fix: typo in the YAML tag for Webhook.ExpectedStatusCodes
  pkg/config/config.go
Labels: size/XS

#5348 fix(brew): do not use on_arm and on_intel
  internal/pipe/brew/templates/linux_packages.rb
  internal/pipe/brew/templates/macos_packages.rb
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
  internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden
Labels: bug, size/L

#5362 fix(archive): improve info messages
  internal/pipe/archive/archive.go
Labels: size/XS

#5366 refactor: simplify validateImager, validateManifester
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/docker/manifest_test.go
Labels: size/M

#5368 feat: changing descriptions everywhere, more docs touches
  .goreleaser.yaml
  README.md
  cmd/root.go
  main.go
  www/docs/intro.md
  www/docs/quick-start.md
  www/mkdocs.yml
Labels: size/M

#5350 docs: 2.5 release notes
  www/docs/blog/posts/2024-12-15-v2.5.md
Labels: size/L

#5377 fix(rust): better cargo workspaces check
  internal/builders/rust/build.go
  internal/builders/rust/build_test.go
  www/docs/customization/rust-builds.md
Labels: bug, size/M, eco/rust

#5378 fix(rust,zig): improve init, experimental warn
  cmd/init.go
  cmd/init_test.go
  cmd/root.go
  internal/builders/rust/build.go
  internal/builders/zig/build.go
Labels: enhancement, size/L, eco/rust, eco/zig

#5379 fix: improve goreleaser build --single-target
  internal/builders/golang/build.go
  internal/pipe/build/build.go
  internal/pipe/build/filter.go
  internal/pipe/build/filter_test.go
  internal/pipe/partial/partial.go
  internal/pipe/partial/partial_test.go
  pkg/build/build.go
Labels: enhancement, size/L, eco/rust, eco/go, eco/generic, eco/zig

#5385 Update documentation links
  www/docs/customization/builds.md
Labels: size/M

#5398 test(gitea): use fake server
  internal/client/client_test.go
  internal/client/gitea_test.go
Labels: bug, size/S

#5393 fix(aur_sources): missing new line
  internal/pipe/aursources/testdata/TestFullAur.golden
  internal/pipe/aursources/tmpl.go
Labels: size/XS

#5399 fix(rust): artifact filter when builder is rust
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
Labels: bug, size/S, eco/rust

#5394 docs: cargo publish
  www/docs/customization/rust-builds.md
Labels: docs, eco/rust

#5286 ci: codeql erroring since dagger
  .github/workflows/codeql.yml
Labels: size/S

#5400 ci: fix codeql hopefuly
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/dagger-build.yml
  dagger.json
  dagger/build.go
  dagger/go.mod
  dagger/go.sum
  dagger/main.go
  dagger/run.go
  dagger/test.go
Labels: size/L

#5401 refactor(cargo): workplaces -> workspaces
  internal/cargo/cargo_test.go
  internal/cargo/testdata/workspaces.Cargo.toml
Labels: size/XS

#5402 chore: delete extraneous .gitignore
  internal/builders/rust/testdata/.gitignore
Labels: size/XS
