Repository goreleaser/goreleaser, pull requests merged in 2024-02, with the labels that each got.

#4617 Fix sort order of brew artifacts
  internal/pipe/brew/brew.go
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
Labels: size/M

#4614 feat: use go 1.22
  .golangci.yaml
  CONTRIBUTING.md
  cmd/util_test.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/ko/testdata/app/go.mod
  www/docs/install.md
Labels: enhancement, size/S

#4622 chore(deps): update go-github to v59
  go.mod
  go.sum
  internal/client/github.go
  internal/client/github_test.go
Labels: size/S

#4627 fix: better universalbinary message
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  www/docs/customization/universalbinaries.md
Labels: size/S

#4631 fix(build): buildmode: pie
  pkg/config/config.go
  www/docs/customization/builds.md
Labels: size/XS

#4636 test(pipe): fix tests cleanup
  .golangci.yaml
  internal/pipe/before/before_test.go
  internal/pipe/sign/sign_test.go
Labels: size/S

#4638 docs: bump setup-go version
  www/docs/ci/actions.md
Labels: size/XS

#4637 chore: fix all existing lint issues
  .github/workflows/lint.yml
  .golangci.yaml
  cmd/build.go
  cmd/docs.go
  cmd/healthcheck.go
  cmd/man.go
  cmd/schema.go
  internal/artifact/artifact_test.go
  internal/client/gitlab.go
  internal/gio/safe_test.go
  internal/http/http_test.go
  internal/middleware/errhandler/error_test.go
  internal/middleware/logging/logging_test.go
  internal/pipe/chocolatey/chocolatey_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/ko/ko.go
  internal/pipe/linkedin/client_test.go
  internal/pipe/milestone/milestone.go
Labels: size/M

#4633 feat(nfpm): also allow $NFPM_PASSPHRASE
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/M

#4626 feat(pipe/release): Mark GitHub releases as non-draft only after all artifacts are uploaded.
  internal/client/client.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/client/mock.go
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
  www/docs/customization/release.md
Labels: size/M

#4640 test: simplify error asserts with require.ErrorContains
  internal/builders/golang/build_test.go
  internal/client/git_test.go
  internal/git/git_test.go
  internal/pipe/archive/archive_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/before/before_test.go
  internal/pipe/build/build_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/env/env_test.go
  internal/pipe/git/git_test.go
  internal/pipe/ko/ko_test.go
  internal/pipe/pipe_test.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/semver/semver_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/upload/upload_test.go
Labels: size/M

#4648 feat(brew): allow to set headers in the url
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/templates/linux_packages.rb
  internal/pipe/brew/templates/macos_packages.rb
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew.md
Labels: enhancement, size/L

#4658 feat(winget): update manifest version to 1.6.0
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.installer.yaml.golden
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestFormatBinary/TestFormatBinary.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/bad-commit-msg-tmpl/bad-commit-msg-tmpl.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/full/full.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/minimal/minimal.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/open-pr/open-pr.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/partial/partial.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload-auto/skip-upload-auto.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/skip-upload/skip-upload.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/with-deps/with-deps.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.installer.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.yaml.golden
Labels: size/L

#4652 DOCS: Sort the GoReleaser configuration YAML code examples
  www/docs/customization/archive.md
  www/docs/customization/aur.md
  www/docs/customization/blob.md
  www/docs/customization/builds.md
  www/docs/customization/changelog.md
  www/docs/customization/checksum.md
  www/docs/customization/docker.md
  www/docs/customization/docker_sign.md
  www/docs/customization/git.md
  www/docs/customization/metadata.md
  www/docs/customization/nfpm.md
  www/docs/customization/publishers.md
  www/docs/customization/release.md
  www/docs/customization/snapcraft.md
  www/docs/customization/source.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/winget.md
  www/docs/includes/repository.md
Labels: size/M
