Repository goreleaser/goreleaser, pull requests merged in 2024-06, with the labels that each got.

#4915 fix: init in v2
  internal/static/config.yaml
  internal/static/config_test.go
Labels: bug

#4922 docs: added the missing deprecation notices deep link to v2 section
  www/docs/blog/posts/2024-06-04-goreleaser-v2.md
Labels: size/XS

#4921 Do not upload artifacts if `blobs: ids: []` is set
  internal/pipe/blob/upload.go
Labels: size/XS

#4919 feat(notary): allow to sign without notarizing
  internal/pipe/notary/macos.go
  www/docs/customization/notarize.md
Labels: enhancement, size/S

#4916 feat: --skip=archive
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/skips/skips.go
Labels: enhancement, size/S

#4901 feat(nfpm): support arm in termux
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
Labels: enhancement, size/XS

#4870 feat(archive): support `.tzst` suffix
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  www/docs/customization/archive.md
Labels: enhancement, size/XS

#4858 feat(chocolatey): allow template in copyright, provide ctx.ReleaseNotes
  internal/pipe/chocolatey/chocolatey.go
  www/docs/customization/chocolatey.md
Labels: enhancement, size/XS

#4917 feat: build --auto-snapshot
  cmd/build.go
  cmd/build_test.go
  cmd/util_test.go
Labels: enhancement, size/M

#4925 feat(blob): allow to upload only extra_files
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/upload.go
  pkg/config/config.go
  www/docs/customization/blob.md
Labels: size/L

#4938 docs(notarize): use a Application cert not an Installer cert
  www/docs/customization/notarize.md
Labels: size/XS

#4940 feat: support extra_files in http upload and artifactories
  internal/http/http.go
  internal/http/http_test.go
  internal/http/testdata/foo.txt
  pkg/config/config.go
  www/docs/customization/artifactory.md
  www/docs/customization/blob.md
  www/docs/customization/upload.md
Labels: enhancement

#4941 feat(build): use GOCACHEPROG if set
  internal/builders/golang/build.go
Labels: size/XS

#4918 fix(gitlab): better handle CI_JOB_TOKEN and unavailable APIs
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: bug, size/M

#4942 fix: actually respect changelog.abbrev
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: bug, size/S

#4949 Fixed missing closing quote
  www/docs/customization/notarize.md
Labels: size/XS

#4953 docs: improving home page
  www/docs/index.md
  www/docs/overrides/home.html
  www/docs/static/goreleaser.svg
Labels: size/L

#4964 docs: Fix deprecation keyword in `.gitlab-ci.yml`
  www/docs/ci/gitlab.md
Labels: size/XS

#4963 fix: snapcraft temporary directory + concurrency
  .github/workflows/build.yml
  .github/workflows/release.yml
  internal/pipe/snapcraft/snapcraft.go
  internal/semerrgroup/sem.go
  internal/semerrgroup/sem_test.go
Labels: size/M

#4966 fix: make latest on drafts
  internal/client/github.go
Labels: bug, size/S, pro
