Repository goreleaser/goreleaser, pull requests merged in 2024-11, with the labels that each got.

#5239 fix: build override
  internal/builders/golang/build.go
  pkg/config/config.go
Labels: size/S

#5243 Update deprecated config documentation
  www/docs/errors/resource-not-accessible-by-integration.md
Labels: size/XS

#5242 fix(changelog): first release default to git changelogger
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: size/S

#5246 docs: fix typos in comments
  internal/builders/golang/build_test.go
  internal/client/gitlab_test.go
  internal/pipe/blob/upload.go
  internal/pipe/sign/sign_test.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
Labels: size/S

#5251 fix: typo in JSON property for OpenCollective announce
  pkg/config/config.go
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: size/XS

#5253 test: remove redundant require.Error
  internal/pipe/slack/slack_test.go
  pkg/config/config_slack_test.go
Labels: size/XS

#5256 chore: fix typo in script name
  Taskfile.yml
  scripts/nix-update-flake.sh
Labels: size/XS

#5257 test: remove redundant os.Exit in TestMain
  internal/exec/exec_mock_test.go
  internal/pipe/before/before_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/env/env_test.go
  internal/pipe/sign/sign_test.go
Labels: size/S

#5272 fix(changelog): fix for no tags
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: bug, size/S

#5276 fix(jsonschema): add custom JSONSchema type to umask
  pkg/config/config.go
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: size/XS

#5283 fix: URL escape tags in github, gitlab, and gitea
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/client/mock.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: bug

#5287 fix: typo in the git SSH command constant
  internal/client/git.go
Labels: size/XS

#5289 feat: pass context.Context to HTTP requests
  .golangci.yaml
  internal/pipe/linkedin/client.go
  internal/pipe/linkedin/client_test.go
  internal/pipe/linkedin/linkedin.go
  internal/pipe/webhook/webhook.go
Labels: size/M

#5263 ci: run build/test workflow on windows too
  .github/workflows/build.yml
  CONTRIBUTING.md
  Taskfile.yml
  cmd/init_test.go
  cmd/schema_test.go
  cmd/util_test.go
  dagger/test.go
  go.mod
  go.sum
  internal/builders/golang/build_test.go
  internal/client/gitlab_test.go
  internal/exec/exec.go
  internal/exec/exec_test.go
  internal/gio/copy_test.go
  internal/gio/hash_test.go
  internal/golden/golden.go
  internal/http/http.go
  internal/pipe/archive/archive_test.go
  internal/pipe/artifactory/artifactory_test.go
  internal/pipe/before/before_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/build/build_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/env/env_test.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/gomod/gomod_test.go
  internal/pipe/ko/ko_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nix/nix_test.go
  internal/pipe/release/release_test.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/sign/sign_binary_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/snapcraft/snapcraft_test.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/upload/upload_test.go
  internal/pipe/upx/upx.go
  internal/shell/shell_test.go
  internal/shell/shell_windows_test.go
  internal/testlib/docker.go
  internal/testlib/git.go
  internal/testlib/path.go
  internal/testlib/path_test.go
  internal/tmpl/tmpl_test.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/tarzst/tarzst_test.go
  pkg/archive/zip/zip_test.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/XL

#5288 build: update golangci-lint to v1.62
  .github/workflows/lint.yml
  cmd/root.go
  internal/archivefiles/archivefiles.go
  internal/git/config_test.go
Labels: size/S

#5280 chore(aur): remove dead code about armv6
  internal/pipe/aur/aur.go
Labels: size/XS

#5295 refactor: use cmp.Or instead of ordered.First
  go.mod
  go.sum
  internal/client/git.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/pipe/git/git.go
  internal/pipe/partial/partial.go
  internal/shell/shell.go
Labels: size/M

#5294 refactor: replace fmt.Errorf with errors.New for consistency
  .golangci.yaml
  cmd/build.go
  cmd/check.go
  cmd/healthcheck.go
  internal/client/client.go
  internal/client/git.go
  internal/client/gitlab.go
  internal/git/config.go
  internal/pipe/archive/archive.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/upload.go
  internal/pipe/brew/brew.go
  internal/pipe/docker/docker.go
  internal/pipe/krew/krew.go
  internal/pipe/linkedin/client.go
  internal/pipe/nix/nix.go
  internal/pipe/project/project.go
  internal/pipe/sbom/sbom.go
  internal/pipe/scoop/scoop.go
  internal/pipe/smtp/smtp.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/snapshot/snapshot.go
  internal/pipe/winget/winget.go
Labels: size/M

#5298 fix(build): overrides without specifying goarm64 et al
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: bug, size/L

#5304 fix(aur): description with quotes
  internal/pipe/aur/aur.go
  internal/pipe/aur/aur_test.go
  internal/pipe/aur/testdata/TestFullPipe/double-quote-inside-description.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/double-quote-inside-description.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/mixed-quote-inside-description.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/mixed-quote-inside-description.srcinfo.golden
  internal/pipe/aur/testdata/TestFullPipe/simple-quote-inside-description.pkgbuild.golden
  internal/pipe/aur/testdata/TestFullPipe/simple-quote-inside-description.srcinfo.golden
  internal/pipe/aur/tmpl.go
Labels: size/L

#5307 refactor(build): preparing to support multiple languages
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/golang/targets.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/pipe/universalbinary/targets.go
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/testlib/artifacts.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/build/build.go
  pkg/build/build_test.go
Labels: enhancement, size/XL

#5308 feat(template): allow to use .Target
  internal/artifact/artifact.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/pipe/archive/archive.go
  internal/pipe/snapcraft/snapcraft.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement, size/S

#5312 feat(build): initial support for zig
  .editorconfig
  .gitattributes
  .github/workflows/build.yml
  dagger/build.go
  internal/artifact/artifact.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/zig/all_targets.txt
  internal/builders/zig/build.go
  internal/builders/zig/build_test.go
  internal/builders/zig/error_targets.txt
  internal/builders/zig/targets.go
  internal/builders/zig/targets_test.go
  internal/builders/zig/testdata/.gitignore
  internal/builders/zig/testdata/main.c
  internal/builders/zig/testdata/proj/.gitignore
  internal/builders/zig/testdata/proj/build.zig
  internal/builders/zig/testdata/proj/build.zig.zon
  internal/builders/zig/testdata/proj/src/main.zig
  internal/builders/zig/testdata/proj/src/root.zig
  internal/builders/zig/testdata/targets.sh
  internal/builders/zig/testdata/version.txt
  internal/pipe/build/build.go
  www/docs/customization/builds.md
  www/docs/overrides/hooks/shortcodes.py
Labels: enhancement, size/XXL

#5317 feat(pipe): implement expected_status_codes for webhooks
  internal/pipe/webhook/webhook.go
  internal/pipe/webhook/webhook_test.go
  pkg/config/config.go
  www/docs/customization/announce/webhook.md
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: size/M
