Repository goreleaser/goreleaser, pull requests merged in 2024-07, with the labels that each got.

#4863 feat(packaging): add support for ipk package format
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/L

#4991 Update blob.md `neq` -> `ne`
  www/docs/customization/blob.md
Labels: size/XS

#4993 chore(deps): bump golang to 1.22.5-alpine
  Dockerfile
Labels: size/XS

#4987 docs: v2.1 announcement
  www/docs/blog/posts/2024-07-13-v2.1.md
Labels: size/M

#5019 feat: rename snapshot.name_template -> snapshot.version_template
  .goreleaser.yaml
  cmd/testdata/good.yml
  internal/pipe/snapshot/snapshot.go
  internal/pipe/snapshot/snapshot_test.go
  pkg/config/config.go
  www/docs/deprecations.md
Labels: enhancement, size/M

#5034 Revert "chore(deps): bump gocloud.dev from 0.37.0 to 0.38.0 (#5028)"
  go.mod
  go.sum
Labels: bug
