Repository goreleaser/goreleaser, pull requests merged in 2024-04, with the labels that each got.

#4737 feat: consistently use directory in property names
  .goreleaser.yaml
  USERS.md
  cmd/build.go
  cmd/release.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_test.go
  internal/pipe/blob/upload.go
  internal/pipe/brew/brew.go
  internal/pipe/dist/dist.go
  internal/pipe/scoop/scoop.go
  internal/pipeline/pipeline.go
  pkg/config/config.go
  www/docs/cmd/goreleaser_announce.md
  www/docs/cmd/goreleaser_build.md
  www/docs/cmd/goreleaser_continue.md
  www/docs/cmd/goreleaser_publish.md
  www/docs/cmd/goreleaser_release.md
  www/docs/cookbooks/build-go-modules.md
  www/docs/customization/archive.md
  www/docs/customization/aur.md
  www/docs/customization/blob.md
  www/docs/customization/builds.md
  www/docs/customization/docker.md
  www/docs/customization/homebrew.md
  www/docs/customization/krew.md
  www/docs/customization/metadata.md
  www/docs/customization/nfpm.md
  www/docs/customization/nix.md
  www/docs/customization/scoop.md
  www/docs/customization/snapshots.md
  www/docs/customization/source.md
  www/docs/customization/templatefiles.md
  www/docs/customization/winget.md
  www/docs/deprecations.md
  www/docs/errors/docker-build.md
  www/docs/errors/no-main.md
  www/docs/static/schema-pro.json
Labels: enhancement, size/L

#4739 fix `run` not being truly POSIX-compliant
  www/docs/static/run
Labels: size/XS

#4740 docs: Minor edits to 'dockerhub'
  www/docs/customization/dockerhub.md
Labels: size/XS

#4745 fix(release): publish tag with skip_upload
  internal/pipe/release/release.go
  internal/pipe/release/release_test.go
Labels: bug, size/M

#4744 fix(release): only change release draft status on new releases
  internal/client/github.go
Labels: bug, size/XS

#4748 build: simplify
  .github/workflows/build.yml
  scripts/test.sh
Labels: enhancement, size/S

#4750 docs: fix deprecation typos
  www/docs/deprecations.md
Labels: size/XS

#4756 fix: use correct path variable for logging in check command
  cmd/check.go
Labels: size/XS

#4765 fix: typo in User-Agent header value
  internal/pipe/webhook/webhook.go
Labels: size/XS

#4764 docs: fix typos
  www/docs/blog/posts/2022-02-05-cloud-native-storage.md
  www/docs/blog/posts/2022-02-20-azure-devops.md
  www/docs/blog/posts/2023-05-05-goreleaser-v1.18.md
  www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md
  www/docs/customization/artifactory.md
  www/docs/errors/docker-build.md
Labels: size/M

#4763 docs: description for chocolateys.package_source_url
  www/docs/customization/chocolatey.md
Labels: size/XS

#4766 Update dirty.md deprecated syntax
  www/docs/errors/dirty.md
Labels: size/XS

#4769 chore: fix some comments
  internal/builders/golang/build_test.go
  internal/pipe/sign/testdata/README.md
  www/docs/blog/posts/2023-05-05-goreleaser-v1.18.md
  www/docs/blog/posts/2023-10-08-slsa-generation-for-your-artifacts.md
Labels: size/XS

#4781 Update SBOM generation to add .json as file type
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  www/docs/customization/sbom.md
Labels: size/L

#4771 feat(cmd): release --draft
  cmd/release.go
Labels: enhancement, size/XS

#4775 feat: isEnvSet tmpl function
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  www/docs/customization/templates.md
Labels: enhancement

#4784 Add mdv2escape for ProjectName in default telegram message template
  internal/pipe/telegram/telegram.go
  www/docs/customization/announce/telegram.md
Labels: size/XS

#4788 Optimize strings replacers
  internal/deprecate/deprecate.go
  internal/pipe/nfpm/nfpm.go
  internal/tmpl/tmpl.go
Labels: size/M

#4787 feat: always log build output
  internal/builders/golang/build.go
Labels: bug

#4786 fix: winget paths on windows
  internal/pipe/winget/template.go
  internal/pipe/winget/winget.go
Labels: bug

#4789 chore(deps): update env from v9 to v11
  go.mod
  go.sum
  internal/pipe/discord/discord.go
  internal/pipe/linkedin/linkedin.go
  internal/pipe/mastodon/mastodon.go
  internal/pipe/mattermost/mattermost.go
  internal/pipe/opencollective/opencollective.go
  internal/pipe/reddit/reddit.go
  internal/pipe/slack/slack.go
  internal/pipe/smtp/smtp.go
  internal/pipe/teams/teams.go
  internal/pipe/telegram/telegram.go
  internal/pipe/twitter/twitter.go
  internal/pipe/webhook/webhook.go
Labels: dependencies

#4774 feat: notarize macos binaries
  .github/workflows/depsreview.yaml
  .github/workflows/release.yml
  .goreleaser.yaml
  go.mod
  go.sum
  internal/pipe/notary/macos.go
  internal/pipe/notary/macos_test.go
  internal/pipe/notary/notary.go
  internal/pipeline/pipeline.go
  internal/skips/skips.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/msi.md
  www/docs/customization/notarize.md
  www/mkdocs.yml
Labels: enhancement, size/XL

#4798 improve -p help message
  cmd/build.go
Labels: size/XS

#4779 feat(announce): add BlueSky support
  go.mod
  go.sum
  internal/pipe/announce/announce.go
  internal/pipe/bluesky/bluesky.go
  internal/pipe/bluesky/bluesky_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/announce/bluesky.md
  www/mkdocs.yml
Labels: size/L

#4794 feat(gitea): implement `Changelog` function
  internal/client/gitea.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  www/docs/customization/changelog.md
Labels: size/M

#4792 fix(gitlab): Use start_branch for file creation if branch doesn't exist already
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: size/L

#4793 feat(gitlab): Allow PRs to be created
  internal/client/config.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
Labels: enhancement, size/L

#4802 feat(changelog): custom commit format
  internal/client/client.go
  internal/client/gitea.go
  internal/client/gitea_test.go
  internal/client/github.go
  internal/client/github_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/client/mock.go
  internal/client/testdata/github/compare.json
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  www/docs/customization/changelog.md
Labels: enhancement, size/L

#4812 fix(nfpm): termux platform
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  www/docs/customization/nfpm.md
Labels: size/M

#4814 fix(brew): cpu conditionals
  internal/pipe/brew/templates/macos_packages.rb
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeMacOSOnly.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeUniversalBinaryNotReplacing.rb.golden
Labels: size/M
