Repository goreleaser/goreleaser, pull requests merged in 2024-05, with the labels that each got.

#4821 Fix telegram default message
  go.mod
  go.sum
  internal/pipe/telegram/telegram.go
  internal/pipe/telegram/telegram_test.go
  www/docs/customization/announce/telegram.md
Labels: size/S

#4822 feat: migrate to new homebrew constuctions (on_arm, on_intel)
  internal/pipe/brew/templates/linux_packages.rb
  internal/pipe/brew/templates/macos_packages.rb
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
  internal/pipe/brew/testdata/TestRunPipeNameTemplate.rb.golden
  www/docs/customization/homebrew.md
Labels: size/L

#4826 fix: temp disable snapcraft
  .goreleaser.yaml
  internal/pipe/snapcraft/snapcraft_test.go
Labels: bug, size/XS

#4825 feat(archive): support tar.zst
  go.mod
  pkg/archive/archive.go
  pkg/archive/archive_test.go
  pkg/archive/tarzst/tarzst.go
  pkg/archive/tarzst/tarzst_test.go
  www/docs/customization/archive.md
Labels: enhancement, size/L

#4830 Revert "fix: temp disable snapcraft"
  .github/workflows/build.yml
  .github/workflows/release.yml
  .goreleaser.yaml
  internal/pipe/snapcraft/snapcraft_test.go
Labels: size/S

#4839 Update USERS.md
  USERS.md
Labels: size/XS

#4849 build: use latest snapcraft
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: size/XS

#4850 feat(checksum): supports BLAKE2 and SHA-3
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  www/docs/customization/checksum.md
Labels: size/M

#4832 blob: permit skipping the configuration of the Content-Disposition header
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_test.go
  www/docs/customization/blob.md
Labels: size/S

#4851 docs: announce v1.26
  go.mod
  go.sum
  internal/client/github.go
  internal/client/github_test.go
  www/docs/blog/posts/2024-05-11-goreleaser-v1.26.md
Labels: size/M

#4857 fix: close HTTP resp body to prevent resource leak
  .golangci.yaml
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/discord/discord.go
Labels: size/S

#4856 refactor: remove unneeded in Go 1.22 loop var copy
  .github/workflows/lint.yml
  .golangci.yaml
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/exec/exec.go
  internal/http/http.go
  internal/pipe/archive/archive.go
  internal/pipe/artifactory/artifactory.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/upload.go
  internal/pipe/build/build.go
  internal/pipe/checksums/checksums.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
  internal/pipe/ko/ko_test.go
  internal/pipe/nfpm/nfpm.go
  internal/pipe/release/body_test.go
  internal/pipe/release/release.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/universalbinary/universalbinary.go
  internal/pipe/upload/upload.go
  internal/pipe/upx/upx.go
  internal/semerrgroup/sem_test.go
  internal/tmpl/tmpl_test.go
  main_test.go
  pkg/archive/archive_test.go
Labels: enhancement, size/M

#4855 docs: update old Go website links
  CONTRIBUTING.md
  internal/builders/buildtarget/targets.go
  internal/builders/golang/build_test.go
  www/docs/contributing.md
  www/docs/cookbooks/using-main.version.md
  www/docs/customization/builds.md
  www/docs/customization/templates.md
Labels: size/M

#4854 chore: fix nolintlint issues
  .golangci.yaml
  cmd/build.go
  cmd/release.go
  internal/artifact/artifact.go
  internal/builders/buildtarget/targets.go
  internal/builders/golang/build.go
  internal/client/gitea.go
  internal/client/github.go
  internal/client/gitlab.go
  internal/exec/exec.go
  internal/exec/exec_mock.go
  internal/http/http.go
  internal/pipe/announce/announce.go
  internal/pipe/archive/archive.go
  internal/pipe/docker/api.go
  internal/pipe/docker/docker.go
  internal/pipe/git/git.go
  internal/pipe/gomod/gomod_proxy.go
  internal/pipe/krew/krew.go
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_test.go
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/sourcearchive/source.go
  internal/pipe/winget/template.go
  internal/pipeline/pipeline.go
  main.go
  pkg/archive/gzip/gzip_test.go
  pkg/archive/tar/tar_test.go
  pkg/archive/targz/targz_test.go
  pkg/archive/tarxz/tarxz_test.go
  pkg/archive/tarzst/tarzst_test.go
  pkg/archive/zip/zip_test.go
  pkg/build/build.go
  pkg/config/config.go
  pkg/defaults/defaults.go
  pkg/healthcheck/healthcheck.go
Labels: size/L

#4859 chore: fix exe typo in .gitignore
  .gitignore
Labels: size/XS

#4869 fix(build): do not print 'go: downloading' bits of go build output
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
Labels: size/M

#4865 fix: disable logs on some commands
  cmd/root.go
  cmd/root_test.go
Labels: bug

#4875 Update winget.md path docs
  www/docs/customization/winget.md
Labels: size/XS

#4878 fix(docs): version typo
  www/docs/ci/actions.md
Labels: size/XS

#4806 feat!: v2
  cmd/build_test.go
  cmd/check_test.go
  cmd/release_test.go
  cmd/testdata/unmarshal_error.yml
  cmd/util_test.go
  internal/artifact/artifact_test.go
  internal/pipe/archive/archive.go
  internal/pipe/blob/blob.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/blob/blob_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/template.go
  internal/pipe/brew/templates/cask.rb
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/krew/krew.go
  internal/pipe/krew/krew_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/sourcearchive/source.go
  pkg/config/config.go
  pkg/config/config_homebrew_dependency_test.go
  pkg/config/config_test.go
  pkg/config/load.go
  pkg/config/testdata/anchor.yaml
  pkg/config/testdata/invalid.yml
  pkg/config/testdata/invalid_config.yml
  www/docs/deprecations.md
Labels: enhancement, size/XL

#4892 feat!: more v2 cleanups
  cmd/build.go
  cmd/build_test.go
  cmd/release.go
  cmd/release_test.go
  cmd/root.go
  cmd/root_test.go
Labels: enhancement, size/L
