Repository goreleaser/goreleaser, pull requests merged in 2024-09, with the labels that each got.

#5109 test: check if pre-requisites are installed
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/ko/ko_test.go
  internal/pipe/sign/sign_binary_test.go
  internal/pipe/sign/sign_test.go
  internal/testlib/path.go
Labels: size/M

#5114 fix: build --single-target filters
  cmd/build.go
  internal/pipe/build/filter.go
  internal/pipe/build/filter_test.go
  internal/pipe/partial/partial.go
  internal/pipe/partial/partial_test.go
Labels: enhancement, size/M

#5115 feat(build): templateable no_unique_dist_dir
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
  pkg/config/config.go
  www/docs/customization/builds.md
Labels: enhancement, size/M

#5122 feat(tmpl): IsSingleTarget
  cmd/build.go
  internal/tmpl/tmpl.go
  internal/tmpl/tmpl_test.go
  pkg/context/context.go
  www/docs/cmd/goreleaser_build.md
  www/docs/customization/templates.md
Labels: enhancement, size/XS

#5116 feat(ko): snapshot builds
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  internal/pipeline/pipeline.go
  www/docs/customization/ko.md
Labels: enhancement, size/M

#5128 fix(build,release): c-shared build and release when target is wasm
  internal/builders/golang/build.go
  internal/pipe/build/build.go
  internal/pipe/build/build_test.go
Labels: size/XS

#5134 docs: announce v2.3
  www/docs/blog/posts/2024-09-12-v2.3.md
Labels: size/M

#5137 docs: Add GH Actions OIDC permission docs
  www/docs/ci/actions.md
Labels: size/XS

#4969 Daggerize test pipeline
  .github/workflows/dagger-build.yml
  CONTRIBUTING.md
  dagger.json
  dagger/.gitattributes
  dagger/.gitignore
  dagger/build.go
  dagger/go.mod
  dagger/go.sum
  dagger/lint.go
  dagger/main.go
  dagger/run.go
  dagger/test.go
Labels: enhancement, size/XL

#5149 docs: correct spelling errors in documentation
  www/docs/blog/posts/2024-09-12-v2.3.md
  www/docs/install.md
Labels: size/XS

#5148 fix: signature template failed silently after signing process completed
  internal/pipe/sign/sign.go
  internal/pipe/sign/sign_binary_test.go
Labels: size/M

#5159 fix: remove filetype exe from chocolatey template
  internal/pipe/chocolatey/template.go
Labels: bug, size/XS

#5157 feat: default GOARM change to 7
  internal/builders/golang/build.go
  internal/experimental/exp.go
  internal/experimental/exp_test.go
  internal/pipe/brew/brew.go
  internal/pipe/docker/docker.go
  internal/pipe/partial/partial.go
  pkg/context/context.go
  www/docs/experiments.md
  www/mkdocs.yml
Labels: enhancement, size/M

#5161 perf(changelog): improve changelog sort performance
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
Labels: size/M
