Repository goreleaser/goreleaser, pull requests merged in 2025-07, with the labels that each got.

#5866 fix(rust): properly group binaries by platform
  internal/builders/rust/build.go
  internal/builders/rust/build_test.go
  internal/builders/rust/targets.go
Labels: bug, size/M

#5872 feat: log duration of all shell commands
  internal/logext/styles.go
  internal/logext/styles_test.go
  internal/logext/testdata/TestDuration.txt.golden
  internal/middleware/logging/logging.go
  internal/shell/shell.go
Labels: enhancement, size/L

#5877 fix(deps): update to lipgloss/v2
  cmd/healthcheck.go
  cmd/root.go
  go.mod
  go.sum
  internal/deprecate/deprecate_test.go
  internal/deprecate/testdata/TestNotice.txt.golden
  internal/logext/styles.go
  internal/logext/writer_test.go
  internal/middleware/logging/logging.go
  main.go
Labels: enhancement, dependencies, size/M

#5878 feat: improve error handling
  cmd/build.go
  cmd/check.go
  cmd/error.go
  cmd/release.go
  cmd/root.go
  internal/gerrors/errors.go
  internal/gerrors/errors_test.go
  internal/pipe/build/build.go
  internal/pipe/pipe.go
  internal/pipe/pipe_test.go
Labels: size/L

#5883 fix(nix): improve nix-hash check
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
Labels: bug, size/M

#5885 fix(cask): invalid string quoting in uninstall/zap arrays
  internal/pipe/cask/template.go
  internal/pipe/cask/testdata/TestFullPipe/uninstall.rb.golden
  internal/pipe/cask/testdata/TestFullPipe/zap.rb.golden
Labels: bug, size/M

#5886 docs: announce v2.11
  www/docs/blog/posts/2025-07-08-v2.11.md
  www/docs/customization/aur.md
  www/docs/customization/aursources.md
  www/docs/customization/cloudsmith.md
  www/docs/customization/publishers.md
  www/docs/deprecations.md
  www/docs/includes/repository.md
Labels: docs, size/M

#5895 Update USERS.md
  USERS.md
Labels: size/XS

#5913 fix: exec.CommandContext
  internal/builders/bun/build_test.go
  internal/builders/deno/build_test.go
  internal/builders/golang/build_test.go
  internal/builders/poetry/build_test.go
  internal/builders/rust/build_test.go
  internal/builders/uv/build_test.go
  internal/builders/zig/build_test.go
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/git/git_test.go
  internal/pipe/gomod/gomod_proxy_test.go
  internal/pipe/gomod/gomod_test.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/project/project.go
  internal/pipe/project/project_test.go
  internal/pipe/sign/sign_test.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/upx/upx_test.go
  internal/testlib/docker.go
  internal/testlib/git.go
Labels: bug, size/M

#5925 ci: link announcement in the release notes
  .goreleaser.yaml
Labels: size/XS

#5924 fix: make brews deprecation "soft"
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
Labels: enhancement, size/S

#5929 fix(shell): prevent panic on empty commands
  internal/shell/shell.go
  internal/shell/shell_test.go
Labels: bug, size/S
