Repository goreleaser/goreleaser, pull requests merged in 2025-01, with the labels that each got.

#5405 test: init test projects on the spot for rust and zig
  .gitattributes
  internal/builders/rust/build_test.go
  internal/builders/rust/testdata/proj/.gitignore
  internal/builders/rust/testdata/proj/Cargo.lock
  internal/builders/rust/testdata/proj/Cargo.toml
  internal/builders/rust/testdata/proj/src/main.rs
  internal/builders/zig/build_test.go
  internal/builders/zig/testdata/proj/.gitignore
  internal/builders/zig/testdata/proj/build.zig
  internal/builders/zig/testdata/proj/build.zig.zon
  internal/builders/zig/testdata/proj/src/main.zig
  internal/builders/zig/testdata/proj/src/root.zig
Labels: size/M, eco/rust, eco/zig

#5407 fix(builders/bun): add missing targets
  internal/builders/bun/targets.txt
Labels: bug, size/S, eco/typescript

#5410 fix: don't assume username in tests
  internal/pipe/release/scm_test.go
Labels: size/XS

#5412 test: update gomod
  internal/pipe/gomod/gomod_proxy_test.go
Labels: bug, size/XS, eco/go

#5392 feat(nfpm): allow to set mtime on packages
  .goreleaser.yaml
  internal/pipe/nfpm/nfpm.go
  internal/pipe/nfpm/nfpm_test.go
  pkg/config/config.go
  www/docs/customization/nfpm.md
Labels: enhancement, size/L

#5408 feat(build): adds deno support
  .github/workflows/build.yml
  .goreleaser.yaml
  cmd/init.go
  flake.nix
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/builders/deno/build.go
  internal/builders/deno/build_test.go
  internal/builders/deno/targets.go
  internal/builders/deno/targets.txt
  internal/pipe/build/build.go
  internal/static/config.deno.yaml
  internal/static/config.go
  internal/static/config_test.go
  pkg/config/config.go
  pkg/healthcheck/healthcheck_test.go
  www/docs/cookbooks/builds-complex-envs.md
  www/docs/customization/builds/bun.md
  www/docs/customization/builds/deno.md
  www/docs/customization/builds/go.md
  www/docs/customization/builds/index.md
  www/docs/customization/builds/poetry.md
  www/docs/customization/builds/python.md
  www/docs/customization/builds/rust.md
  www/docs/customization/builds/uv.md
  www/docs/customization/builds/zig.md
  www/mkdocs.yml
Labels: enhancement, size/XL, eco/typescript

#5417 chore(license): happy new year
  LICENSE.md
Labels: size/XS

#5416 docs: small fixes to deno builder, environment setup
  www/docs/customization/builds/bun.md
  www/docs/customization/builds/deno.md
  www/docs/customization/builds/zig.md
Labels: size/S

#5419 fix: do not return nil if builder is invalid
  pkg/build/build.go
  pkg/build/fail.go
  pkg/build/fail_test.go
Labels: bug, size/M

#5420 feat(release/gh): allow templates in make_latest
  internal/client/github.go
  www/docs/customization/release.md
Labels: size/XS

#5423 docs: update docs
  www/docs/ci/index.md
  www/docs/customization/announce/index.md
  www/docs/customization/builds/bun.md
  www/docs/customization/builds/deno.md
  www/docs/customization/builds/go.md
  www/docs/customization/builds/hooks.md
  www/docs/customization/builds/index.md
  www/docs/customization/builds/rust.md
  www/docs/customization/builds/zig.md
  www/docs/customization/universalbinaries.md
  www/docs/customization/upx.md
  www/docs/quick-start.md
  www/mkdocs.yml
Labels: size/L

#5432 ci(nfpm): suggest builders instead of recommends
  .goreleaser.yaml
Labels: size/XS

#5438 test: improve speed, work on clean system
  cmd/init_test.go
  internal/builders/golang/build_test.go
  internal/client/gitlab.go
  internal/client/gitlab_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/env/env_test.go
  internal/pipe/gomod/gomod_proxy.go
  internal/pipe/gomod/gomod_proxy_test.go
Labels: bug, size/L, eco/go

#5441 fix: target filter byamd64 and byarm
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/nix/nix.go
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip-with-dependencies_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/zip_publish.nix.golden
  internal/shell/shell_test.go
Labels: size/M

#5443 fix: build --single-target infer target from runtime
  cmd/build.go
  internal/pipe/partial/partial.go
  internal/pipe/partial/partial_test.go
Labels: enhancement, size/M, eco/generic

#5449 feat(build): support solaris/sparc and solaris/sparc64 in golang builder
  internal/builders/buildtarget/targets.go
  internal/builders/buildtarget/targets_test.go
Labels: enhancement, size/XS, eco/go

#5451 feat(docker): suggest image if not found
  go.mod
  go.sum
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/docker/manifest.go
Labels: enhancement, size/M

#5456 test: improve stability of some tests
  internal/pipe/blob/blob_minio_test.go
  internal/pipe/docker/docker_test.go
  internal/pipe/ko/ko_test.go
  internal/shell/shell_test.go
  internal/testlib/docker.go
Labels: bug, size/M

#5465 feat(notarize): allows setting signing entitlements
  internal/pipe/notary/macos.go
  internal/pipe/notary/macos_test.go
  pkg/config/config.go
  www/docs/customization/notarize.md
Labels: size/M

#5455 feat(archive): allow to specify multiple formats
  .goreleaser.yaml
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/defaults/defaults_test.go
  pkg/config/config.go
  www/docs/customization/archive.md
  www/docs/deprecations.md
Labels: enhancement, size/L

#5437 docs: maintainers and emeritus
  www/docs/maintainers.md
  www/mkdocs.yml
Labels: size/L

#5468 fix(gitea): commit with no author
  internal/client/gitea.go
  internal/client/gitea_test.go
Labels: size/S

#5478 chore: update security policy
  SECURITY.md
Labels: size/XS

#5479 docs: remove unreleased for v2.6
  www/docs/customization/app_bundles.md
  www/docs/customization/archive.md
  www/docs/customization/builds/bun.md
  www/docs/customization/builds/deno.md
  www/docs/customization/changelog.md
  www/docs/customization/notarize.md
Labels: size/S

#5474 docs: attestations
  www/docs/customization/attestations.md
  www/mkdocs.yml
Labels: docs, size/M

#5484 test: avoid cross-compile in test
  .github/workflows/build.yml
  internal/builders/rust/build_test.go
  internal/testlib/path.go
Labels: size/M

#5492 fix(go): build env overrides
  internal/builders/bun/build.go
  internal/builders/common/common.go
  internal/builders/common/common_test.go
  internal/builders/deno/build.go
  internal/builders/golang/build.go
  internal/builders/golang/build_test.go
  internal/builders/rust/build.go
  internal/builders/zig/build.go
  internal/testlib/artifacts.go
Labels: size/M

#5486 Go report card badge
  README.md
Labels: size/XS

#5500 feat(http/artifactory): skip configuration
  internal/http/http.go
  internal/http/http_test.go
  pkg/config/config.go
  www/docs/customization/artifactory.md
  www/docs/customization/upload.md
  www/docs/static/schema-pro.json
Labels: size/L

#5501 feat: allow oss to use pro configurations when --snapshot is set
  .goreleaser-nightly.yaml
  cmd/build.go
  cmd/config.go
  cmd/config_test.go
  cmd/healthcheck.go
  cmd/release.go
  internal/yaml/yaml.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/load.go
  www/docs/errors/version.md
Labels: size/L

#5507 refactor: use math/rand/v2
  .golangci.yaml
  internal/client/client_test.go
  internal/pipe/sign/sign_test.go
Labels: size/S
