Repository goreleaser/goreleaser, pull requests merged in 2025-05, with the labels that each got.

#5746 fix(brew,nix): support txz, tgz, tzst, tar.zst
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/testdata/TestRunPipe/deps_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/deps_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/extra-install_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/extra-install_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/minimal_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/open-pr_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/partial_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload-auto_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/skip-upload_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/unibin-replaces_publish.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_build.nix.golden
  internal/pipe/nix/testdata/TestRunPipe/wrapped-in-dir_publish.nix.golden
Labels: bug, size/L

#5757 ci: fix lint
  .github/workflows/lint.yml
Labels: size/XS

#5767 chore(deps): update ko and nfpm
  go.mod
  go.sum
Labels: dependencies, size/L

#5759 Add blog post about packaging and publishing Go binaries on NPM which use GoReleaser as build tool
  www/docs/cookbooks/blog-posts.md
Labels: size/XS

#5771 fix(bun,deno): duplicated build flags
  internal/builders/bun/build.go
  internal/builders/deno/build.go
Labels: bug, size/S

#5775 fix(init): handle CRLF line endings in gitignore
  cmd/init.go
  cmd/init_test.go
Labels: bug, size/L

#5789 ci: fix zig action
  .github/workflows/build.yml
Labels: size/XS

#5787 feat: sbom.disable
  internal/pipe/sbom/sbom.go
  internal/pipe/sbom/sbom_test.go
  pkg/config/config.go
  www/docs/customization/sbom.md
Labels: enhancement, size/L
