Repository goreleaser/goreleaser, pull requests merged in 2025-03, with the labels that each got.

#5629 fix: package comment for packagejson
  .golangci.yaml
  internal/packagejson/packagejson.go
Labels: size/XS

#5627 feat(changelog): allow to use format when using the git changeloger
  internal/client/client.go
  internal/pipe/changelog/changelog.go
  internal/pipe/changelog/changelog_test.go
  internal/pipe/changelog/testdata/TestIssue5595/abbrev-sha.md.golden
  internal/pipe/changelog/testdata/TestIssue5595/no-sha.md.golden
  pkg/config/config.go
  www/docs/customization/changelog.md
Labels: size/XL

#5631 fix(archive): make sure binaries are executable
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
Labels: bug, size/M

#5639 docs: announce v2.8
  www/docs/blog/posts/2024-02-05-goreleaser-v1.24.md
  www/docs/blog/posts/2024-04-02-goreleaser-v1.25.md
  www/docs/blog/posts/2024-05-11-goreleaser-v1.26.md
  www/docs/blog/posts/2024-07-13-v2.1.md
  www/docs/blog/posts/2024-08-14-v2.2.md
  www/docs/blog/posts/2024-09-12-v2.3.md
  www/docs/blog/posts/2024-11-02-v2.4.md
  www/docs/blog/posts/2024-12-15-v2.5.md
  www/docs/blog/posts/2025-01-21-v2.6.md
  www/docs/blog/posts/2025-02-10-v2.7.md
  www/docs/blog/posts/2025-03-12-v2.8.md
Labels: size/L

#5642 fix: notify each deprecation only once
  internal/deprecate/deprecate.go
  internal/deprecate/deprecate_test.go
  pkg/context/context.go
Labels: bug, size/S

#5641 ci: publish to npm
  .github/workflows/nightly-oss.yml
  .github/workflows/release.yml
  .goreleaser-nightly.yaml
  .goreleaser-pro.yaml
  .goreleaser.yaml
  scripts/fury-upload.sh
Labels: size/M

#5651 perf: improve default gpg path detection
  internal/pipe/sign/sign.go
Labels: enhancement, size/S

#5661 docs: move sponsors to navbar
  www/mkdocs.yml
Labels: size/XS

#5435 wip: nodejs support
  .goreleaser.yaml
  cmd/init.go
  internal/builders/node/build.go
  internal/builders/node/build_test.go
  internal/builders/node/targets.go
  internal/builders/node/targets.txt
  internal/pipe/build/build.go
  internal/static/config.go
  internal/static/config.node.yaml
  internal/static/config_test.go
  pkg/config/config.go
  pkg/healthcheck/healthcheck_test.go
  www/docs/intro.md
Labels: size/L

#5664 fix(winget): make tags lowercase
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  www/docs/customization/winget.md
Labels: bug, size/XS

#5669 fix(nix): use nix-hash instead of nix-prefetch-url
  internal/pipe/nix/nix.go
  internal/pipe/nix/nix_test.go
  internal/pipe/nix/testdata/file.bin
Labels: bug, size/L

#5672 docs: fix build
  .github/dependabot.yml
  .github/dependency-review.yml
  .github/workflows/depsreview.yaml
  .github/workflows/docs.yml
  Taskfile.yml
  flake.lock
  flake.nix
  scripts/pages/build.sh
  www/Dockerfile
  www/README.md
  www/htmltest.yml
  www/requirements.txt
Labels: docs, size/L

#5684 test: simplify tests with usetesting linter
  .golangci.yaml
  cmd/init_test.go
  cmd/util_test.go
  internal/git/config_test.go
  internal/git/git_test.go
  internal/http/http_test.go
  internal/pipe/build/build_test.go
  internal/pipe/linkedin/client_test.go
  internal/testlib/git.go
  internal/testlib/mktemp.go
Labels: enhancement, size/M

#5685 refactor: ExtraOr, MustExtra
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/archive/archive.go
  internal/pipe/archive/archive_test.go
  internal/pipe/aur/aur.go
  internal/pipe/aursources/aursources.go
  internal/pipe/brew/brew.go
  internal/pipe/brew/brew_test.go
  internal/pipe/checksums/checksums_test.go
  internal/pipe/chocolatey/chocolatey.go
  internal/pipe/docker/docker.go
  internal/pipe/docker/docker_test.go
  internal/pipe/krew/krew.go
  internal/pipe/nfpm/nfpm_test.go
  internal/pipe/nix/nix.go
  internal/pipe/reportsizes/reportsizes_test.go
  internal/pipe/scoop/scoop.go
  internal/pipe/scoop/scoop_test.go
  internal/pipe/scoop/testdata/TestRunPipePullRequest.json.golden
  internal/pipe/scoop/testdata/Test_doRun/git_remote.json.golden
  internal/pipe/scoop/testdata/Test_doRun/valid_public_github.json.golden
  internal/pipe/snapcraft/snapcraft.go
  internal/pipe/universalbinary/universalbinary_test.go
  internal/pipe/winget/winget.go
  internal/tmpl/tmpl.go
Labels: bug, size/XL
