Repository goreleaser/goreleaser, pull requests merged in 2025-04, with the labels that each got.

#5709 chore(deps): bump gocloud.dev from 0.40.0 to 0.41.0
  go.mod
  go.sum
Labels: dependencies, size/L

#5688 feat: allow passing sbomDir to KO
  .gitignore
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  pkg/config/config.go
  www/docs/customization/ko.md
Labels: enhancement, size/S

#5717 fix(aur): panic if both aur and aur_sources configured
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
  internal/pipe/aursources/aursources.go
Labels: bug, size/S

#5720 fix: upx properly handle skips
  internal/pipe/upx/testdata/fakeupx
  internal/pipe/upx/testdata/fakeupx.bat
  internal/pipe/upx/upx.go
  internal/pipe/upx/upx_test.go
  www/docs/static/schema-pro.json
Labels: bug, size/L

#5726 fix: increase default timeout
  cmd/build.go
  cmd/release.go
Labels: enhancement, size/XS

#5714 feat(winget): Add additional template values
  internal/pipe/winget/template.go
  internal/pipe/winget/testdata/TestRunPipe/full/full.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/package_id/package_id.locale.en-US.yaml.golden
  internal/pipe/winget/testdata/TestRunPipe/wrapped-in-dir/wrapped-in-dir.locale.en-US.yaml.golden
  internal/pipe/winget/winget.go
  internal/pipe/winget/winget_test.go
  pkg/config/config.go
  www/docs/customization/winget.md
Labels: enhancement, size/M

#5741 fix(brew): improve if hardware structures
  .github/workflows/build.yml
  internal/pipe/brew/templates/linux_packages.rb
  internal/pipe/brew/testdata/TestFullFormulae.rb.golden
  internal/pipe/brew/testdata/TestFullFormulaeLinuxOnly.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_block.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_download_strategy.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/custom_require.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/default_gitlab.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/git_remote.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/open_pr.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/valid_repository_templates.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_header.rb.golden
  internal/pipe/brew/testdata/TestFullPipe/with_many_headers.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v1.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v2.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v3.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleAmd64Versions/v4.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv5.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv6.rb.golden
  internal/pipe/brew/testdata/TestRunPipeForMultipleArmVersions/multiple_armv7.rb.golden
Labels: bug, size/L

#5744 docs: v2.9 release
  www/docs/blog/posts/2025-04-29-v2.9.md
  www/docs/customization/builds/index.md
  www/docs/customization/builds/poetry.md
  www/docs/customization/builds/uv.md
  www/docs/customization/winget.md
  www/docs/install.md
Labels: size/L

#5745 docs: use recommended SPDX SBOM filename in example
  www/docs/customization/sbom.md
Labels: size/XS
