Repository goreleaser/goreleaser, pull requests merged in 2025-09, with the labels that each got.

#6043 docs: announce v2.12
  www/docs/blog/posts/2025-09-01-v2.12.md
Labels: size/L

#6089 fix(dockers/v2): properly support pywheel
  internal/pipe/docker/v2/docker.go
  internal/pipe/docker/v2/docker_integration_test.go
  internal/pipe/docker/v2/testdata/Dockerfile.python
Labels: bug

#6103 Fedora move exclude to repo config
  www/docs/install.md
Labels: size/S
