Repository goreleaser/goreleaser, pull requests merged in 2025-06, with the labels that each got.

#5800 feat: support addtional url parameters in homebrew cask
  internal/pipe/cask/cask.go
  internal/pipe/cask/cask_test.go
  internal/pipe/cask/template.go
  internal/pipe/cask/templates/additional_url_params.rb
  internal/pipe/cask/templates/linux_packages.rb
  internal/pipe/cask/templates/macos_packages.rb
  internal/pipe/cask/testdata/TestFullPipe/url_parameters_curl.rb.golden
  internal/pipe/cask/testdata/TestFullPipe/url_parameters_post.rb.golden
  pkg/config/config.go
  www/docs/customization/homebrew_casks.md
Labels: size/L

#5803 feat(cask): improve URL config
  internal/pipe/cask/cask.go
  internal/pipe/cask/cask_test.go
  internal/pipe/cask/template.go
  internal/pipe/cask/templates/additional_url_params.rb
  internal/pipe/cask/templates/linux_packages.rb
  internal/pipe/cask/templates/macos_packages.rb
  pkg/config/config.go
  www/docs/customization/homebrew_casks.md
Labels: size/L

#5806 ci(dagger): failing zig tests
  .github/workflows/dagger-build.yml
  dagger/test.go
Labels: size/S

#5810 Update USERS.md
  USERS.md
Labels: size/XS

#5809 feat(ko): allow configuration of local domain to allow publishing to other local registries (e.g. kind)
  internal/pipe/ko/ko.go
  internal/pipe/ko/ko_test.go
  pkg/config/config.go
  www/docs/customization/ko.md
  www/docs/static/schema-pro.json
  www/docs/static/schema.json
Labels: enhancement, size/M

#5798 feat: mcp server
  cmd/mcp.go
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement, size/L

#5825 fix: skip empty image_templates in docker_manifests
  internal/pipe/docker/manifest.go
  internal/pipe/docker/manifest_test.go
Labels: bug, size/L

#5831 feat: place `custom_block` on top of cask definition
  internal/pipe/cask/cask_test.go
  internal/pipe/cask/templates/cask.rb
  internal/pipe/cask/testdata/TestFullCask.rb.golden
  internal/pipe/cask/testdata/TestFullPipe/custom_block.rb.golden
  www/docs/customization/homebrew_casks.md
Labels: size/M

#5844 fix(cask): add test and docs for custom URL
  internal/pipe/cask/cask_test.go
  internal/pipe/cask/testdata/TestFullPipe/custom_block_url.rb.golden
  internal/pipe/cask/testdata/github.rb
  www/docs/customization/homebrew_casks.md
Labels: docs, size/L

#5849 fix: artifact.Checksum should set artifact.Extra field
  .golangci.yaml
  internal/artifact/artifact.go
  internal/artifact/artifact_test.go
Labels: size/S

#5850 chore(deps): update github.com/caarlos0/go-version from 0.2.0 to 0.2.1
  go.mod
  go.sum
  testdata/TestVersion/all_empty.json.golden
  testdata/TestVersion/complete.json.golden
  testdata/TestVersion/only_version.json.golden
  testdata/TestVersion/version,_date,_built_by.json.golden
  testdata/TestVersion/version_and_date.json.golden
Labels: size/S

#5845 fix(semver): skip=validate allows invalid semver
  internal/pipe/semver/semver.go
  internal/pipe/semver/semver_test.go
Labels: enhancement, size/S
